package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AberturaAgenda generated by hbm2java
 */
@Entity
@Table(name="ABERTURA_AGENDA"
    ,schema="DESENV"
)
public class AberturaAgenda  implements java.io.Serializable {


     private BigDecimal id;
     private Profissional profissional;
     private Empresa empresa;
     private Date dtAbertura;
     private Date dtFechamento;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set horarioAberturaAgendas = new HashSet(0);

    public AberturaAgenda() {
    }

	
    public AberturaAgenda(BigDecimal id, Profissional profissional, Empresa empresa, Date dtAbertura) {
        this.id = id;
        this.profissional = profissional;
        this.empresa = empresa;
        this.dtAbertura = dtAbertura;
    }
    public AberturaAgenda(BigDecimal id, Profissional profissional, Empresa empresa, Date dtAbertura, Date dtFechamento, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set horarioAberturaAgendas) {
       this.id = id;
       this.profissional = profissional;
       this.empresa = empresa;
       this.dtAbertura = dtAbertura;
       this.dtFechamento = dtFechamento;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.horarioAberturaAgendas = horarioAberturaAgendas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROF_ID", nullable=false)
    public Profissional getProfissional() {
        return this.profissional;
    }
    
    public void setProfissional(Profissional profissional) {
        this.profissional = profissional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ABERTURA", nullable=false, length=7)
    public Date getDtAbertura() {
        return this.dtAbertura;
    }
    
    public void setDtAbertura(Date dtAbertura) {
        this.dtAbertura = dtAbertura;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FECHAMENTO", length=7)
    public Date getDtFechamento() {
        return this.dtFechamento;
    }
    
    public void setDtFechamento(Date dtFechamento) {
        this.dtFechamento = dtFechamento;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aberturaAgenda")
    public Set getHorarioAberturaAgendas() {
        return this.horarioAberturaAgendas;
    }
    
    public void setHorarioAberturaAgendas(Set horarioAberturaAgendas) {
        this.horarioAberturaAgendas = horarioAberturaAgendas;
    }




}


