package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeAgendamento generated by hbm2java
 */
@Entity
@Table(name="AGE_AGENDAMENTO"
    ,schema="DESENV"
)
public class AgeAgendamento  implements java.io.Serializable {


     private BigDecimal cdAgendamento;
     private Empresa empresa;
     private String nmAgendamento;
     private Date dtSubmissao;
     private String flStatus;
     private String flTipoExecucao;
     private Date dtExecInicio;
     private Date dtExecFim;
     private BigDecimal nuExecIntervalo;
     private String flTipoIntervalo;
     private String flManterHorario;
     private BigDecimal nuAtrasoMaximo;
     private Date dtProximaExecucao;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set ageProgAgendamentos = new HashSet(0);

    public AgeAgendamento() {
    }

	
    public AgeAgendamento(BigDecimal cdAgendamento, Empresa empresa, String nmAgendamento, Date dtSubmissao, String flStatus, String flTipoExecucao, String flManterHorario, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdAgendamento = cdAgendamento;
        this.empresa = empresa;
        this.nmAgendamento = nmAgendamento;
        this.dtSubmissao = dtSubmissao;
        this.flStatus = flStatus;
        this.flTipoExecucao = flTipoExecucao;
        this.flManterHorario = flManterHorario;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public AgeAgendamento(BigDecimal cdAgendamento, Empresa empresa, String nmAgendamento, Date dtSubmissao, String flStatus, String flTipoExecucao, Date dtExecInicio, Date dtExecFim, BigDecimal nuExecIntervalo, String flTipoIntervalo, String flManterHorario, BigDecimal nuAtrasoMaximo, Date dtProximaExecucao, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set ageProgAgendamentos) {
       this.cdAgendamento = cdAgendamento;
       this.empresa = empresa;
       this.nmAgendamento = nmAgendamento;
       this.dtSubmissao = dtSubmissao;
       this.flStatus = flStatus;
       this.flTipoExecucao = flTipoExecucao;
       this.dtExecInicio = dtExecInicio;
       this.dtExecFim = dtExecFim;
       this.nuExecIntervalo = nuExecIntervalo;
       this.flTipoIntervalo = flTipoIntervalo;
       this.flManterHorario = flManterHorario;
       this.nuAtrasoMaximo = nuAtrasoMaximo;
       this.dtProximaExecucao = dtProximaExecucao;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.ageProgAgendamentos = ageProgAgendamentos;
    }
   
     @Id 

    
    @Column(name="CD_AGENDAMENTO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdAgendamento() {
        return this.cdAgendamento;
    }
    
    public void setCdAgendamento(BigDecimal cdAgendamento) {
        this.cdAgendamento = cdAgendamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NM_AGENDAMENTO", nullable=false, length=100)
    public String getNmAgendamento() {
        return this.nmAgendamento;
    }
    
    public void setNmAgendamento(String nmAgendamento) {
        this.nmAgendamento = nmAgendamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_SUBMISSAO", nullable=false, length=7)
    public Date getDtSubmissao() {
        return this.dtSubmissao;
    }
    
    public void setDtSubmissao(Date dtSubmissao) {
        this.dtSubmissao = dtSubmissao;
    }

    
    @Column(name="FL_STATUS", nullable=false, length=1)
    public String getFlStatus() {
        return this.flStatus;
    }
    
    public void setFlStatus(String flStatus) {
        this.flStatus = flStatus;
    }

    
    @Column(name="FL_TIPO_EXECUCAO", nullable=false, length=1)
    public String getFlTipoExecucao() {
        return this.flTipoExecucao;
    }
    
    public void setFlTipoExecucao(String flTipoExecucao) {
        this.flTipoExecucao = flTipoExecucao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_EXEC_INICIO", length=7)
    public Date getDtExecInicio() {
        return this.dtExecInicio;
    }
    
    public void setDtExecInicio(Date dtExecInicio) {
        this.dtExecInicio = dtExecInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_EXEC_FIM", length=7)
    public Date getDtExecFim() {
        return this.dtExecFim;
    }
    
    public void setDtExecFim(Date dtExecFim) {
        this.dtExecFim = dtExecFim;
    }

    
    @Column(name="NU_EXEC_INTERVALO", precision=22, scale=0)
    public BigDecimal getNuExecIntervalo() {
        return this.nuExecIntervalo;
    }
    
    public void setNuExecIntervalo(BigDecimal nuExecIntervalo) {
        this.nuExecIntervalo = nuExecIntervalo;
    }

    
    @Column(name="FL_TIPO_INTERVALO", length=1)
    public String getFlTipoIntervalo() {
        return this.flTipoIntervalo;
    }
    
    public void setFlTipoIntervalo(String flTipoIntervalo) {
        this.flTipoIntervalo = flTipoIntervalo;
    }

    
    @Column(name="FL_MANTER_HORARIO", nullable=false, length=1)
    public String getFlManterHorario() {
        return this.flManterHorario;
    }
    
    public void setFlManterHorario(String flManterHorario) {
        this.flManterHorario = flManterHorario;
    }

    
    @Column(name="NU_ATRASO_MAXIMO", precision=22, scale=0)
    public BigDecimal getNuAtrasoMaximo() {
        return this.nuAtrasoMaximo;
    }
    
    public void setNuAtrasoMaximo(BigDecimal nuAtrasoMaximo) {
        this.nuAtrasoMaximo = nuAtrasoMaximo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_PROXIMA_EXECUCAO", length=7)
    public Date getDtProximaExecucao() {
        return this.dtProximaExecucao;
    }
    
    public void setDtProximaExecucao(Date dtProximaExecucao) {
        this.dtProximaExecucao = dtProximaExecucao;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageAgendamento")
    public Set getAgeProgAgendamentos() {
        return this.ageProgAgendamentos;
    }
    
    public void setAgeProgAgendamentos(Set ageProgAgendamentos) {
        this.ageProgAgendamentos = ageProgAgendamentos;
    }




}


