package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeDetalhesExecucao generated by hbm2java
 */
@Entity
@Table(name="AGE_DETALHES_EXECUCAO"
    ,schema="DESENV"
)
public class AgeDetalhesExecucao  implements java.io.Serializable {


     private AgeDetalhesExecucaoId id;
     private AgeHitoricoProgAgend ageHitoricoProgAgend;
     private Empresa empresa;
     private String coluna1;
     private String coluna2;
     private String coluna3;
     private String coluna4;
     private String coluna5;
     private String coluna6;
     private String coluna7;
     private String flErro;
     private String dsMensagem;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public AgeDetalhesExecucao() {
    }

	
    public AgeDetalhesExecucao(AgeDetalhesExecucaoId id, AgeHitoricoProgAgend ageHitoricoProgAgend, Empresa empresa, String flErro) {
        this.id = id;
        this.ageHitoricoProgAgend = ageHitoricoProgAgend;
        this.empresa = empresa;
        this.flErro = flErro;
    }
    public AgeDetalhesExecucao(AgeDetalhesExecucaoId id, AgeHitoricoProgAgend ageHitoricoProgAgend, Empresa empresa, String coluna1, String coluna2, String coluna3, String coluna4, String coluna5, String coluna6, String coluna7, String flErro, String dsMensagem, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.ageHitoricoProgAgend = ageHitoricoProgAgend;
       this.empresa = empresa;
       this.coluna1 = coluna1;
       this.coluna2 = coluna2;
       this.coluna3 = coluna3;
       this.coluna4 = coluna4;
       this.coluna5 = coluna5;
       this.coluna6 = coluna6;
       this.coluna7 = coluna7;
       this.flErro = flErro;
       this.dsMensagem = dsMensagem;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cdDetalhe", column=@Column(name="CD_DETALHE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="histoCdHistorico", column=@Column(name="HISTO_CD_HISTORICO", nullable=false, precision=22, scale=0) ) } )
    public AgeDetalhesExecucaoId getId() {
        return this.id;
    }
    
    public void setId(AgeDetalhesExecucaoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="HISTO_CD_HISTORICO", nullable=false, insertable=false, updatable=false)
    public AgeHitoricoProgAgend getAgeHitoricoProgAgend() {
        return this.ageHitoricoProgAgend;
    }
    
    public void setAgeHitoricoProgAgend(AgeHitoricoProgAgend ageHitoricoProgAgend) {
        this.ageHitoricoProgAgend = ageHitoricoProgAgend;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="COLUNA_1")
    public String getColuna1() {
        return this.coluna1;
    }
    
    public void setColuna1(String coluna1) {
        this.coluna1 = coluna1;
    }

    
    @Column(name="COLUNA_2")
    public String getColuna2() {
        return this.coluna2;
    }
    
    public void setColuna2(String coluna2) {
        this.coluna2 = coluna2;
    }

    
    @Column(name="COLUNA_3")
    public String getColuna3() {
        return this.coluna3;
    }
    
    public void setColuna3(String coluna3) {
        this.coluna3 = coluna3;
    }

    
    @Column(name="COLUNA_4")
    public String getColuna4() {
        return this.coluna4;
    }
    
    public void setColuna4(String coluna4) {
        this.coluna4 = coluna4;
    }

    
    @Column(name="COLUNA_5")
    public String getColuna5() {
        return this.coluna5;
    }
    
    public void setColuna5(String coluna5) {
        this.coluna5 = coluna5;
    }

    
    @Column(name="COLUNA_6")
    public String getColuna6() {
        return this.coluna6;
    }
    
    public void setColuna6(String coluna6) {
        this.coluna6 = coluna6;
    }

    
    @Column(name="COLUNA_7")
    public String getColuna7() {
        return this.coluna7;
    }
    
    public void setColuna7(String coluna7) {
        this.coluna7 = coluna7;
    }

    
    @Column(name="FL_ERRO", nullable=false, length=1)
    public String getFlErro() {
        return this.flErro;
    }
    
    public void setFlErro(String flErro) {
        this.flErro = flErro;
    }

    
    @Column(name="DS_MENSAGEM", length=4000)
    public String getDsMensagem() {
        return this.dsMensagem;
    }
    
    public void setDsMensagem(String dsMensagem) {
        this.dsMensagem = dsMensagem;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


