package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeHitoricoProgAgend generated by hbm2java
 */
@Entity
@Table(name="AGE_HITORICO_PROG_AGEND"
    ,schema="DESENV"
)
public class AgeHitoricoProgAgend  implements java.io.Serializable {


     private BigDecimal cdHistorico;
     private AgeProgAgendamento ageProgAgendamento;
     private Empresa empresa;
     private Date dtInicioExec;
     private Date dtFimExec;
     private String flStatus;
     private String dsSaida;
     private String dsUrl;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private String dsComando;
     private Clob dsArquivo;
     private Set ageDetalhesExecucaos = new HashSet(0);

    public AgeHitoricoProgAgend() {
    }

	
    public AgeHitoricoProgAgend(BigDecimal cdHistorico, AgeProgAgendamento ageProgAgendamento, Empresa empresa, Date dtInicioExec, Date dtFimExec, String dsSaida, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdHistorico = cdHistorico;
        this.ageProgAgendamento = ageProgAgendamento;
        this.empresa = empresa;
        this.dtInicioExec = dtInicioExec;
        this.dtFimExec = dtFimExec;
        this.dsSaida = dsSaida;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public AgeHitoricoProgAgend(BigDecimal cdHistorico, AgeProgAgendamento ageProgAgendamento, Empresa empresa, Date dtInicioExec, Date dtFimExec, String flStatus, String dsSaida, String dsUrl, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, String dsComando, Clob dsArquivo, Set ageDetalhesExecucaos) {
       this.cdHistorico = cdHistorico;
       this.ageProgAgendamento = ageProgAgendamento;
       this.empresa = empresa;
       this.dtInicioExec = dtInicioExec;
       this.dtFimExec = dtFimExec;
       this.flStatus = flStatus;
       this.dsSaida = dsSaida;
       this.dsUrl = dsUrl;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.dsComando = dsComando;
       this.dsArquivo = dsArquivo;
       this.ageDetalhesExecucaos = ageDetalhesExecucaos;
    }
   
     @Id 

    
    @Column(name="CD_HISTORICO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdHistorico() {
        return this.cdHistorico;
    }
    
    public void setCdHistorico(BigDecimal cdHistorico) {
        this.cdHistorico = cdHistorico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="AGE_PROG_NU_ORDEM", referencedColumnName="NU_ORDEM", nullable=false), 
        @JoinColumn(name="AGE_PROG_PROG_CD_PROGRAMA", referencedColumnName="PROG_CD_PROGRAMA", nullable=false), 
        @JoinColumn(name="AGE_PROG_AGE_CD_AGENDAMENTO", referencedColumnName="AGE_CD_AGENDAMENTO", nullable=false) } )
    public AgeProgAgendamento getAgeProgAgendamento() {
        return this.ageProgAgendamento;
    }
    
    public void setAgeProgAgendamento(AgeProgAgendamento ageProgAgendamento) {
        this.ageProgAgendamento = ageProgAgendamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_INICIO_EXEC", nullable=false, length=7)
    public Date getDtInicioExec() {
        return this.dtInicioExec;
    }
    
    public void setDtInicioExec(Date dtInicioExec) {
        this.dtInicioExec = dtInicioExec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FIM_EXEC", nullable=false, length=7)
    public Date getDtFimExec() {
        return this.dtFimExec;
    }
    
    public void setDtFimExec(Date dtFimExec) {
        this.dtFimExec = dtFimExec;
    }

    
    @Column(name="FL_STATUS", length=2)
    public String getFlStatus() {
        return this.flStatus;
    }
    
    public void setFlStatus(String flStatus) {
        this.flStatus = flStatus;
    }

    
    @Column(name="DS_SAIDA", nullable=false, length=0)
    public String getDsSaida() {
        return this.dsSaida;
    }
    
    public void setDsSaida(String dsSaida) {
        this.dsSaida = dsSaida;
    }

    
    @Column(name="DS_URL", length=2000)
    public String getDsUrl() {
        return this.dsUrl;
    }
    
    public void setDsUrl(String dsUrl) {
        this.dsUrl = dsUrl;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="DS_COMANDO", length=4000)
    public String getDsComando() {
        return this.dsComando;
    }
    
    public void setDsComando(String dsComando) {
        this.dsComando = dsComando;
    }

    
    @Column(name="DS_ARQUIVO")
    public Clob getDsArquivo() {
        return this.dsArquivo;
    }
    
    public void setDsArquivo(Clob dsArquivo) {
        this.dsArquivo = dsArquivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageHitoricoProgAgend")
    public Set getAgeDetalhesExecucaos() {
        return this.ageDetalhesExecucaos;
    }
    
    public void setAgeDetalhesExecucaos(Set ageDetalhesExecucaos) {
        this.ageDetalhesExecucaos = ageDetalhesExecucaos;
    }




}


