package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name="AGENDA"
    ,schema="DESENV"
)
public class Agenda  implements java.io.Serializable {


     private BigDecimal id;
     private Consultorio consultorio;
     private Convenio convenio;
     private Paciente paciente;
     private Profissional profissional;
     private TipoAgenda tipoAgenda;
     private Empresa empresa;
     private Date dtInicio;
     private Date dtTermino;
     private String nomePaciente;
     private String telefoneResidencialPaciente;
     private String telefoneCelularPaciente;
     private String telefoneComercialPaciente;
     private String emailPaciente;
     private String procedimento;
     private String flConfirmado;
     private String flFalta;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private String flEncaixe;
     private char flPacienteNovo;

    public Agenda() {
    }

	
    public Agenda(BigDecimal id, Consultorio consultorio, Convenio convenio, Profissional profissional, TipoAgenda tipoAgenda, Empresa empresa, Date dtInicio, Date dtTermino, String flConfirmado, String flFalta, String flEncaixe, char flPacienteNovo) {
        this.id = id;
        this.consultorio = consultorio;
        this.convenio = convenio;
        this.profissional = profissional;
        this.tipoAgenda = tipoAgenda;
        this.empresa = empresa;
        this.dtInicio = dtInicio;
        this.dtTermino = dtTermino;
        this.flConfirmado = flConfirmado;
        this.flFalta = flFalta;
        this.flEncaixe = flEncaixe;
        this.flPacienteNovo = flPacienteNovo;
    }
    public Agenda(BigDecimal id, Consultorio consultorio, Convenio convenio, Paciente paciente, Profissional profissional, TipoAgenda tipoAgenda, Empresa empresa, Date dtInicio, Date dtTermino, String nomePaciente, String telefoneResidencialPaciente, String telefoneCelularPaciente, String telefoneComercialPaciente, String emailPaciente, String procedimento, String flConfirmado, String flFalta, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, String flEncaixe, char flPacienteNovo) {
       this.id = id;
       this.consultorio = consultorio;
       this.convenio = convenio;
       this.paciente = paciente;
       this.profissional = profissional;
       this.tipoAgenda = tipoAgenda;
       this.empresa = empresa;
       this.dtInicio = dtInicio;
       this.dtTermino = dtTermino;
       this.nomePaciente = nomePaciente;
       this.telefoneResidencialPaciente = telefoneResidencialPaciente;
       this.telefoneCelularPaciente = telefoneCelularPaciente;
       this.telefoneComercialPaciente = telefoneComercialPaciente;
       this.emailPaciente = emailPaciente;
       this.procedimento = procedimento;
       this.flConfirmado = flConfirmado;
       this.flFalta = flFalta;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flEncaixe = flEncaixe;
       this.flPacienteNovo = flPacienteNovo;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONS_UNI_ID", referencedColumnName="UNI_ID", nullable=false), 
        @JoinColumn(name="CONS_ID", referencedColumnName="ID", nullable=false) } )
    public Consultorio getConsultorio() {
        return this.consultorio;
    }
    
    public void setConsultorio(Consultorio consultorio) {
        this.consultorio = consultorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_ID", referencedColumnName="ID"), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false) } )
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAC_ID")
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROF_ID", nullable=false)
    public Profissional getProfissional() {
        return this.profissional;
    }
    
    public void setProfissional(Profissional profissional) {
        this.profissional = profissional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="TIAGE_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false, insertable=false, updatable=false) } )
    public TipoAgenda getTipoAgenda() {
        return this.tipoAgenda;
    }
    
    public void setTipoAgenda(TipoAgenda tipoAgenda) {
        this.tipoAgenda = tipoAgenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_INICIO", nullable=false, length=7)
    public Date getDtInicio() {
        return this.dtInicio;
    }
    
    public void setDtInicio(Date dtInicio) {
        this.dtInicio = dtInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_TERMINO", nullable=false, length=7)
    public Date getDtTermino() {
        return this.dtTermino;
    }
    
    public void setDtTermino(Date dtTermino) {
        this.dtTermino = dtTermino;
    }

    
    @Column(name="NOME_PACIENTE", length=100)
    public String getNomePaciente() {
        return this.nomePaciente;
    }
    
    public void setNomePaciente(String nomePaciente) {
        this.nomePaciente = nomePaciente;
    }

    
    @Column(name="TELEFONE_RESIDENCIAL_PACIENTE", length=30)
    public String getTelefoneResidencialPaciente() {
        return this.telefoneResidencialPaciente;
    }
    
    public void setTelefoneResidencialPaciente(String telefoneResidencialPaciente) {
        this.telefoneResidencialPaciente = telefoneResidencialPaciente;
    }

    
    @Column(name="TELEFONE_CELULAR_PACIENTE", length=30)
    public String getTelefoneCelularPaciente() {
        return this.telefoneCelularPaciente;
    }
    
    public void setTelefoneCelularPaciente(String telefoneCelularPaciente) {
        this.telefoneCelularPaciente = telefoneCelularPaciente;
    }

    
    @Column(name="TELEFONE_COMERCIAL_PACIENTE", length=30)
    public String getTelefoneComercialPaciente() {
        return this.telefoneComercialPaciente;
    }
    
    public void setTelefoneComercialPaciente(String telefoneComercialPaciente) {
        this.telefoneComercialPaciente = telefoneComercialPaciente;
    }

    
    @Column(name="EMAIL_PACIENTE", length=200)
    public String getEmailPaciente() {
        return this.emailPaciente;
    }
    
    public void setEmailPaciente(String emailPaciente) {
        this.emailPaciente = emailPaciente;
    }

    
    @Column(name="PROCEDIMENTO", length=100)
    public String getProcedimento() {
        return this.procedimento;
    }
    
    public void setProcedimento(String procedimento) {
        this.procedimento = procedimento;
    }

    
    @Column(name="FL_CONFIRMADO", nullable=false, length=1)
    public String getFlConfirmado() {
        return this.flConfirmado;
    }
    
    public void setFlConfirmado(String flConfirmado) {
        this.flConfirmado = flConfirmado;
    }

    
    @Column(name="FL_FALTA", nullable=false, length=1)
    public String getFlFalta() {
        return this.flFalta;
    }
    
    public void setFlFalta(String flFalta) {
        this.flFalta = flFalta;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_ENCAIXE", nullable=false, length=1)
    public String getFlEncaixe() {
        return this.flEncaixe;
    }
    
    public void setFlEncaixe(String flEncaixe) {
        this.flEncaixe = flEncaixe;
    }

    
    @Column(name="FL_PACIENTE_NOVO", nullable=false, length=1)
    public char getFlPacienteNovo() {
        return this.flPacienteNovo;
    }
    
    public void setFlPacienteNovo(char flPacienteNovo) {
        this.flPacienteNovo = flPacienteNovo;
    }




}


