package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AgePrograma generated by hbm2java
 */
@Entity
@Table(name="AGE_PROGRAMA"
    ,schema="DESENV"
    , uniqueConstraints = @UniqueConstraint(columnNames="NM_ABREVIADO") 
)
public class AgePrograma  implements java.io.Serializable {


     private BigDecimal cdPrograma;
     private String nmAbreviado;
     private String dsPrograma;
     private String nmExecutavel;
     private String flMetodoExec;
     private String flFormatoSaida;
     private String flSalvarSaida;
     private String flAtivo;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set ageParametroses = new HashSet(0);
     private Set usuGrupoProgs = new HashSet(0);
     private Set ageProgAgendamentos = new HashSet(0);

    public AgePrograma() {
    }

	
    public AgePrograma(BigDecimal cdPrograma, String nmAbreviado, String nmExecutavel, String flMetodoExec, String flFormatoSaida, String flSalvarSaida, String flAtivo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdPrograma = cdPrograma;
        this.nmAbreviado = nmAbreviado;
        this.nmExecutavel = nmExecutavel;
        this.flMetodoExec = flMetodoExec;
        this.flFormatoSaida = flFormatoSaida;
        this.flSalvarSaida = flSalvarSaida;
        this.flAtivo = flAtivo;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public AgePrograma(BigDecimal cdPrograma, String nmAbreviado, String dsPrograma, String nmExecutavel, String flMetodoExec, String flFormatoSaida, String flSalvarSaida, String flAtivo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set ageParametroses, Set usuGrupoProgs, Set ageProgAgendamentos) {
       this.cdPrograma = cdPrograma;
       this.nmAbreviado = nmAbreviado;
       this.dsPrograma = dsPrograma;
       this.nmExecutavel = nmExecutavel;
       this.flMetodoExec = flMetodoExec;
       this.flFormatoSaida = flFormatoSaida;
       this.flSalvarSaida = flSalvarSaida;
       this.flAtivo = flAtivo;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.ageParametroses = ageParametroses;
       this.usuGrupoProgs = usuGrupoProgs;
       this.ageProgAgendamentos = ageProgAgendamentos;
    }
   
     @Id 

    
    @Column(name="CD_PROGRAMA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdPrograma() {
        return this.cdPrograma;
    }
    
    public void setCdPrograma(BigDecimal cdPrograma) {
        this.cdPrograma = cdPrograma;
    }

    
    @Column(name="NM_ABREVIADO", unique=true, nullable=false, length=50)
    public String getNmAbreviado() {
        return this.nmAbreviado;
    }
    
    public void setNmAbreviado(String nmAbreviado) {
        this.nmAbreviado = nmAbreviado;
    }

    
    @Column(name="DS_PROGRAMA", length=500)
    public String getDsPrograma() {
        return this.dsPrograma;
    }
    
    public void setDsPrograma(String dsPrograma) {
        this.dsPrograma = dsPrograma;
    }

    
    @Column(name="NM_EXECUTAVEL", nullable=false, length=500)
    public String getNmExecutavel() {
        return this.nmExecutavel;
    }
    
    public void setNmExecutavel(String nmExecutavel) {
        this.nmExecutavel = nmExecutavel;
    }

    
    @Column(name="FL_METODO_EXEC", nullable=false, length=2)
    public String getFlMetodoExec() {
        return this.flMetodoExec;
    }
    
    public void setFlMetodoExec(String flMetodoExec) {
        this.flMetodoExec = flMetodoExec;
    }

    
    @Column(name="FL_FORMATO_SAIDA", nullable=false, length=1)
    public String getFlFormatoSaida() {
        return this.flFormatoSaida;
    }
    
    public void setFlFormatoSaida(String flFormatoSaida) {
        this.flFormatoSaida = flFormatoSaida;
    }

    
    @Column(name="FL_SALVAR_SAIDA", nullable=false, length=1)
    public String getFlSalvarSaida() {
        return this.flSalvarSaida;
    }
    
    public void setFlSalvarSaida(String flSalvarSaida) {
        this.flSalvarSaida = flSalvarSaida;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agePrograma")
    public Set getAgeParametroses() {
        return this.ageParametroses;
    }
    
    public void setAgeParametroses(Set ageParametroses) {
        this.ageParametroses = ageParametroses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agePrograma")
    public Set getUsuGrupoProgs() {
        return this.usuGrupoProgs;
    }
    
    public void setUsuGrupoProgs(Set usuGrupoProgs) {
        this.usuGrupoProgs = usuGrupoProgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agePrograma")
    public Set getAgeProgAgendamentos() {
        return this.ageProgAgendamentos;
    }
    
    public void setAgeProgAgendamentos(Set ageProgAgendamentos) {
        this.ageProgAgendamentos = ageProgAgendamentos;
    }




}


