package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgeParametrosAgendamentoId generated by hbm2java
 */
@Embeddable
public class AgeParametrosAgendamentoId  implements java.io.Serializable {


     private String parNmParametro;
     private BigDecimal parProgCdPrograma;
     private String dsValorParametro;
     private BigDecimal ageProgNuOrdem;
     private BigDecimal ageProgProgCdPrograma;
     private BigDecimal ageProgAgeCdAgendamento;

    public AgeParametrosAgendamentoId() {
    }

    public AgeParametrosAgendamentoId(String parNmParametro, BigDecimal parProgCdPrograma, String dsValorParametro, BigDecimal ageProgNuOrdem, BigDecimal ageProgProgCdPrograma, BigDecimal ageProgAgeCdAgendamento) {
       this.parNmParametro = parNmParametro;
       this.parProgCdPrograma = parProgCdPrograma;
       this.dsValorParametro = dsValorParametro;
       this.ageProgNuOrdem = ageProgNuOrdem;
       this.ageProgProgCdPrograma = ageProgProgCdPrograma;
       this.ageProgAgeCdAgendamento = ageProgAgeCdAgendamento;
    }
   


    @Column(name="PAR_NM_PARAMETRO", nullable=false, length=100)
    public String getParNmParametro() {
        return this.parNmParametro;
    }
    
    public void setParNmParametro(String parNmParametro) {
        this.parNmParametro = parNmParametro;
    }


    @Column(name="PAR_PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0)
    public BigDecimal getParProgCdPrograma() {
        return this.parProgCdPrograma;
    }
    
    public void setParProgCdPrograma(BigDecimal parProgCdPrograma) {
        this.parProgCdPrograma = parProgCdPrograma;
    }


    @Column(name="DS_VALOR_PARAMETRO", nullable=false, length=2000)
    public String getDsValorParametro() {
        return this.dsValorParametro;
    }
    
    public void setDsValorParametro(String dsValorParametro) {
        this.dsValorParametro = dsValorParametro;
    }


    @Column(name="AGE_PROG_NU_ORDEM", nullable=false, precision=22, scale=0)
    public BigDecimal getAgeProgNuOrdem() {
        return this.ageProgNuOrdem;
    }
    
    public void setAgeProgNuOrdem(BigDecimal ageProgNuOrdem) {
        this.ageProgNuOrdem = ageProgNuOrdem;
    }


    @Column(name="AGE_PROG_PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0)
    public BigDecimal getAgeProgProgCdPrograma() {
        return this.ageProgProgCdPrograma;
    }
    
    public void setAgeProgProgCdPrograma(BigDecimal ageProgProgCdPrograma) {
        this.ageProgProgCdPrograma = ageProgProgCdPrograma;
    }


    @Column(name="AGE_PROG_AGE_CD_AGENDAMENTO", nullable=false, precision=22, scale=0)
    public BigDecimal getAgeProgAgeCdAgendamento() {
        return this.ageProgAgeCdAgendamento;
    }
    
    public void setAgeProgAgeCdAgendamento(BigDecimal ageProgAgeCdAgendamento) {
        this.ageProgAgeCdAgendamento = ageProgAgeCdAgendamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgeParametrosAgendamentoId) ) return false;
		 AgeParametrosAgendamentoId castOther = ( AgeParametrosAgendamentoId ) other; 
         
		 return ( (this.getParNmParametro()==castOther.getParNmParametro()) || ( this.getParNmParametro()!=null && castOther.getParNmParametro()!=null && this.getParNmParametro().equals(castOther.getParNmParametro()) ) )
 && ( (this.getParProgCdPrograma()==castOther.getParProgCdPrograma()) || ( this.getParProgCdPrograma()!=null && castOther.getParProgCdPrograma()!=null && this.getParProgCdPrograma().equals(castOther.getParProgCdPrograma()) ) )
 && ( (this.getDsValorParametro()==castOther.getDsValorParametro()) || ( this.getDsValorParametro()!=null && castOther.getDsValorParametro()!=null && this.getDsValorParametro().equals(castOther.getDsValorParametro()) ) )
 && ( (this.getAgeProgNuOrdem()==castOther.getAgeProgNuOrdem()) || ( this.getAgeProgNuOrdem()!=null && castOther.getAgeProgNuOrdem()!=null && this.getAgeProgNuOrdem().equals(castOther.getAgeProgNuOrdem()) ) )
 && ( (this.getAgeProgProgCdPrograma()==castOther.getAgeProgProgCdPrograma()) || ( this.getAgeProgProgCdPrograma()!=null && castOther.getAgeProgProgCdPrograma()!=null && this.getAgeProgProgCdPrograma().equals(castOther.getAgeProgProgCdPrograma()) ) )
 && ( (this.getAgeProgAgeCdAgendamento()==castOther.getAgeProgAgeCdAgendamento()) || ( this.getAgeProgAgeCdAgendamento()!=null && castOther.getAgeProgAgeCdAgendamento()!=null && this.getAgeProgAgeCdAgendamento().equals(castOther.getAgeProgAgeCdAgendamento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getParNmParametro() == null ? 0 : this.getParNmParametro().hashCode() );
         result = 37 * result + ( getParProgCdPrograma() == null ? 0 : this.getParProgCdPrograma().hashCode() );
         result = 37 * result + ( getDsValorParametro() == null ? 0 : this.getDsValorParametro().hashCode() );
         result = 37 * result + ( getAgeProgNuOrdem() == null ? 0 : this.getAgeProgNuOrdem().hashCode() );
         result = 37 * result + ( getAgeProgProgCdPrograma() == null ? 0 : this.getAgeProgProgCdPrograma().hashCode() );
         result = 37 * result + ( getAgeProgAgeCdAgendamento() == null ? 0 : this.getAgeProgAgeCdAgendamento().hashCode() );
         return result;
   }   


}


