package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeParametrosAgendamento generated by hbm2java
 */
@Entity
@Table(name="AGE_PARAMETROS_AGENDAMENTO"
    ,schema="DESENV"
)
public class AgeParametrosAgendamento  implements java.io.Serializable {


     private AgeParametrosAgendamentoId id;
     private AgeParametros ageParametros;
     private AgeProgAgendamento ageProgAgendamento;
     private Empresa empresa;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;

    public AgeParametrosAgendamento() {
    }

    public AgeParametrosAgendamento(AgeParametrosAgendamentoId id, AgeParametros ageParametros, AgeProgAgendamento ageProgAgendamento, Empresa empresa, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
       this.id = id;
       this.ageParametros = ageParametros;
       this.ageProgAgendamento = ageProgAgendamento;
       this.empresa = empresa;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="parNmParametro", column=@Column(name="PAR_NM_PARAMETRO", nullable=false, length=100) ), 
        @AttributeOverride(name="parProgCdPrograma", column=@Column(name="PAR_PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="dsValorParametro", column=@Column(name="DS_VALOR_PARAMETRO", nullable=false, length=2000) ), 
        @AttributeOverride(name="ageProgNuOrdem", column=@Column(name="AGE_PROG_NU_ORDEM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="ageProgProgCdPrograma", column=@Column(name="AGE_PROG_PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="ageProgAgeCdAgendamento", column=@Column(name="AGE_PROG_AGE_CD_AGENDAMENTO", nullable=false, precision=22, scale=0) ) } )
    public AgeParametrosAgendamentoId getId() {
        return this.id;
    }
    
    public void setId(AgeParametrosAgendamentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="PAR_NM_PARAMETRO", referencedColumnName="NM_PARAMETRO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PAR_PROG_CD_PROGRAMA", referencedColumnName="PROG_CD_PROGRAMA", nullable=false, insertable=false, updatable=false) } )
    public AgeParametros getAgeParametros() {
        return this.ageParametros;
    }
    
    public void setAgeParametros(AgeParametros ageParametros) {
        this.ageParametros = ageParametros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="AGE_PROG_NU_ORDEM", referencedColumnName="NU_ORDEM", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="AGE_PROG_PROG_CD_PROGRAMA", referencedColumnName="PROG_CD_PROGRAMA", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="AGE_PROG_AGE_CD_AGENDAMENTO", referencedColumnName="AGE_CD_AGENDAMENTO", nullable=false, insertable=false, updatable=false) } )
    public AgeProgAgendamento getAgeProgAgendamento() {
        return this.ageProgAgendamento;
    }
    
    public void setAgeProgAgendamento(AgeProgAgendamento ageProgAgendamento) {
        this.ageProgAgendamento = ageProgAgendamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


