package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeProgAgendamento generated by hbm2java
 */
@Entity
@Table(name="AGE_PROG_AGENDAMENTO"
    ,schema="DESENV"
)
public class AgeProgAgendamento  implements java.io.Serializable {


     private AgeProgAgendamentoId id;
     private AgeAgendamento ageAgendamento;
     private AgePrograma agePrograma;
     private Empresa empresa;
     private BigDecimal cdAlteradoPor;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set ageHitoricoProgAgends = new HashSet(0);
     private Set ageParametrosAgendamentos = new HashSet(0);

    public AgeProgAgendamento() {
    }

	
    public AgeProgAgendamento(AgeProgAgendamentoId id, AgeAgendamento ageAgendamento, AgePrograma agePrograma, Empresa empresa, BigDecimal cdAlteradoPor, BigDecimal cdCriadoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.id = id;
        this.ageAgendamento = ageAgendamento;
        this.agePrograma = agePrograma;
        this.empresa = empresa;
        this.cdAlteradoPor = cdAlteradoPor;
        this.cdCriadoPor = cdCriadoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public AgeProgAgendamento(AgeProgAgendamentoId id, AgeAgendamento ageAgendamento, AgePrograma agePrograma, Empresa empresa, BigDecimal cdAlteradoPor, BigDecimal cdCriadoPor, Date dtCriacao, Date dtUltimaAlteracao, Set ageHitoricoProgAgends, Set ageParametrosAgendamentos) {
       this.id = id;
       this.ageAgendamento = ageAgendamento;
       this.agePrograma = agePrograma;
       this.empresa = empresa;
       this.cdAlteradoPor = cdAlteradoPor;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.ageHitoricoProgAgends = ageHitoricoProgAgends;
       this.ageParametrosAgendamentos = ageParametrosAgendamentos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nuOrdem", column=@Column(name="NU_ORDEM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="progCdPrograma", column=@Column(name="PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="ageCdAgendamento", column=@Column(name="AGE_CD_AGENDAMENTO", nullable=false, precision=22, scale=0) ) } )
    public AgeProgAgendamentoId getId() {
        return this.id;
    }
    
    public void setId(AgeProgAgendamentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AGE_CD_AGENDAMENTO", nullable=false, insertable=false, updatable=false)
    public AgeAgendamento getAgeAgendamento() {
        return this.ageAgendamento;
    }
    
    public void setAgeAgendamento(AgeAgendamento ageAgendamento) {
        this.ageAgendamento = ageAgendamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROG_CD_PROGRAMA", nullable=false, insertable=false, updatable=false)
    public AgePrograma getAgePrograma() {
        return this.agePrograma;
    }
    
    public void setAgePrograma(AgePrograma agePrograma) {
        this.agePrograma = agePrograma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageProgAgendamento")
    public Set getAgeHitoricoProgAgends() {
        return this.ageHitoricoProgAgends;
    }
    
    public void setAgeHitoricoProgAgends(Set ageHitoricoProgAgends) {
        this.ageHitoricoProgAgends = ageHitoricoProgAgends;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageProgAgendamento")
    public Set getAgeParametrosAgendamentos() {
        return this.ageParametrosAgendamentos;
    }
    
    public void setAgeParametrosAgendamentos(Set ageParametrosAgendamentos) {
        this.ageParametrosAgendamentos = ageParametrosAgendamentos;
    }




}


