package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeParametros generated by hbm2java
 */
@Entity
@Table(name="AGE_PARAMETROS"
    ,schema="DESENV"
)
public class AgeParametros  implements java.io.Serializable {


     private AgeParametrosId id;
     private AgeValidacao ageValidacao;
     private AgePrograma agePrograma;
     private String dsParametro;
     private String flAtivo;
     private String flTipoPadrao;
     private String dsValorPadrao;
     private String flObrigatorio;
     private String flMult;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private byte nuOrdem;
     private Set ageParametrosAgendamentos = new HashSet(0);

    public AgeParametros() {
    }

	
    public AgeParametros(AgeParametrosId id, AgeValidacao ageValidacao, AgePrograma agePrograma, String flAtivo, String flTipoPadrao, String flObrigatorio, String flMult, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, byte nuOrdem) {
        this.id = id;
        this.ageValidacao = ageValidacao;
        this.agePrograma = agePrograma;
        this.flAtivo = flAtivo;
        this.flTipoPadrao = flTipoPadrao;
        this.flObrigatorio = flObrigatorio;
        this.flMult = flMult;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
        this.nuOrdem = nuOrdem;
    }
    public AgeParametros(AgeParametrosId id, AgeValidacao ageValidacao, AgePrograma agePrograma, String dsParametro, String flAtivo, String flTipoPadrao, String dsValorPadrao, String flObrigatorio, String flMult, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, byte nuOrdem, Set ageParametrosAgendamentos) {
       this.id = id;
       this.ageValidacao = ageValidacao;
       this.agePrograma = agePrograma;
       this.dsParametro = dsParametro;
       this.flAtivo = flAtivo;
       this.flTipoPadrao = flTipoPadrao;
       this.dsValorPadrao = dsValorPadrao;
       this.flObrigatorio = flObrigatorio;
       this.flMult = flMult;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.nuOrdem = nuOrdem;
       this.ageParametrosAgendamentos = ageParametrosAgendamentos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nmParametro", column=@Column(name="NM_PARAMETRO", nullable=false, length=100) ), 
        @AttributeOverride(name="progCdPrograma", column=@Column(name="PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0) ) } )
    public AgeParametrosId getId() {
        return this.id;
    }
    
    public void setId(AgeParametrosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VALIDA_CD_VALIDACAO", nullable=false)
    public AgeValidacao getAgeValidacao() {
        return this.ageValidacao;
    }
    
    public void setAgeValidacao(AgeValidacao ageValidacao) {
        this.ageValidacao = ageValidacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROG_CD_PROGRAMA", nullable=false, insertable=false, updatable=false)
    public AgePrograma getAgePrograma() {
        return this.agePrograma;
    }
    
    public void setAgePrograma(AgePrograma agePrograma) {
        this.agePrograma = agePrograma;
    }

    
    @Column(name="DS_PARAMETRO", length=500)
    public String getDsParametro() {
        return this.dsParametro;
    }
    
    public void setDsParametro(String dsParametro) {
        this.dsParametro = dsParametro;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="FL_TIPO_PADRAO", nullable=false, length=1)
    public String getFlTipoPadrao() {
        return this.flTipoPadrao;
    }
    
    public void setFlTipoPadrao(String flTipoPadrao) {
        this.flTipoPadrao = flTipoPadrao;
    }

    
    @Column(name="DS_VALOR_PADRAO", length=2000)
    public String getDsValorPadrao() {
        return this.dsValorPadrao;
    }
    
    public void setDsValorPadrao(String dsValorPadrao) {
        this.dsValorPadrao = dsValorPadrao;
    }

    
    @Column(name="FL_OBRIGATORIO", nullable=false, length=1)
    public String getFlObrigatorio() {
        return this.flObrigatorio;
    }
    
    public void setFlObrigatorio(String flObrigatorio) {
        this.flObrigatorio = flObrigatorio;
    }

    
    @Column(name="FL_MULT", nullable=false, length=1)
    public String getFlMult() {
        return this.flMult;
    }
    
    public void setFlMult(String flMult) {
        this.flMult = flMult;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="NU_ORDEM", nullable=false, precision=2, scale=0)
    public byte getNuOrdem() {
        return this.nuOrdem;
    }
    
    public void setNuOrdem(byte nuOrdem) {
        this.nuOrdem = nuOrdem;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageParametros")
    public Set getAgeParametrosAgendamentos() {
        return this.ageParametrosAgendamentos;
    }
    
    public void setAgeParametrosAgendamentos(Set ageParametrosAgendamentos) {
        this.ageParametrosAgendamentos = ageParametrosAgendamentos;
    }




}


