package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgeValidacao generated by hbm2java
 */
@Entity
@Table(name="AGE_VALIDACAO"
    ,schema="DESENV"
)
public class AgeValidacao  implements java.io.Serializable {


     private BigDecimal cdValidacao;
     private String nmValidacao;
     private String dsValidacao;
     private String flTipoCampo;
     private BigDecimal nuTamanho;
     private String dsValorMax;
     private String dsValorMin;
     private String flTipoValidacao;
     private String nmTabela;
     private String nmCampoIdLov;
     private String nmCampoNmLov;
     private String nmCampoVlLov;
     private String dsWhereOrder;
     private String dsColunasAdicionais;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private String dsTipoCampo;
     private String nmCampoRec;
     private String flDistinct;
     private Set ageParametroses = new HashSet(0);
     private Set ageConjuntoValidacaos = new HashSet(0);

    public AgeValidacao() {
    }

	
    public AgeValidacao(BigDecimal cdValidacao, String nmValidacao, String flTipoCampo, String flTipoValidacao, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdValidacao = cdValidacao;
        this.nmValidacao = nmValidacao;
        this.flTipoCampo = flTipoCampo;
        this.flTipoValidacao = flTipoValidacao;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public AgeValidacao(BigDecimal cdValidacao, String nmValidacao, String dsValidacao, String flTipoCampo, BigDecimal nuTamanho, String dsValorMax, String dsValorMin, String flTipoValidacao, String nmTabela, String nmCampoIdLov, String nmCampoNmLov, String nmCampoVlLov, String dsWhereOrder, String dsColunasAdicionais, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, String dsTipoCampo, String nmCampoRec, String flDistinct, Set ageParametroses, Set ageConjuntoValidacaos) {
       this.cdValidacao = cdValidacao;
       this.nmValidacao = nmValidacao;
       this.dsValidacao = dsValidacao;
       this.flTipoCampo = flTipoCampo;
       this.nuTamanho = nuTamanho;
       this.dsValorMax = dsValorMax;
       this.dsValorMin = dsValorMin;
       this.flTipoValidacao = flTipoValidacao;
       this.nmTabela = nmTabela;
       this.nmCampoIdLov = nmCampoIdLov;
       this.nmCampoNmLov = nmCampoNmLov;
       this.nmCampoVlLov = nmCampoVlLov;
       this.dsWhereOrder = dsWhereOrder;
       this.dsColunasAdicionais = dsColunasAdicionais;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.dsTipoCampo = dsTipoCampo;
       this.nmCampoRec = nmCampoRec;
       this.flDistinct = flDistinct;
       this.ageParametroses = ageParametroses;
       this.ageConjuntoValidacaos = ageConjuntoValidacaos;
    }
   
     @Id 

    
    @Column(name="CD_VALIDACAO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdValidacao() {
        return this.cdValidacao;
    }
    
    public void setCdValidacao(BigDecimal cdValidacao) {
        this.cdValidacao = cdValidacao;
    }

    
    @Column(name="NM_VALIDACAO", nullable=false, length=200)
    public String getNmValidacao() {
        return this.nmValidacao;
    }
    
    public void setNmValidacao(String nmValidacao) {
        this.nmValidacao = nmValidacao;
    }

    
    @Column(name="DS_VALIDACAO", length=500)
    public String getDsValidacao() {
        return this.dsValidacao;
    }
    
    public void setDsValidacao(String dsValidacao) {
        this.dsValidacao = dsValidacao;
    }

    
    @Column(name="FL_TIPO_CAMPO", nullable=false, length=1)
    public String getFlTipoCampo() {
        return this.flTipoCampo;
    }
    
    public void setFlTipoCampo(String flTipoCampo) {
        this.flTipoCampo = flTipoCampo;
    }

    
    @Column(name="NU_TAMANHO", precision=22, scale=0)
    public BigDecimal getNuTamanho() {
        return this.nuTamanho;
    }
    
    public void setNuTamanho(BigDecimal nuTamanho) {
        this.nuTamanho = nuTamanho;
    }

    
    @Column(name="DS_VALOR_MAX", length=500)
    public String getDsValorMax() {
        return this.dsValorMax;
    }
    
    public void setDsValorMax(String dsValorMax) {
        this.dsValorMax = dsValorMax;
    }

    
    @Column(name="DS_VALOR_MIN", length=500)
    public String getDsValorMin() {
        return this.dsValorMin;
    }
    
    public void setDsValorMin(String dsValorMin) {
        this.dsValorMin = dsValorMin;
    }

    
    @Column(name="FL_TIPO_VALIDACAO", nullable=false, length=1)
    public String getFlTipoValidacao() {
        return this.flTipoValidacao;
    }
    
    public void setFlTipoValidacao(String flTipoValidacao) {
        this.flTipoValidacao = flTipoValidacao;
    }

    
    @Column(name="NM_TABELA", length=500)
    public String getNmTabela() {
        return this.nmTabela;
    }
    
    public void setNmTabela(String nmTabela) {
        this.nmTabela = nmTabela;
    }

    
    @Column(name="NM_CAMPO_ID_LOV", length=100)
    public String getNmCampoIdLov() {
        return this.nmCampoIdLov;
    }
    
    public void setNmCampoIdLov(String nmCampoIdLov) {
        this.nmCampoIdLov = nmCampoIdLov;
    }

    
    @Column(name="NM_CAMPO_NM_LOV", length=100)
    public String getNmCampoNmLov() {
        return this.nmCampoNmLov;
    }
    
    public void setNmCampoNmLov(String nmCampoNmLov) {
        this.nmCampoNmLov = nmCampoNmLov;
    }

    
    @Column(name="NM_CAMPO_VL_LOV", length=100)
    public String getNmCampoVlLov() {
        return this.nmCampoVlLov;
    }
    
    public void setNmCampoVlLov(String nmCampoVlLov) {
        this.nmCampoVlLov = nmCampoVlLov;
    }

    
    @Column(name="DS_WHERE_ORDER", length=2000)
    public String getDsWhereOrder() {
        return this.dsWhereOrder;
    }
    
    public void setDsWhereOrder(String dsWhereOrder) {
        this.dsWhereOrder = dsWhereOrder;
    }

    
    @Column(name="DS_COLUNAS_ADICIONAIS", length=2000)
    public String getDsColunasAdicionais() {
        return this.dsColunasAdicionais;
    }
    
    public void setDsColunasAdicionais(String dsColunasAdicionais) {
        this.dsColunasAdicionais = dsColunasAdicionais;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="DS_TIPO_CAMPO", length=200)
    public String getDsTipoCampo() {
        return this.dsTipoCampo;
    }
    
    public void setDsTipoCampo(String dsTipoCampo) {
        this.dsTipoCampo = dsTipoCampo;
    }

    
    @Column(name="NM_CAMPO_REC", length=30)
    public String getNmCampoRec() {
        return this.nmCampoRec;
    }
    
    public void setNmCampoRec(String nmCampoRec) {
        this.nmCampoRec = nmCampoRec;
    }

    
    @Column(name="FL_DISTINCT", length=1)
    public String getFlDistinct() {
        return this.flDistinct;
    }
    
    public void setFlDistinct(String flDistinct) {
        this.flDistinct = flDistinct;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageValidacao")
    public Set getAgeParametroses() {
        return this.ageParametroses;
    }
    
    public void setAgeParametroses(Set ageParametroses) {
        this.ageParametroses = ageParametroses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ageValidacao")
    public Set getAgeConjuntoValidacaos() {
        return this.ageConjuntoValidacaos;
    }
    
    public void setAgeConjuntoValidacaos(Set ageConjuntoValidacaos) {
        this.ageConjuntoValidacaos = ageConjuntoValidacaos;
    }




}


