package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArquivoLiquidacao generated by hbm2java
 */
@Entity
@Table(name="ARQUIVO_LIQUIDACAO"
    ,schema="DESENV"
)
public class ArquivoLiquidacao  implements java.io.Serializable {


     private BigDecimal id;
     private ConvenioBancario convenioBancario;
     private Empresa empresa;
     private String nome;
     private BigDecimal sequencia;
     private Date dataLeitura;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set linhasArquivoLiquidacaos = new HashSet(0);

    public ArquivoLiquidacao() {
    }

	
    public ArquivoLiquidacao(BigDecimal id, ConvenioBancario convenioBancario, Empresa empresa, String nome, BigDecimal sequencia, Date dataLeitura) {
        this.id = id;
        this.convenioBancario = convenioBancario;
        this.empresa = empresa;
        this.nome = nome;
        this.sequencia = sequencia;
        this.dataLeitura = dataLeitura;
    }
    public ArquivoLiquidacao(BigDecimal id, ConvenioBancario convenioBancario, Empresa empresa, String nome, BigDecimal sequencia, Date dataLeitura, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set linhasArquivoLiquidacaos) {
       this.id = id;
       this.convenioBancario = convenioBancario;
       this.empresa = empresa;
       this.nome = nome;
       this.sequencia = sequencia;
       this.dataLeitura = dataLeitura;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.linhasArquivoLiquidacaos = linhasArquivoLiquidacaos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_BANCO", referencedColumnName="BANCO", nullable=false), 
        @JoinColumn(name="CONV_AGENCIA", referencedColumnName="AGENCIA", nullable=false), 
        @JoinColumn(name="CONV_CEDENTE", referencedColumnName="CEDENTE", nullable=false), 
        @JoinColumn(name="CONV_CARTEIRA", referencedColumnName="CARTEIRA", nullable=false), 
        @JoinColumn(name="CONV_CONVENIO", referencedColumnName="CONVENIO", nullable=false) } )
    public ConvenioBancario getConvenioBancario() {
        return this.convenioBancario;
    }
    
    public void setConvenioBancario(ConvenioBancario convenioBancario) {
        this.convenioBancario = convenioBancario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="SEQUENCIA", nullable=false, precision=22, scale=0)
    public BigDecimal getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(BigDecimal sequencia) {
        this.sequencia = sequencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_LEITURA", nullable=false, length=7)
    public Date getDataLeitura() {
        return this.dataLeitura;
    }
    
    public void setDataLeitura(Date dataLeitura) {
        this.dataLeitura = dataLeitura;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="arquivoLiquidacao")
    public Set getLinhasArquivoLiquidacaos() {
        return this.linhasArquivoLiquidacaos;
    }
    
    public void setLinhasArquivoLiquidacaos(Set linhasArquivoLiquidacaos) {
        this.linhasArquivoLiquidacaos = linhasArquivoLiquidacaos;
    }




}


