package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BalancoItem generated by hbm2java
 */
@Entity
@Table(name="BALANCO_ITEM"
    ,schema="DESENV"
)
public class BalancoItem  implements java.io.Serializable {


     private BalancoItemId id;
     private Item item;
     private Unidade unidade;
     private Empresa empresa;
     private BigDecimal qtInicial;
     private BigDecimal qtEntrada;
     private BigDecimal qtSaida;
     private BigDecimal qtInventario;
     private BigDecimal valorMedio;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;

    public BalancoItem() {
    }

    public BalancoItem(BalancoItemId id, Item item, Unidade unidade, Empresa empresa, BigDecimal qtInicial, BigDecimal qtEntrada, BigDecimal qtSaida, BigDecimal qtInventario, BigDecimal valorMedio, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
       this.id = id;
       this.item = item;
       this.unidade = unidade;
       this.empresa = empresa;
       this.qtInicial = qtInicial;
       this.qtEntrada = qtEntrada;
       this.qtSaida = qtSaida;
       this.qtInventario = qtInventario;
       this.valorMedio = valorMedio;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="data", column=@Column(name="DATA", nullable=false, length=7) ), 
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="uniId", column=@Column(name="UNI_ID", nullable=false, precision=22, scale=0) ) } )
    public BalancoItemId getId() {
        return this.id;
    }
    
    public void setId(BalancoItemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_ID", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false, insertable=false, updatable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="QT_INICIAL", nullable=false, precision=22, scale=0)
    public BigDecimal getQtInicial() {
        return this.qtInicial;
    }
    
    public void setQtInicial(BigDecimal qtInicial) {
        this.qtInicial = qtInicial;
    }

    
    @Column(name="QT_ENTRADA", nullable=false, precision=22, scale=0)
    public BigDecimal getQtEntrada() {
        return this.qtEntrada;
    }
    
    public void setQtEntrada(BigDecimal qtEntrada) {
        this.qtEntrada = qtEntrada;
    }

    
    @Column(name="QT_SAIDA", nullable=false, precision=22, scale=0)
    public BigDecimal getQtSaida() {
        return this.qtSaida;
    }
    
    public void setQtSaida(BigDecimal qtSaida) {
        this.qtSaida = qtSaida;
    }

    
    @Column(name="QT_INVENTARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getQtInventario() {
        return this.qtInventario;
    }
    
    public void setQtInventario(BigDecimal qtInventario) {
        this.qtInventario = qtInventario;
    }

    
    @Column(name="VALOR_MEDIO", nullable=false, precision=17)
    public BigDecimal getValorMedio() {
        return this.valorMedio;
    }
    
    public void setValorMedio(BigDecimal valorMedio) {
        this.valorMedio = valorMedio;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


