package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CampoLayout generated by hbm2java
 */
@Entity
@Table(name="CAMPO_LAYOUT"
    ,schema="DESENV"
)
public class CampoLayout  implements java.io.Serializable {


     private CampoLayoutId id;
     private LayoutBancario layoutBancario;
     private Empresa empresa;
     private short nuInicio;
     private short nuTamanho;
     private String flTipo;
     private String flTipoRegistro;
     private String flProcessa;
     private String dsMascara;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public CampoLayout() {
    }

	
    public CampoLayout(CampoLayoutId id, LayoutBancario layoutBancario, Empresa empresa, short nuInicio, short nuTamanho, String flTipo, String flTipoRegistro) {
        this.id = id;
        this.layoutBancario = layoutBancario;
        this.empresa = empresa;
        this.nuInicio = nuInicio;
        this.nuTamanho = nuTamanho;
        this.flTipo = flTipo;
        this.flTipoRegistro = flTipoRegistro;
    }
    public CampoLayout(CampoLayoutId id, LayoutBancario layoutBancario, Empresa empresa, short nuInicio, short nuTamanho, String flTipo, String flTipoRegistro, String flProcessa, String dsMascara, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.layoutBancario = layoutBancario;
       this.empresa = empresa;
       this.nuInicio = nuInicio;
       this.nuTamanho = nuTamanho;
       this.flTipo = flTipo;
       this.flTipoRegistro = flTipoRegistro;
       this.flProcessa = flProcessa;
       this.dsMascara = dsMascara;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="laybcoId", column=@Column(name="LAYBCO_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="nmCampo", column=@Column(name="NM_CAMPO", nullable=false, length=30) ) } )
    public CampoLayoutId getId() {
        return this.id;
    }
    
    public void setId(CampoLayoutId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LAYBCO_ID", nullable=false, insertable=false, updatable=false)
    public LayoutBancario getLayoutBancario() {
        return this.layoutBancario;
    }
    
    public void setLayoutBancario(LayoutBancario layoutBancario) {
        this.layoutBancario = layoutBancario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NU_INICIO", nullable=false, precision=3, scale=0)
    public short getNuInicio() {
        return this.nuInicio;
    }
    
    public void setNuInicio(short nuInicio) {
        this.nuInicio = nuInicio;
    }

    
    @Column(name="NU_TAMANHO", nullable=false, precision=3, scale=0)
    public short getNuTamanho() {
        return this.nuTamanho;
    }
    
    public void setNuTamanho(short nuTamanho) {
        this.nuTamanho = nuTamanho;
    }

    
    @Column(name="FL_TIPO", nullable=false, length=1)
    public String getFlTipo() {
        return this.flTipo;
    }
    
    public void setFlTipo(String flTipo) {
        this.flTipo = flTipo;
    }

    
    @Column(name="FL_TIPO_REGISTRO", nullable=false, length=2)
    public String getFlTipoRegistro() {
        return this.flTipoRegistro;
    }
    
    public void setFlTipoRegistro(String flTipoRegistro) {
        this.flTipoRegistro = flTipoRegistro;
    }

    
    @Column(name="FL_PROCESSA", length=1)
    public String getFlProcessa() {
        return this.flProcessa;
    }
    
    public void setFlProcessa(String flProcessa) {
        this.flProcessa = flProcessa;
    }

    
    @Column(name="DS_MASCARA", length=30)
    public String getDsMascara() {
        return this.dsMascara;
    }
    
    public void setDsMascara(String dsMascara) {
        this.dsMascara = dsMascara;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


