package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChequePagamentoPedido generated by hbm2java
 */
@Entity
@Table(name="CHEQUE_PAGAMENTO_PEDIDO"
    ,schema="DESENV"
)
public class ChequePagamentoPedido  implements java.io.Serializable {


     private ChequePagamentoPedidoId id;
     private Cheque cheque;
     private PagamentoPedido pagamentoPedido;
     private Empresa empresa;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public ChequePagamentoPedido() {
    }

	
    public ChequePagamentoPedido(ChequePagamentoPedidoId id, Cheque cheque, PagamentoPedido pagamentoPedido, Empresa empresa) {
        this.id = id;
        this.cheque = cheque;
        this.pagamentoPedido = pagamentoPedido;
        this.empresa = empresa;
    }
    public ChequePagamentoPedido(ChequePagamentoPedidoId id, Cheque cheque, PagamentoPedido pagamentoPedido, Empresa empresa, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.cheque = cheque;
       this.pagamentoPedido = pagamentoPedido;
       this.empresa = empresa;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pagpeId", column=@Column(name="PAGPE_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="cheId", column=@Column(name="CHE_ID", nullable=false, precision=22, scale=0) ) } )
    public ChequePagamentoPedidoId getId() {
        return this.id;
    }
    
    public void setId(ChequePagamentoPedidoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CHE_ID", nullable=false, insertable=false, updatable=false)
    public Cheque getCheque() {
        return this.cheque;
    }
    
    public void setCheque(Cheque cheque) {
        this.cheque = cheque;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGPE_ID", nullable=false, insertable=false, updatable=false)
    public PagamentoPedido getPagamentoPedido() {
        return this.pagamentoPedido;
    }
    
    public void setPagamentoPedido(PagamentoPedido pagamentoPedido) {
        this.pagamentoPedido = pagamentoPedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


