package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComandoLayout generated by hbm2java
 */
@Entity
@Table(name="COMANDO_LAYOUT"
    ,schema="DESENV"
)
public class ComandoLayout  implements java.io.Serializable {


     private ComandoLayoutId id;
     private LayoutBancario layoutBancario;
     private Empresa empresa;
     private String dsComando;
     private String flAcao;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set movimentoTitulos = new HashSet(0);

    public ComandoLayout() {
    }

	
    public ComandoLayout(ComandoLayoutId id, LayoutBancario layoutBancario, Empresa empresa, String dsComando, String flAcao) {
        this.id = id;
        this.layoutBancario = layoutBancario;
        this.empresa = empresa;
        this.dsComando = dsComando;
        this.flAcao = flAcao;
    }
    public ComandoLayout(ComandoLayoutId id, LayoutBancario layoutBancario, Empresa empresa, String dsComando, String flAcao, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set movimentoTitulos) {
       this.id = id;
       this.layoutBancario = layoutBancario;
       this.empresa = empresa;
       this.dsComando = dsComando;
       this.flAcao = flAcao;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.movimentoTitulos = movimentoTitulos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="flRemessaRetorno", column=@Column(name="FL_REMESSA_RETORNO", nullable=false, length=2) ), 
        @AttributeOverride(name="laybcoId", column=@Column(name="LAYBCO_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="nuComando", column=@Column(name="NU_COMANDO", nullable=false, length=2) ) } )
    public ComandoLayoutId getId() {
        return this.id;
    }
    
    public void setId(ComandoLayoutId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LAYBCO_ID", nullable=false, insertable=false, updatable=false)
    public LayoutBancario getLayoutBancario() {
        return this.layoutBancario;
    }
    
    public void setLayoutBancario(LayoutBancario layoutBancario) {
        this.layoutBancario = layoutBancario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="DS_COMANDO", nullable=false)
    public String getDsComando() {
        return this.dsComando;
    }
    
    public void setDsComando(String dsComando) {
        this.dsComando = dsComando;
    }

    
    @Column(name="FL_ACAO", nullable=false, length=5)
    public String getFlAcao() {
        return this.flAcao;
    }
    
    public void setFlAcao(String flAcao) {
        this.flAcao = flAcao;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comandoLayout")
    public Set getMovimentoTitulos() {
        return this.movimentoTitulos;
    }
    
    public void setMovimentoTitulos(Set movimentoTitulos) {
        this.movimentoTitulos = movimentoTitulos;
    }




}


