package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsumoMaterialId generated by hbm2java
 */
@Embeddable
public class ConsumoMaterialId  implements java.io.Serializable {


     private Date data;
     private BigDecimal materialId;
     private BigDecimal profissionalId;

    public ConsumoMaterialId() {
    }

    public ConsumoMaterialId(Date data, BigDecimal materialId, BigDecimal profissionalId) {
       this.data = data;
       this.materialId = materialId;
       this.profissionalId = profissionalId;
    }
   


    @Column(name="DATA", nullable=false, length=7)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }


    @Column(name="MATERIAL_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(BigDecimal materialId) {
        this.materialId = materialId;
    }


    @Column(name="PROFISSIONAL_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getProfissionalId() {
        return this.profissionalId;
    }
    
    public void setProfissionalId(BigDecimal profissionalId) {
        this.profissionalId = profissionalId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsumoMaterialId) ) return false;
		 ConsumoMaterialId castOther = ( ConsumoMaterialId ) other; 
         
		 return ( (this.getData()==castOther.getData()) || ( this.getData()!=null && castOther.getData()!=null && this.getData().equals(castOther.getData()) ) )
 && ( (this.getMaterialId()==castOther.getMaterialId()) || ( this.getMaterialId()!=null && castOther.getMaterialId()!=null && this.getMaterialId().equals(castOther.getMaterialId()) ) )
 && ( (this.getProfissionalId()==castOther.getProfissionalId()) || ( this.getProfissionalId()!=null && castOther.getProfissionalId()!=null && this.getProfissionalId().equals(castOther.getProfissionalId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getData() == null ? 0 : this.getData().hashCode() );
         result = 37 * result + ( getMaterialId() == null ? 0 : this.getMaterialId().hashCode() );
         result = 37 * result + ( getProfissionalId() == null ? 0 : this.getProfissionalId().hashCode() );
         return result;
   }   


}


