package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="CONTRATO"
    ,schema="DESENV"
)
public class Contrato  implements java.io.Serializable {


     private BigDecimal id;
     private Paciente paciente;
     private TipoContrato tipoContrato;
     private Unidade unidade;
     private Empresa empresa;
     private Date dtContrato;
     private String flStatus;
     private BigDecimal valorOriginal;
     private BigDecimal valorPago;
     private BigDecimal valorDesconto;
     private BigDecimal valorParcelado;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal valorEntrada;
     private Character flGeraBoletoEntrada;
     private Date dataVencimentoEntrada;
     private Date dataVencimento1Parcela;
     private BigDecimal valorAjuste;
     private Set contratoCondicoeses = new HashSet(0);
     private Set cobrancas = new HashSet(0);
     private Set procedimentoContratos = new HashSet(0);
     private Set procedimentoPacientes = new HashSet(0);
     private Set pagamentoPacientes = new HashSet(0);

    public Contrato() {
    }

	
    public Contrato(BigDecimal id, Paciente paciente, Unidade unidade, Empresa empresa, Date dtContrato, String flStatus, BigDecimal valorOriginal, BigDecimal valorPago, BigDecimal valorDesconto, BigDecimal valorParcelado, BigDecimal valorAjuste) {
        this.id = id;
        this.paciente = paciente;
        this.unidade = unidade;
        this.empresa = empresa;
        this.dtContrato = dtContrato;
        this.flStatus = flStatus;
        this.valorOriginal = valorOriginal;
        this.valorPago = valorPago;
        this.valorDesconto = valorDesconto;
        this.valorParcelado = valorParcelado;
        this.valorAjuste = valorAjuste;
    }
    public Contrato(BigDecimal id, Paciente paciente, TipoContrato tipoContrato, Unidade unidade, Empresa empresa, Date dtContrato, String flStatus, BigDecimal valorOriginal, BigDecimal valorPago, BigDecimal valorDesconto, BigDecimal valorParcelado, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal valorEntrada, Character flGeraBoletoEntrada, Date dataVencimentoEntrada, Date dataVencimento1Parcela, BigDecimal valorAjuste, Set contratoCondicoeses, Set cobrancas, Set procedimentoContratos, Set procedimentoPacientes, Set pagamentoPacientes) {
       this.id = id;
       this.paciente = paciente;
       this.tipoContrato = tipoContrato;
       this.unidade = unidade;
       this.empresa = empresa;
       this.dtContrato = dtContrato;
       this.flStatus = flStatus;
       this.valorOriginal = valorOriginal;
       this.valorPago = valorPago;
       this.valorDesconto = valorDesconto;
       this.valorParcelado = valorParcelado;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.valorEntrada = valorEntrada;
       this.flGeraBoletoEntrada = flGeraBoletoEntrada;
       this.dataVencimentoEntrada = dataVencimentoEntrada;
       this.dataVencimento1Parcela = dataVencimento1Parcela;
       this.valorAjuste = valorAjuste;
       this.contratoCondicoeses = contratoCondicoeses;
       this.cobrancas = cobrancas;
       this.procedimentoContratos = procedimentoContratos;
       this.procedimentoPacientes = procedimentoPacientes;
       this.pagamentoPacientes = pagamentoPacientes;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TPCONT_ID")
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }
    
    public void setTipoContrato(TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CONTRATO", nullable=false, length=7)
    public Date getDtContrato() {
        return this.dtContrato;
    }
    
    public void setDtContrato(Date dtContrato) {
        this.dtContrato = dtContrato;
    }

    
    @Column(name="FL_STATUS", nullable=false, length=2)
    public String getFlStatus() {
        return this.flStatus;
    }
    
    public void setFlStatus(String flStatus) {
        this.flStatus = flStatus;
    }

    
    @Column(name="VALOR_ORIGINAL", nullable=false, precision=17)
    public BigDecimal getValorOriginal() {
        return this.valorOriginal;
    }
    
    public void setValorOriginal(BigDecimal valorOriginal) {
        this.valorOriginal = valorOriginal;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=17)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VALOR_DESCONTO", nullable=false, precision=17)
    public BigDecimal getValorDesconto() {
        return this.valorDesconto;
    }
    
    public void setValorDesconto(BigDecimal valorDesconto) {
        this.valorDesconto = valorDesconto;
    }

    
    @Column(name="VALOR_PARCELADO", nullable=false, precision=17)
    public BigDecimal getValorParcelado() {
        return this.valorParcelado;
    }
    
    public void setValorParcelado(BigDecimal valorParcelado) {
        this.valorParcelado = valorParcelado;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="VALOR_ENTRADA", precision=22, scale=0)
    public BigDecimal getValorEntrada() {
        return this.valorEntrada;
    }
    
    public void setValorEntrada(BigDecimal valorEntrada) {
        this.valorEntrada = valorEntrada;
    }

    
    @Column(name="FL_GERA_BOLETO_ENTRADA", length=1)
    public Character getFlGeraBoletoEntrada() {
        return this.flGeraBoletoEntrada;
    }
    
    public void setFlGeraBoletoEntrada(Character flGeraBoletoEntrada) {
        this.flGeraBoletoEntrada = flGeraBoletoEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_VENCIMENTO_ENTRADA", length=7)
    public Date getDataVencimentoEntrada() {
        return this.dataVencimentoEntrada;
    }
    
    public void setDataVencimentoEntrada(Date dataVencimentoEntrada) {
        this.dataVencimentoEntrada = dataVencimentoEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_VENCIMENTO_1_PARCELA", length=7)
    public Date getDataVencimento1Parcela() {
        return this.dataVencimento1Parcela;
    }
    
    public void setDataVencimento1Parcela(Date dataVencimento1Parcela) {
        this.dataVencimento1Parcela = dataVencimento1Parcela;
    }

    
    @Column(name="VALOR_AJUSTE", nullable=false, precision=17)
    public BigDecimal getValorAjuste() {
        return this.valorAjuste;
    }
    
    public void setValorAjuste(BigDecimal valorAjuste) {
        this.valorAjuste = valorAjuste;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set getContratoCondicoeses() {
        return this.contratoCondicoeses;
    }
    
    public void setContratoCondicoeses(Set contratoCondicoeses) {
        this.contratoCondicoeses = contratoCondicoeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set getCobrancas() {
        return this.cobrancas;
    }
    
    public void setCobrancas(Set cobrancas) {
        this.cobrancas = cobrancas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set getProcedimentoContratos() {
        return this.procedimentoContratos;
    }
    
    public void setProcedimentoContratos(Set procedimentoContratos) {
        this.procedimentoContratos = procedimentoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set getProcedimentoPacientes() {
        return this.procedimentoPacientes;
    }
    
    public void setProcedimentoPacientes(Set procedimentoPacientes) {
        this.procedimentoPacientes = procedimentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set getPagamentoPacientes() {
        return this.pagamentoPacientes;
    }
    
    public void setPagamentoPacientes(Set pagamentoPacientes) {
        this.pagamentoPacientes = pagamentoPacientes;
    }




}


