package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conta generated by hbm2java
 */
@Entity
@Table(name="CONTA"
    ,schema="DESENV"
)
public class Conta  implements java.io.Serializable {


     private BigDecimal id;
     private Unidade unidade;
     private Empresa empresa;
     private String nome;
     private char flDinheiro;
     private BigDecimal vlSaldoInicial;
     private BigDecimal vlSaldoAtual;
     private Date dtFechamento;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set programacaoPagamentoNfs = new HashSet(0);
     private Set meioPagamentoContaUnidades = new HashSet(0);
     private Set movimentoCaixas = new HashSet(0);
     private Set portadors = new HashSet(0);
     private Set contaOperadors = new HashSet(0);
     private Set convenioBancarios = new HashSet(0);
     private Set pagamentoFornecedors = new HashSet(0);

    public Conta() {
    }

	
    public Conta(BigDecimal id, Unidade unidade, Empresa empresa, String nome, char flDinheiro, BigDecimal vlSaldoInicial, BigDecimal vlSaldoAtual) {
        this.id = id;
        this.unidade = unidade;
        this.empresa = empresa;
        this.nome = nome;
        this.flDinheiro = flDinheiro;
        this.vlSaldoInicial = vlSaldoInicial;
        this.vlSaldoAtual = vlSaldoAtual;
    }
    public Conta(BigDecimal id, Unidade unidade, Empresa empresa, String nome, char flDinheiro, BigDecimal vlSaldoInicial, BigDecimal vlSaldoAtual, Date dtFechamento, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set programacaoPagamentoNfs, Set meioPagamentoContaUnidades, Set movimentoCaixas, Set portadors, Set contaOperadors, Set convenioBancarios, Set pagamentoFornecedors) {
       this.id = id;
       this.unidade = unidade;
       this.empresa = empresa;
       this.nome = nome;
       this.flDinheiro = flDinheiro;
       this.vlSaldoInicial = vlSaldoInicial;
       this.vlSaldoAtual = vlSaldoAtual;
       this.dtFechamento = dtFechamento;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.programacaoPagamentoNfs = programacaoPagamentoNfs;
       this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
       this.movimentoCaixas = movimentoCaixas;
       this.portadors = portadors;
       this.contaOperadors = contaOperadors;
       this.convenioBancarios = convenioBancarios;
       this.pagamentoFornecedors = pagamentoFornecedors;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_DINHEIRO", nullable=false, length=1)
    public char getFlDinheiro() {
        return this.flDinheiro;
    }
    
    public void setFlDinheiro(char flDinheiro) {
        this.flDinheiro = flDinheiro;
    }

    
    @Column(name="VL_SALDO_INICIAL", nullable=false, precision=15)
    public BigDecimal getVlSaldoInicial() {
        return this.vlSaldoInicial;
    }
    
    public void setVlSaldoInicial(BigDecimal vlSaldoInicial) {
        this.vlSaldoInicial = vlSaldoInicial;
    }

    
    @Column(name="VL_SALDO_ATUAL", nullable=false, precision=15)
    public BigDecimal getVlSaldoAtual() {
        return this.vlSaldoAtual;
    }
    
    public void setVlSaldoAtual(BigDecimal vlSaldoAtual) {
        this.vlSaldoAtual = vlSaldoAtual;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FECHAMENTO", length=7)
    public Date getDtFechamento() {
        return this.dtFechamento;
    }
    
    public void setDtFechamento(Date dtFechamento) {
        this.dtFechamento = dtFechamento;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getProgramacaoPagamentoNfs() {
        return this.programacaoPagamentoNfs;
    }
    
    public void setProgramacaoPagamentoNfs(Set programacaoPagamentoNfs) {
        this.programacaoPagamentoNfs = programacaoPagamentoNfs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getMeioPagamentoContaUnidades() {
        return this.meioPagamentoContaUnidades;
    }
    
    public void setMeioPagamentoContaUnidades(Set meioPagamentoContaUnidades) {
        this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getMovimentoCaixas() {
        return this.movimentoCaixas;
    }
    
    public void setMovimentoCaixas(Set movimentoCaixas) {
        this.movimentoCaixas = movimentoCaixas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getPortadors() {
        return this.portadors;
    }
    
    public void setPortadors(Set portadors) {
        this.portadors = portadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getContaOperadors() {
        return this.contaOperadors;
    }
    
    public void setContaOperadors(Set contaOperadors) {
        this.contaOperadors = contaOperadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getConvenioBancarios() {
        return this.convenioBancarios;
    }
    
    public void setConvenioBancarios(Set convenioBancarios) {
        this.convenioBancarios = convenioBancarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conta")
    public Set getPagamentoFornecedors() {
        return this.pagamentoFornecedors;
    }
    
    public void setPagamentoFornecedors(Set pagamentoFornecedors) {
        this.pagamentoFornecedors = pagamentoFornecedors;
    }




}


