package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContratoCondicoes generated by hbm2java
 */
@Entity
@Table(name="CONTRATO_CONDICOES"
    ,schema="DESENV"
)
public class ContratoCondicoes  implements java.io.Serializable {


     private ContratoCondicoesId id;
     private Contrato contrato;
     private TipoContrato tipoContrato;
     private Empresa empresa;
     private BigDecimal nuParcelas;
     private Date primeiroVencimento;
     private BigDecimal valorEntrada;
     private BigDecimal valorOriginal;
     private BigDecimal pcEncargos;
     private BigDecimal valorParcela;
     private BigDecimal valorDesconto;
     private BigDecimal valorTaxaAdmin;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public ContratoCondicoes() {
    }

	
    public ContratoCondicoes(ContratoCondicoesId id, Contrato contrato, TipoContrato tipoContrato, Empresa empresa, BigDecimal nuParcelas, BigDecimal valorOriginal, BigDecimal pcEncargos, BigDecimal valorParcela, BigDecimal valorDesconto, BigDecimal valorTaxaAdmin) {
        this.id = id;
        this.contrato = contrato;
        this.tipoContrato = tipoContrato;
        this.empresa = empresa;
        this.nuParcelas = nuParcelas;
        this.valorOriginal = valorOriginal;
        this.pcEncargos = pcEncargos;
        this.valorParcela = valorParcela;
        this.valorDesconto = valorDesconto;
        this.valorTaxaAdmin = valorTaxaAdmin;
    }
    public ContratoCondicoes(ContratoCondicoesId id, Contrato contrato, TipoContrato tipoContrato, Empresa empresa, BigDecimal nuParcelas, Date primeiroVencimento, BigDecimal valorEntrada, BigDecimal valorOriginal, BigDecimal pcEncargos, BigDecimal valorParcela, BigDecimal valorDesconto, BigDecimal valorTaxaAdmin, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.contrato = contrato;
       this.tipoContrato = tipoContrato;
       this.empresa = empresa;
       this.nuParcelas = nuParcelas;
       this.primeiroVencimento = primeiroVencimento;
       this.valorEntrada = valorEntrada;
       this.valorOriginal = valorOriginal;
       this.pcEncargos = pcEncargos;
       this.valorParcela = valorParcela;
       this.valorDesconto = valorDesconto;
       this.valorTaxaAdmin = valorTaxaAdmin;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="contId", column=@Column(name="CONT_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="tpcontId", column=@Column(name="TPCONT_ID", nullable=false, precision=22, scale=0) ) } )
    public ContratoCondicoesId getId() {
        return this.id;
    }
    
    public void setId(ContratoCondicoesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONT_ID", nullable=false, insertable=false, updatable=false)
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TPCONT_ID", nullable=false, insertable=false, updatable=false)
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }
    
    public void setTipoContrato(TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NU_PARCELAS", nullable=false, precision=22, scale=0)
    public BigDecimal getNuParcelas() {
        return this.nuParcelas;
    }
    
    public void setNuParcelas(BigDecimal nuParcelas) {
        this.nuParcelas = nuParcelas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PRIMEIRO_VENCIMENTO", length=7)
    public Date getPrimeiroVencimento() {
        return this.primeiroVencimento;
    }
    
    public void setPrimeiroVencimento(Date primeiroVencimento) {
        this.primeiroVencimento = primeiroVencimento;
    }

    
    @Column(name="VALOR_ENTRADA", precision=17)
    public BigDecimal getValorEntrada() {
        return this.valorEntrada;
    }
    
    public void setValorEntrada(BigDecimal valorEntrada) {
        this.valorEntrada = valorEntrada;
    }

    
    @Column(name="VALOR_ORIGINAL", nullable=false, precision=17)
    public BigDecimal getValorOriginal() {
        return this.valorOriginal;
    }
    
    public void setValorOriginal(BigDecimal valorOriginal) {
        this.valorOriginal = valorOriginal;
    }

    
    @Column(name="PC_ENCARGOS", nullable=false, precision=7, scale=4)
    public BigDecimal getPcEncargos() {
        return this.pcEncargos;
    }
    
    public void setPcEncargos(BigDecimal pcEncargos) {
        this.pcEncargos = pcEncargos;
    }

    
    @Column(name="VALOR_PARCELA", nullable=false, precision=17)
    public BigDecimal getValorParcela() {
        return this.valorParcela;
    }
    
    public void setValorParcela(BigDecimal valorParcela) {
        this.valorParcela = valorParcela;
    }

    
    @Column(name="VALOR_DESCONTO", nullable=false, precision=17)
    public BigDecimal getValorDesconto() {
        return this.valorDesconto;
    }
    
    public void setValorDesconto(BigDecimal valorDesconto) {
        this.valorDesconto = valorDesconto;
    }

    
    @Column(name="VALOR_TAXA_ADMIN", nullable=false, precision=17)
    public BigDecimal getValorTaxaAdmin() {
        return this.valorTaxaAdmin;
    }
    
    public void setValorTaxaAdmin(BigDecimal valorTaxaAdmin) {
        this.valorTaxaAdmin = valorTaxaAdmin;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


