package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContaOperadorId generated by hbm2java
 */
@Embeddable
public class ContaOperadorId  implements java.io.Serializable {


     private BigDecimal conId;
     private BigDecimal grusCdUsuario;

    public ContaOperadorId() {
    }

    public ContaOperadorId(BigDecimal conId, BigDecimal grusCdUsuario) {
       this.conId = conId;
       this.grusCdUsuario = grusCdUsuario;
    }
   


    @Column(name="CON_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getConId() {
        return this.conId;
    }
    
    public void setConId(BigDecimal conId) {
        this.conId = conId;
    }


    @Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getGrusCdUsuario() {
        return this.grusCdUsuario;
    }
    
    public void setGrusCdUsuario(BigDecimal grusCdUsuario) {
        this.grusCdUsuario = grusCdUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContaOperadorId) ) return false;
		 ContaOperadorId castOther = ( ContaOperadorId ) other; 
         
		 return ( (this.getConId()==castOther.getConId()) || ( this.getConId()!=null && castOther.getConId()!=null && this.getConId().equals(castOther.getConId()) ) )
 && ( (this.getGrusCdUsuario()==castOther.getGrusCdUsuario()) || ( this.getGrusCdUsuario()!=null && castOther.getGrusCdUsuario()!=null && this.getGrusCdUsuario().equals(castOther.getGrusCdUsuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getConId() == null ? 0 : this.getConId().hashCode() );
         result = 37 * result + ( getGrusCdUsuario() == null ? 0 : this.getGrusCdUsuario().hashCode() );
         return result;
   }   


}


