package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Convenio generated by hbm2java
 */
@Entity
@Table(name="CONVENIO"
    ,schema="DESENV"
)
public class Convenio  implements java.io.Serializable {


     private ConvenioId id;
     private Empresa empresa;
     private String nome;
     private char flAtivo;
     private byte diaFechamentoGuias;
     private Date dtUltimoFechamento;
     private String flCalculoValor;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set motivoGlosas = new HashSet(0);
     private Set repasseProfissionals = new HashSet(0);
     private Set agendas = new HashSet(0);
     private Set convenioPacientes = new HashSet(0);
     private Set convenioEspecialidades = new HashSet(0);
     private Set tabelaConvenios = new HashSet(0);
     private Set fechamentoConvenios = new HashSet(0);

    public Convenio() {
    }

	
    public Convenio(ConvenioId id, Empresa empresa, String nome, char flAtivo, byte diaFechamentoGuias, String flCalculoValor) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.flAtivo = flAtivo;
        this.diaFechamentoGuias = diaFechamentoGuias;
        this.flCalculoValor = flCalculoValor;
    }
    public Convenio(ConvenioId id, Empresa empresa, String nome, char flAtivo, byte diaFechamentoGuias, Date dtUltimoFechamento, String flCalculoValor, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set motivoGlosas, Set repasseProfissionals, Set agendas, Set convenioPacientes, Set convenioEspecialidades, Set tabelaConvenios, Set fechamentoConvenios) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.flAtivo = flAtivo;
       this.diaFechamentoGuias = diaFechamentoGuias;
       this.dtUltimoFechamento = dtUltimoFechamento;
       this.flCalculoValor = flCalculoValor;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.motivoGlosas = motivoGlosas;
       this.repasseProfissionals = repasseProfissionals;
       this.agendas = agendas;
       this.convenioPacientes = convenioPacientes;
       this.convenioEspecialidades = convenioEspecialidades;
       this.tabelaConvenios = tabelaConvenios;
       this.fechamentoConvenios = fechamentoConvenios;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="empId", column=@Column(name="EMP_ID", nullable=false, precision=22, scale=0) ) } )
    public ConvenioId getId() {
        return this.id;
    }
    
    public void setId(ConvenioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public char getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(char flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="DIA_FECHAMENTO_GUIAS", nullable=false, precision=2, scale=0)
    public byte getDiaFechamentoGuias() {
        return this.diaFechamentoGuias;
    }
    
    public void setDiaFechamentoGuias(byte diaFechamentoGuias) {
        this.diaFechamentoGuias = diaFechamentoGuias;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMO_FECHAMENTO", length=7)
    public Date getDtUltimoFechamento() {
        return this.dtUltimoFechamento;
    }
    
    public void setDtUltimoFechamento(Date dtUltimoFechamento) {
        this.dtUltimoFechamento = dtUltimoFechamento;
    }

    
    @Column(name="FL_CALCULO_VALOR", nullable=false, length=3)
    public String getFlCalculoValor() {
        return this.flCalculoValor;
    }
    
    public void setFlCalculoValor(String flCalculoValor) {
        this.flCalculoValor = flCalculoValor;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getMotivoGlosas() {
        return this.motivoGlosas;
    }
    
    public void setMotivoGlosas(Set motivoGlosas) {
        this.motivoGlosas = motivoGlosas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getRepasseProfissionals() {
        return this.repasseProfissionals;
    }
    
    public void setRepasseProfissionals(Set repasseProfissionals) {
        this.repasseProfissionals = repasseProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getConvenioPacientes() {
        return this.convenioPacientes;
    }
    
    public void setConvenioPacientes(Set convenioPacientes) {
        this.convenioPacientes = convenioPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getConvenioEspecialidades() {
        return this.convenioEspecialidades;
    }
    
    public void setConvenioEspecialidades(Set convenioEspecialidades) {
        this.convenioEspecialidades = convenioEspecialidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getTabelaConvenios() {
        return this.tabelaConvenios;
    }
    
    public void setTabelaConvenios(Set tabelaConvenios) {
        this.tabelaConvenios = tabelaConvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenio")
    public Set getFechamentoConvenios() {
        return this.fechamentoConvenios;
    }
    
    public void setFechamentoConvenios(Set fechamentoConvenios) {
        this.fechamentoConvenios = fechamentoConvenios;
    }




}


