package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConvenioPaciente generated by hbm2java
 */
@Entity
@Table(name="CONVENIO_PACIENTE"
    ,schema="DESENV"
)
public class ConvenioPaciente  implements java.io.Serializable {


     private ConvenioPacienteId id;
     private Convenio convenio;
     private Paciente paciente;
     private Empresa empresa;
     private char flAtivo;
     private String numero;
     private String plano;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set guiaPacientes = new HashSet(0);

    public ConvenioPaciente() {
    }

	
    public ConvenioPaciente(ConvenioPacienteId id, Convenio convenio, Paciente paciente, Empresa empresa, char flAtivo, String numero) {
        this.id = id;
        this.convenio = convenio;
        this.paciente = paciente;
        this.empresa = empresa;
        this.flAtivo = flAtivo;
        this.numero = numero;
    }
    public ConvenioPaciente(ConvenioPacienteId id, Convenio convenio, Paciente paciente, Empresa empresa, char flAtivo, String numero, String plano, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set guiaPacientes) {
       this.id = id;
       this.convenio = convenio;
       this.paciente = paciente;
       this.empresa = empresa;
       this.flAtivo = flAtivo;
       this.numero = numero;
       this.plano = plano;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.guiaPacientes = guiaPacientes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pacienteId", column=@Column(name="PACIENTE_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="convId", column=@Column(name="CONV_ID", nullable=false, precision=22, scale=0) ) } )
    public ConvenioPacienteId getId() {
        return this.id;
    }
    
    public void setId(ConvenioPacienteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false, insertable=false, updatable=false) } )
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PACIENTE_ID", nullable=false, insertable=false, updatable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public char getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(char flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="NUMERO", nullable=false, length=30)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="PLANO", length=50)
    public String getPlano() {
        return this.plano;
    }
    
    public void setPlano(String plano) {
        this.plano = plano;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenioPaciente")
    public Set getGuiaPacientes() {
        return this.guiaPacientes;
    }
    
    public void setGuiaPacientes(Set guiaPacientes) {
        this.guiaPacientes = guiaPacientes;
    }




}


