package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConvenioBancarioId generated by hbm2java
 */
@Embeddable
public class ConvenioBancarioId  implements java.io.Serializable {


     private String banco;
     private String agencia;
     private String cedente;
     private String carteira;
     private String convenio;

    public ConvenioBancarioId() {
    }

    public ConvenioBancarioId(String banco, String agencia, String cedente, String carteira, String convenio) {
       this.banco = banco;
       this.agencia = agencia;
       this.cedente = cedente;
       this.carteira = carteira;
       this.convenio = convenio;
    }
   


    @Column(name="BANCO", nullable=false, length=3)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }


    @Column(name="AGENCIA", nullable=false, length=5)
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }


    @Column(name="CEDENTE", nullable=false, length=20)
    public String getCedente() {
        return this.cedente;
    }
    
    public void setCedente(String cedente) {
        this.cedente = cedente;
    }


    @Column(name="CARTEIRA", nullable=false, length=2)
    public String getCarteira() {
        return this.carteira;
    }
    
    public void setCarteira(String carteira) {
        this.carteira = carteira;
    }


    @Column(name="CONVENIO", nullable=false, length=10)
    public String getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(String convenio) {
        this.convenio = convenio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConvenioBancarioId) ) return false;
		 ConvenioBancarioId castOther = ( ConvenioBancarioId ) other; 
         
		 return ( (this.getBanco()==castOther.getBanco()) || ( this.getBanco()!=null && castOther.getBanco()!=null && this.getBanco().equals(castOther.getBanco()) ) )
 && ( (this.getAgencia()==castOther.getAgencia()) || ( this.getAgencia()!=null && castOther.getAgencia()!=null && this.getAgencia().equals(castOther.getAgencia()) ) )
 && ( (this.getCedente()==castOther.getCedente()) || ( this.getCedente()!=null && castOther.getCedente()!=null && this.getCedente().equals(castOther.getCedente()) ) )
 && ( (this.getCarteira()==castOther.getCarteira()) || ( this.getCarteira()!=null && castOther.getCarteira()!=null && this.getCarteira().equals(castOther.getCarteira()) ) )
 && ( (this.getConvenio()==castOther.getConvenio()) || ( this.getConvenio()!=null && castOther.getConvenio()!=null && this.getConvenio().equals(castOther.getConvenio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBanco() == null ? 0 : this.getBanco().hashCode() );
         result = 37 * result + ( getAgencia() == null ? 0 : this.getAgencia().hashCode() );
         result = 37 * result + ( getCedente() == null ? 0 : this.getCedente().hashCode() );
         result = 37 * result + ( getCarteira() == null ? 0 : this.getCarteira().hashCode() );
         result = 37 * result + ( getConvenio() == null ? 0 : this.getConvenio().hashCode() );
         return result;
   }   


}


