package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConvenioBancario generated by hbm2java
 */
@Entity
@Table(name="CONVENIO_BANCARIO"
    ,schema="DESENV"
)
public class ConvenioBancario  implements java.io.Serializable {


     private ConvenioBancarioId id;
     private LayoutBancario layoutBancario;
     private Conta conta;
     private Empresa empresa;
     private String bancoDv;
     private String agenciaDv;
     private String cedenteDv;
     private long sequenciaMaxima;
     private String nomeSequencia;
     private String cnpj;
     private String nomeCedente;
     private Blob imLogoBanco;
     private String operacao;
     private BigDecimal nuUltArqRemessa;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set tipoContratos = new HashSet(0);
     private Set tituloses = new HashSet(0);
     private Set arquivoLiquidacaos = new HashSet(0);
     private Set cfgBancariaUnidades = new HashSet(0);
     private Set remessaBancarias = new HashSet(0);

    public ConvenioBancario() {
    }

	
    public ConvenioBancario(ConvenioBancarioId id, LayoutBancario layoutBancario, Empresa empresa, String bancoDv, String agenciaDv, String cedenteDv, long sequenciaMaxima, String nomeSequencia, String cnpj, String nomeCedente) {
        this.id = id;
        this.layoutBancario = layoutBancario;
        this.empresa = empresa;
        this.bancoDv = bancoDv;
        this.agenciaDv = agenciaDv;
        this.cedenteDv = cedenteDv;
        this.sequenciaMaxima = sequenciaMaxima;
        this.nomeSequencia = nomeSequencia;
        this.cnpj = cnpj;
        this.nomeCedente = nomeCedente;
    }
    public ConvenioBancario(ConvenioBancarioId id, LayoutBancario layoutBancario, Conta conta, Empresa empresa, String bancoDv, String agenciaDv, String cedenteDv, long sequenciaMaxima, String nomeSequencia, String cnpj, String nomeCedente, Blob imLogoBanco, String operacao, BigDecimal nuUltArqRemessa, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set tipoContratos, Set tituloses, Set arquivoLiquidacaos, Set cfgBancariaUnidades, Set remessaBancarias) {
       this.id = id;
       this.layoutBancario = layoutBancario;
       this.conta = conta;
       this.empresa = empresa;
       this.bancoDv = bancoDv;
       this.agenciaDv = agenciaDv;
       this.cedenteDv = cedenteDv;
       this.sequenciaMaxima = sequenciaMaxima;
       this.nomeSequencia = nomeSequencia;
       this.cnpj = cnpj;
       this.nomeCedente = nomeCedente;
       this.imLogoBanco = imLogoBanco;
       this.operacao = operacao;
       this.nuUltArqRemessa = nuUltArqRemessa;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.tipoContratos = tipoContratos;
       this.tituloses = tituloses;
       this.arquivoLiquidacaos = arquivoLiquidacaos;
       this.cfgBancariaUnidades = cfgBancariaUnidades;
       this.remessaBancarias = remessaBancarias;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="banco", column=@Column(name="BANCO", nullable=false, length=3) ), 
        @AttributeOverride(name="agencia", column=@Column(name="AGENCIA", nullable=false, length=5) ), 
        @AttributeOverride(name="cedente", column=@Column(name="CEDENTE", nullable=false, length=20) ), 
        @AttributeOverride(name="carteira", column=@Column(name="CARTEIRA", nullable=false, length=2) ), 
        @AttributeOverride(name="convenio", column=@Column(name="CONVENIO", nullable=false, length=10) ) } )
    public ConvenioBancarioId getId() {
        return this.id;
    }
    
    public void setId(ConvenioBancarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LAYBCO_ID", nullable=false)
    public LayoutBancario getLayoutBancario() {
        return this.layoutBancario;
    }
    
    public void setLayoutBancario(LayoutBancario layoutBancario) {
        this.layoutBancario = layoutBancario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CON_ID")
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="BANCO_DV", nullable=false, length=1)
    public String getBancoDv() {
        return this.bancoDv;
    }
    
    public void setBancoDv(String bancoDv) {
        this.bancoDv = bancoDv;
    }

    
    @Column(name="AGENCIA_DV", nullable=false, length=1)
    public String getAgenciaDv() {
        return this.agenciaDv;
    }
    
    public void setAgenciaDv(String agenciaDv) {
        this.agenciaDv = agenciaDv;
    }

    
    @Column(name="CEDENTE_DV", nullable=false, length=1)
    public String getCedenteDv() {
        return this.cedenteDv;
    }
    
    public void setCedenteDv(String cedenteDv) {
        this.cedenteDv = cedenteDv;
    }

    
    @Column(name="SEQUENCIA_MAXIMA", nullable=false, precision=17, scale=0)
    public long getSequenciaMaxima() {
        return this.sequenciaMaxima;
    }
    
    public void setSequenciaMaxima(long sequenciaMaxima) {
        this.sequenciaMaxima = sequenciaMaxima;
    }

    
    @Column(name="NOME_SEQUENCIA", nullable=false, length=30)
    public String getNomeSequencia() {
        return this.nomeSequencia;
    }
    
    public void setNomeSequencia(String nomeSequencia) {
        this.nomeSequencia = nomeSequencia;
    }

    
    @Column(name="CNPJ", nullable=false, length=15)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="NOME_CEDENTE", nullable=false, length=100)
    public String getNomeCedente() {
        return this.nomeCedente;
    }
    
    public void setNomeCedente(String nomeCedente) {
        this.nomeCedente = nomeCedente;
    }

    
    @Column(name="IM_LOGO_BANCO")
    public Blob getImLogoBanco() {
        return this.imLogoBanco;
    }
    
    public void setImLogoBanco(Blob imLogoBanco) {
        this.imLogoBanco = imLogoBanco;
    }

    
    @Column(name="OPERACAO", length=3)
    public String getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(String operacao) {
        this.operacao = operacao;
    }

    
    @Column(name="NU_ULT_ARQ_REMESSA", precision=22, scale=0)
    public BigDecimal getNuUltArqRemessa() {
        return this.nuUltArqRemessa;
    }
    
    public void setNuUltArqRemessa(BigDecimal nuUltArqRemessa) {
        this.nuUltArqRemessa = nuUltArqRemessa;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenioBancario")
    public Set getTipoContratos() {
        return this.tipoContratos;
    }
    
    public void setTipoContratos(Set tipoContratos) {
        this.tipoContratos = tipoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenioBancario")
    public Set getTituloses() {
        return this.tituloses;
    }
    
    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenioBancario")
    public Set getArquivoLiquidacaos() {
        return this.arquivoLiquidacaos;
    }
    
    public void setArquivoLiquidacaos(Set arquivoLiquidacaos) {
        this.arquivoLiquidacaos = arquivoLiquidacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenioBancario")
    public Set getCfgBancariaUnidades() {
        return this.cfgBancariaUnidades;
    }
    
    public void setCfgBancariaUnidades(Set cfgBancariaUnidades) {
        this.cfgBancariaUnidades = cfgBancariaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="convenioBancario")
    public Set getRemessaBancarias() {
        return this.remessaBancarias;
    }
    
    public void setRemessaBancarias(Set remessaBancarias) {
        this.remessaBancarias = remessaBancarias;
    }




}


