package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmbalagemItem generated by hbm2java
 */
@Entity
@Table(name="EMBALAGEM_ITEM"
    ,schema="DESENV"
)
public class EmbalagemItem  implements java.io.Serializable {


     private EmbalagemItemId id;
     private Item item;
     private UnidadeMedida unidadeMedida;
     private Empresa empresa;
     private BigDecimal quantidade;
     private String ativo;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set linhaNotaFiscals = new HashSet(0);
     private Set consumoItems = new HashSet(0);

    public EmbalagemItem() {
    }

	
    public EmbalagemItem(EmbalagemItemId id, Item item, UnidadeMedida unidadeMedida, Empresa empresa, BigDecimal quantidade, String ativo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.id = id;
        this.item = item;
        this.unidadeMedida = unidadeMedida;
        this.empresa = empresa;
        this.quantidade = quantidade;
        this.ativo = ativo;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public EmbalagemItem(EmbalagemItemId id, Item item, UnidadeMedida unidadeMedida, Empresa empresa, BigDecimal quantidade, String ativo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set linhaNotaFiscals, Set consumoItems) {
       this.id = id;
       this.item = item;
       this.unidadeMedida = unidadeMedida;
       this.empresa = empresa;
       this.quantidade = quantidade;
       this.ativo = ativo;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.linhaNotaFiscals = linhaNotaFiscals;
       this.consumoItems = consumoItems;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, precision=22, scale=0) ) } )
    public EmbalagemItemId getId() {
        return this.id;
    }
    
    public void setId(EmbalagemItemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_ID", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNIME_SIGLA", nullable=false)
    public UnidadeMedida getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(UnidadeMedida unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="QUANTIDADE", nullable=false, precision=22, scale=0)
    public BigDecimal getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(BigDecimal quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="ATIVO", nullable=false, length=1)
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="embalagemItem")
    public Set getLinhaNotaFiscals() {
        return this.linhaNotaFiscals;
    }
    
    public void setLinhaNotaFiscals(Set linhaNotaFiscals) {
        this.linhaNotaFiscals = linhaNotaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="embalagemItem")
    public Set getConsumoItems() {
        return this.consumoItems;
    }
    
    public void setConsumoItems(Set consumoItems) {
        this.consumoItems = consumoItems;
    }




}


