package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmbalagemMaterial generated by hbm2java
 */
@Entity
@Table(name="EMBALAGEM_MATERIAL"
    ,schema="DESENV"
)
public class EmbalagemMaterial  implements java.io.Serializable {


     private BigDecimal id;
     private Material material;
     private Empresa empresa;
     private String descricao;
     private BigDecimal quantidadeMaterial;
     private char flAtiva;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set embalagemPedidos = new HashSet(0);

    public EmbalagemMaterial() {
    }

	
    public EmbalagemMaterial(BigDecimal id, Material material, Empresa empresa, String descricao, BigDecimal quantidadeMaterial, char flAtiva) {
        this.id = id;
        this.material = material;
        this.empresa = empresa;
        this.descricao = descricao;
        this.quantidadeMaterial = quantidadeMaterial;
        this.flAtiva = flAtiva;
    }
    public EmbalagemMaterial(BigDecimal id, Material material, Empresa empresa, String descricao, BigDecimal quantidadeMaterial, char flAtiva, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set embalagemPedidos) {
       this.id = id;
       this.material = material;
       this.empresa = empresa;
       this.descricao = descricao;
       this.quantidadeMaterial = quantidadeMaterial;
       this.flAtiva = flAtiva;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.embalagemPedidos = embalagemPedidos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATERIAL_ID", nullable=false)
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="DESCRICAO", nullable=false, length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="QUANTIDADE_MATERIAL", nullable=false, precision=22, scale=0)
    public BigDecimal getQuantidadeMaterial() {
        return this.quantidadeMaterial;
    }
    
    public void setQuantidadeMaterial(BigDecimal quantidadeMaterial) {
        this.quantidadeMaterial = quantidadeMaterial;
    }

    
    @Column(name="FL_ATIVA", nullable=false, length=1)
    public char getFlAtiva() {
        return this.flAtiva;
    }
    
    public void setFlAtiva(char flAtiva) {
        this.flAtiva = flAtiva;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="embalagemMaterial")
    public Set getEmbalagemPedidos() {
        return this.embalagemPedidos;
    }
    
    public void setEmbalagemPedidos(Set embalagemPedidos) {
        this.embalagemPedidos = embalagemPedidos;
    }




}


