package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="EMPRESA"
    ,schema="DESENV"
)
public class Empresa  implements java.io.Serializable {


     private BigDecimal id;
     private String nome;
     private char ativo;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set procedimentoUnidades = new HashSet(0);
     private Set pagamentoPedidos = new HashSet(0);
     private Set unidades = new HashSet(0);
     private Set regiaoProcedimentos = new HashSet(0);
     private Set consumoMaterials = new HashSet(0);
     private Set motivoGlosas = new HashSet(0);
     private Set movimentacaoCheques = new HashSet(0);
     private Set orcamentos = new HashSet(0);
     private Set indiceAtualizacaos = new HashSet(0);
     private Set inventarios = new HashSet(0);
     private Set chequePagamentoPedidos = new HashSet(0);
     private Set procedimentoFormaPagamentos = new HashSet(0);
     private Set grupoProcedimentos = new HashSet(0);
     private Set comandoLayouts = new HashSet(0);
     private Set layoutBancarios = new HashSet(0);
     private Set movimentoCaixas = new HashSet(0);
     private Set listaRegiaoProcedimentos = new HashSet(0);
     private Set logAcessoTelas = new HashSet(0);
     private Set interessePacientes = new HashSet(0);
     private Set custoGeralMensals = new HashSet(0);
     private Set especialidadeProfissionals = new HashSet(0);
     private Set materialProcedimentos = new HashSet(0);
     private Set cobrancas = new HashSet(0);
     private Set parcelamentos = new HashSet(0);
     private Set pagamentoFechamentoConvs = new HashSet(0);
     private Set tipoAgendas = new HashSet(0);
     private Set tipoContratos = new HashSet(0);
     private Set convenioPacientes = new HashSet(0);
     private Set cfgBancariaUnidades = new HashSet(0);
     private Set convenioEspecialidades = new HashSet(0);
     private Set fornecedors = new HashSet(0);
     private Set portadorUsuarios = new HashSet(0);
     private Set consumoItems = new HashSet(0);
     private Set procedimentoPacientes = new HashSet(0);
     private Set documentoMensagemUnidades = new HashSet(0);
     private Set pagamentoPacientes = new HashSet(0);
     private Set procedimentoGrupos = new HashSet(0);
     private Set pagamentoFornecedors = new HashSet(0);
     private Set procedimentos = new HashSet(0);
     private Set repasseProfissionals = new HashSet(0);
     private Set programacaoPagamentoNfs = new HashSet(0);
     private Set fechamentoConvenios = new HashSet(0);
     private Set provisaoReceitas = new HashSet(0);
     private Set profissionals = new HashSet(0);
     private Set ageDetalhesExecucaos = new HashSet(0);
     private Set remessaBancarias = new HashSet(0);
     private Set inventarioItems = new HashSet(0);
     private Set items = new HashSet(0);
     private Set contratoCondicoeses = new HashSet(0);
     private Set ageParametrosAgendamentos = new HashSet(0);
     private Set tituloses = new HashSet(0);
     private Set movimentoTitulos = new HashSet(0);
     private Set materials = new HashSet(0);
     private Set composicaoPagamentoProfs = new HashSet(0);
     private Set ageProgAgendamentos = new HashSet(0);
     private Set planoContases = new HashSet(0);
     private Set tipoNotaFiscals = new HashSet(0);
     private Set consultorios = new HashSet(0);
     private Set meioPagamentos = new HashSet(0);
     private Set embalagemMaterials = new HashSet(0);
     private Set controleCaixas = new HashSet(0);
     private Set convenioBancarios = new HashSet(0);
     private Set guiaPacientes = new HashSet(0);
     private Set tabelaConvenios = new HashSet(0);
     private Set itemProcedimentos = new HashSet(0);
     private Set evolucaoPacientes = new HashSet(0);
     private Set portadors = new HashSet(0);
     private Set procedimentoContratos = new HashSet(0);
     private Set formaPagamentos = new HashSet(0);
     private Set horarioAberturaAgendas = new HashSet(0);
     private Set arquivoLiquidacaos = new HashSet(0);
     private Set bloqueioAgendas = new HashSet(0);
     private Set itemUnidades = new HashSet(0);
     private Set linhaNotaFiscals = new HashSet(0);
     private Set pagamentoNotaFiscals = new HashSet(0);
     private Set guiaFechamentos = new HashSet(0);
     private Set unidadeUsuarios = new HashSet(0);
     private Set balancoItems = new HashSet(0);
     private Set contaPagars = new HashSet(0);
     private Set ageAgendamentos = new HashSet(0);
     private Set horarioUnidades = new HashSet(0);
     private Set procedimentoGuiaFechamentos = new HashSet(0);
     private Set origemPacientes = new HashSet(0);
     private Set ageHitoricoProgAgends = new HashSet(0);
     private Set convenios = new HashSet(0);
     private Set valorIndiceAtualizacaos = new HashSet(0);
     private Set situacaoCheques = new HashSet(0);
     private Set categoriaProcedimentos = new HashSet(0);
     private Set contas = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set meioPagamentoContaUnidades = new HashSet(0);
     private Set pagamentoProfissionals = new HashSet(0);
     private Set usuarioUnidadeAgendas = new HashSet(0);
     private Set categoriaItems = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set pagamentoCobrancas = new HashSet(0);
     private Set grupoUsuarios = new HashSet(0);
     private Set procedimentoGuias = new HashSet(0);
     private Set especialidades = new HashSet(0);
     private Set linhasArquivoLiquidacaos = new HashSet(0);
     private Set notaFiscals = new HashSet(0);
     private Set cheques = new HashSet(0);
     private Set materialPedidos = new HashSet(0);
     private Set embalagemItems = new HashSet(0);
     private Set campoLayouts = new HashSet(0);
     private Set pedidoPagamentoPedidos = new HashSet(0);
     private Set tipoAgendaProfissionals = new HashSet(0);
     private Set aberturaAgendas = new HashSet(0);
     private Set pagamentosTituloses = new HashSet(0);
     private Set pacientes = new HashSet(0);
     private Set proximaSituacaoCheques = new HashSet(0);
     private Set contaOperadors = new HashSet(0);
     private Set agendas = new HashSet(0);
     private Set embalagemPedidos = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(BigDecimal id, String nome, char ativo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
        this.id = id;
        this.nome = nome;
        this.ativo = ativo;
        this.cdCriadoPor = cdCriadoPor;
        this.dtCriacao = dtCriacao;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public Empresa(BigDecimal id, String nome, char ativo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set procedimentoUnidades, Set pagamentoPedidos, Set unidades, Set regiaoProcedimentos, Set consumoMaterials, Set motivoGlosas, Set movimentacaoCheques, Set orcamentos, Set indiceAtualizacaos, Set inventarios, Set chequePagamentoPedidos, Set procedimentoFormaPagamentos, Set grupoProcedimentos, Set comandoLayouts, Set layoutBancarios, Set movimentoCaixas, Set listaRegiaoProcedimentos, Set logAcessoTelas, Set interessePacientes, Set custoGeralMensals, Set especialidadeProfissionals, Set materialProcedimentos, Set cobrancas, Set parcelamentos, Set pagamentoFechamentoConvs, Set tipoAgendas, Set tipoContratos, Set convenioPacientes, Set cfgBancariaUnidades, Set convenioEspecialidades, Set fornecedors, Set portadorUsuarios, Set consumoItems, Set procedimentoPacientes, Set documentoMensagemUnidades, Set pagamentoPacientes, Set procedimentoGrupos, Set pagamentoFornecedors, Set procedimentos, Set repasseProfissionals, Set programacaoPagamentoNfs, Set fechamentoConvenios, Set provisaoReceitas, Set profissionals, Set ageDetalhesExecucaos, Set remessaBancarias, Set inventarioItems, Set items, Set contratoCondicoeses, Set ageParametrosAgendamentos, Set tituloses, Set movimentoTitulos, Set materials, Set composicaoPagamentoProfs, Set ageProgAgendamentos, Set planoContases, Set tipoNotaFiscals, Set consultorios, Set meioPagamentos, Set embalagemMaterials, Set controleCaixas, Set convenioBancarios, Set guiaPacientes, Set tabelaConvenios, Set itemProcedimentos, Set evolucaoPacientes, Set portadors, Set procedimentoContratos, Set formaPagamentos, Set horarioAberturaAgendas, Set arquivoLiquidacaos, Set bloqueioAgendas, Set itemUnidades, Set linhaNotaFiscals, Set pagamentoNotaFiscals, Set guiaFechamentos, Set unidadeUsuarios, Set balancoItems, Set contaPagars, Set ageAgendamentos, Set horarioUnidades, Set procedimentoGuiaFechamentos, Set origemPacientes, Set ageHitoricoProgAgends, Set convenios, Set valorIndiceAtualizacaos, Set situacaoCheques, Set categoriaProcedimentos, Set contas, Set contratos, Set meioPagamentoContaUnidades, Set pagamentoProfissionals, Set usuarioUnidadeAgendas, Set categoriaItems, Set pedidos, Set pagamentoCobrancas, Set grupoUsuarios, Set procedimentoGuias, Set especialidades, Set linhasArquivoLiquidacaos, Set notaFiscals, Set cheques, Set materialPedidos, Set embalagemItems, Set campoLayouts, Set pedidoPagamentoPedidos, Set tipoAgendaProfissionals, Set aberturaAgendas, Set pagamentosTituloses, Set pacientes, Set proximaSituacaoCheques, Set contaOperadors, Set agendas, Set embalagemPedidos) {
       this.id = id;
       this.nome = nome;
       this.ativo = ativo;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.procedimentoUnidades = procedimentoUnidades;
       this.pagamentoPedidos = pagamentoPedidos;
       this.unidades = unidades;
       this.regiaoProcedimentos = regiaoProcedimentos;
       this.consumoMaterials = consumoMaterials;
       this.motivoGlosas = motivoGlosas;
       this.movimentacaoCheques = movimentacaoCheques;
       this.orcamentos = orcamentos;
       this.indiceAtualizacaos = indiceAtualizacaos;
       this.inventarios = inventarios;
       this.chequePagamentoPedidos = chequePagamentoPedidos;
       this.procedimentoFormaPagamentos = procedimentoFormaPagamentos;
       this.grupoProcedimentos = grupoProcedimentos;
       this.comandoLayouts = comandoLayouts;
       this.layoutBancarios = layoutBancarios;
       this.movimentoCaixas = movimentoCaixas;
       this.listaRegiaoProcedimentos = listaRegiaoProcedimentos;
       this.logAcessoTelas = logAcessoTelas;
       this.interessePacientes = interessePacientes;
       this.custoGeralMensals = custoGeralMensals;
       this.especialidadeProfissionals = especialidadeProfissionals;
       this.materialProcedimentos = materialProcedimentos;
       this.cobrancas = cobrancas;
       this.parcelamentos = parcelamentos;
       this.pagamentoFechamentoConvs = pagamentoFechamentoConvs;
       this.tipoAgendas = tipoAgendas;
       this.tipoContratos = tipoContratos;
       this.convenioPacientes = convenioPacientes;
       this.cfgBancariaUnidades = cfgBancariaUnidades;
       this.convenioEspecialidades = convenioEspecialidades;
       this.fornecedors = fornecedors;
       this.portadorUsuarios = portadorUsuarios;
       this.consumoItems = consumoItems;
       this.procedimentoPacientes = procedimentoPacientes;
       this.documentoMensagemUnidades = documentoMensagemUnidades;
       this.pagamentoPacientes = pagamentoPacientes;
       this.procedimentoGrupos = procedimentoGrupos;
       this.pagamentoFornecedors = pagamentoFornecedors;
       this.procedimentos = procedimentos;
       this.repasseProfissionals = repasseProfissionals;
       this.programacaoPagamentoNfs = programacaoPagamentoNfs;
       this.fechamentoConvenios = fechamentoConvenios;
       this.provisaoReceitas = provisaoReceitas;
       this.profissionals = profissionals;
       this.ageDetalhesExecucaos = ageDetalhesExecucaos;
       this.remessaBancarias = remessaBancarias;
       this.inventarioItems = inventarioItems;
       this.items = items;
       this.contratoCondicoeses = contratoCondicoeses;
       this.ageParametrosAgendamentos = ageParametrosAgendamentos;
       this.tituloses = tituloses;
       this.movimentoTitulos = movimentoTitulos;
       this.materials = materials;
       this.composicaoPagamentoProfs = composicaoPagamentoProfs;
       this.ageProgAgendamentos = ageProgAgendamentos;
       this.planoContases = planoContases;
       this.tipoNotaFiscals = tipoNotaFiscals;
       this.consultorios = consultorios;
       this.meioPagamentos = meioPagamentos;
       this.embalagemMaterials = embalagemMaterials;
       this.controleCaixas = controleCaixas;
       this.convenioBancarios = convenioBancarios;
       this.guiaPacientes = guiaPacientes;
       this.tabelaConvenios = tabelaConvenios;
       this.itemProcedimentos = itemProcedimentos;
       this.evolucaoPacientes = evolucaoPacientes;
       this.portadors = portadors;
       this.procedimentoContratos = procedimentoContratos;
       this.formaPagamentos = formaPagamentos;
       this.horarioAberturaAgendas = horarioAberturaAgendas;
       this.arquivoLiquidacaos = arquivoLiquidacaos;
       this.bloqueioAgendas = bloqueioAgendas;
       this.itemUnidades = itemUnidades;
       this.linhaNotaFiscals = linhaNotaFiscals;
       this.pagamentoNotaFiscals = pagamentoNotaFiscals;
       this.guiaFechamentos = guiaFechamentos;
       this.unidadeUsuarios = unidadeUsuarios;
       this.balancoItems = balancoItems;
       this.contaPagars = contaPagars;
       this.ageAgendamentos = ageAgendamentos;
       this.horarioUnidades = horarioUnidades;
       this.procedimentoGuiaFechamentos = procedimentoGuiaFechamentos;
       this.origemPacientes = origemPacientes;
       this.ageHitoricoProgAgends = ageHitoricoProgAgends;
       this.convenios = convenios;
       this.valorIndiceAtualizacaos = valorIndiceAtualizacaos;
       this.situacaoCheques = situacaoCheques;
       this.categoriaProcedimentos = categoriaProcedimentos;
       this.contas = contas;
       this.contratos = contratos;
       this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
       this.pagamentoProfissionals = pagamentoProfissionals;
       this.usuarioUnidadeAgendas = usuarioUnidadeAgendas;
       this.categoriaItems = categoriaItems;
       this.pedidos = pedidos;
       this.pagamentoCobrancas = pagamentoCobrancas;
       this.grupoUsuarios = grupoUsuarios;
       this.procedimentoGuias = procedimentoGuias;
       this.especialidades = especialidades;
       this.linhasArquivoLiquidacaos = linhasArquivoLiquidacaos;
       this.notaFiscals = notaFiscals;
       this.cheques = cheques;
       this.materialPedidos = materialPedidos;
       this.embalagemItems = embalagemItems;
       this.campoLayouts = campoLayouts;
       this.pedidoPagamentoPedidos = pedidoPagamentoPedidos;
       this.tipoAgendaProfissionals = tipoAgendaProfissionals;
       this.aberturaAgendas = aberturaAgendas;
       this.pagamentosTituloses = pagamentosTituloses;
       this.pacientes = pacientes;
       this.proximaSituacaoCheques = proximaSituacaoCheques;
       this.contaOperadors = contaOperadors;
       this.agendas = agendas;
       this.embalagemPedidos = embalagemPedidos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="NOME", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="ATIVO", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoUnidades() {
        return this.procedimentoUnidades;
    }
    
    public void setProcedimentoUnidades(Set procedimentoUnidades) {
        this.procedimentoUnidades = procedimentoUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoPedidos() {
        return this.pagamentoPedidos;
    }
    
    public void setPagamentoPedidos(Set pagamentoPedidos) {
        this.pagamentoPedidos = pagamentoPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Set unidades) {
        this.unidades = unidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getRegiaoProcedimentos() {
        return this.regiaoProcedimentos;
    }
    
    public void setRegiaoProcedimentos(Set regiaoProcedimentos) {
        this.regiaoProcedimentos = regiaoProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConsumoMaterials() {
        return this.consumoMaterials;
    }
    
    public void setConsumoMaterials(Set consumoMaterials) {
        this.consumoMaterials = consumoMaterials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMotivoGlosas() {
        return this.motivoGlosas;
    }
    
    public void setMotivoGlosas(Set motivoGlosas) {
        this.motivoGlosas = motivoGlosas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMovimentacaoCheques() {
        return this.movimentacaoCheques;
    }
    
    public void setMovimentacaoCheques(Set movimentacaoCheques) {
        this.movimentacaoCheques = movimentacaoCheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Set orcamentos) {
        this.orcamentos = orcamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getIndiceAtualizacaos() {
        return this.indiceAtualizacaos;
    }
    
    public void setIndiceAtualizacaos(Set indiceAtualizacaos) {
        this.indiceAtualizacaos = indiceAtualizacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getChequePagamentoPedidos() {
        return this.chequePagamentoPedidos;
    }
    
    public void setChequePagamentoPedidos(Set chequePagamentoPedidos) {
        this.chequePagamentoPedidos = chequePagamentoPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoFormaPagamentos() {
        return this.procedimentoFormaPagamentos;
    }
    
    public void setProcedimentoFormaPagamentos(Set procedimentoFormaPagamentos) {
        this.procedimentoFormaPagamentos = procedimentoFormaPagamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getGrupoProcedimentos() {
        return this.grupoProcedimentos;
    }
    
    public void setGrupoProcedimentos(Set grupoProcedimentos) {
        this.grupoProcedimentos = grupoProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getComandoLayouts() {
        return this.comandoLayouts;
    }
    
    public void setComandoLayouts(Set comandoLayouts) {
        this.comandoLayouts = comandoLayouts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getLayoutBancarios() {
        return this.layoutBancarios;
    }
    
    public void setLayoutBancarios(Set layoutBancarios) {
        this.layoutBancarios = layoutBancarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMovimentoCaixas() {
        return this.movimentoCaixas;
    }
    
    public void setMovimentoCaixas(Set movimentoCaixas) {
        this.movimentoCaixas = movimentoCaixas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getListaRegiaoProcedimentos() {
        return this.listaRegiaoProcedimentos;
    }
    
    public void setListaRegiaoProcedimentos(Set listaRegiaoProcedimentos) {
        this.listaRegiaoProcedimentos = listaRegiaoProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getLogAcessoTelas() {
        return this.logAcessoTelas;
    }
    
    public void setLogAcessoTelas(Set logAcessoTelas) {
        this.logAcessoTelas = logAcessoTelas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getInteressePacientes() {
        return this.interessePacientes;
    }
    
    public void setInteressePacientes(Set interessePacientes) {
        this.interessePacientes = interessePacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCustoGeralMensals() {
        return this.custoGeralMensals;
    }
    
    public void setCustoGeralMensals(Set custoGeralMensals) {
        this.custoGeralMensals = custoGeralMensals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEspecialidadeProfissionals() {
        return this.especialidadeProfissionals;
    }
    
    public void setEspecialidadeProfissionals(Set especialidadeProfissionals) {
        this.especialidadeProfissionals = especialidadeProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMaterialProcedimentos() {
        return this.materialProcedimentos;
    }
    
    public void setMaterialProcedimentos(Set materialProcedimentos) {
        this.materialProcedimentos = materialProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCobrancas() {
        return this.cobrancas;
    }
    
    public void setCobrancas(Set cobrancas) {
        this.cobrancas = cobrancas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getParcelamentos() {
        return this.parcelamentos;
    }
    
    public void setParcelamentos(Set parcelamentos) {
        this.parcelamentos = parcelamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoFechamentoConvs() {
        return this.pagamentoFechamentoConvs;
    }
    
    public void setPagamentoFechamentoConvs(Set pagamentoFechamentoConvs) {
        this.pagamentoFechamentoConvs = pagamentoFechamentoConvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getTipoAgendas() {
        return this.tipoAgendas;
    }
    
    public void setTipoAgendas(Set tipoAgendas) {
        this.tipoAgendas = tipoAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getTipoContratos() {
        return this.tipoContratos;
    }
    
    public void setTipoContratos(Set tipoContratos) {
        this.tipoContratos = tipoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConvenioPacientes() {
        return this.convenioPacientes;
    }
    
    public void setConvenioPacientes(Set convenioPacientes) {
        this.convenioPacientes = convenioPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCfgBancariaUnidades() {
        return this.cfgBancariaUnidades;
    }
    
    public void setCfgBancariaUnidades(Set cfgBancariaUnidades) {
        this.cfgBancariaUnidades = cfgBancariaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConvenioEspecialidades() {
        return this.convenioEspecialidades;
    }
    
    public void setConvenioEspecialidades(Set convenioEspecialidades) {
        this.convenioEspecialidades = convenioEspecialidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPortadorUsuarios() {
        return this.portadorUsuarios;
    }
    
    public void setPortadorUsuarios(Set portadorUsuarios) {
        this.portadorUsuarios = portadorUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConsumoItems() {
        return this.consumoItems;
    }
    
    public void setConsumoItems(Set consumoItems) {
        this.consumoItems = consumoItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoPacientes() {
        return this.procedimentoPacientes;
    }
    
    public void setProcedimentoPacientes(Set procedimentoPacientes) {
        this.procedimentoPacientes = procedimentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getDocumentoMensagemUnidades() {
        return this.documentoMensagemUnidades;
    }
    
    public void setDocumentoMensagemUnidades(Set documentoMensagemUnidades) {
        this.documentoMensagemUnidades = documentoMensagemUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoPacientes() {
        return this.pagamentoPacientes;
    }
    
    public void setPagamentoPacientes(Set pagamentoPacientes) {
        this.pagamentoPacientes = pagamentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoGrupos() {
        return this.procedimentoGrupos;
    }
    
    public void setProcedimentoGrupos(Set procedimentoGrupos) {
        this.procedimentoGrupos = procedimentoGrupos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoFornecedors() {
        return this.pagamentoFornecedors;
    }
    
    public void setPagamentoFornecedors(Set pagamentoFornecedors) {
        this.pagamentoFornecedors = pagamentoFornecedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentos() {
        return this.procedimentos;
    }
    
    public void setProcedimentos(Set procedimentos) {
        this.procedimentos = procedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getRepasseProfissionals() {
        return this.repasseProfissionals;
    }
    
    public void setRepasseProfissionals(Set repasseProfissionals) {
        this.repasseProfissionals = repasseProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProgramacaoPagamentoNfs() {
        return this.programacaoPagamentoNfs;
    }
    
    public void setProgramacaoPagamentoNfs(Set programacaoPagamentoNfs) {
        this.programacaoPagamentoNfs = programacaoPagamentoNfs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getFechamentoConvenios() {
        return this.fechamentoConvenios;
    }
    
    public void setFechamentoConvenios(Set fechamentoConvenios) {
        this.fechamentoConvenios = fechamentoConvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProvisaoReceitas() {
        return this.provisaoReceitas;
    }
    
    public void setProvisaoReceitas(Set provisaoReceitas) {
        this.provisaoReceitas = provisaoReceitas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProfissionals() {
        return this.profissionals;
    }
    
    public void setProfissionals(Set profissionals) {
        this.profissionals = profissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAgeDetalhesExecucaos() {
        return this.ageDetalhesExecucaos;
    }
    
    public void setAgeDetalhesExecucaos(Set ageDetalhesExecucaos) {
        this.ageDetalhesExecucaos = ageDetalhesExecucaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getRemessaBancarias() {
        return this.remessaBancarias;
    }
    
    public void setRemessaBancarias(Set remessaBancarias) {
        this.remessaBancarias = remessaBancarias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getInventarioItems() {
        return this.inventarioItems;
    }
    
    public void setInventarioItems(Set inventarioItems) {
        this.inventarioItems = inventarioItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getContratoCondicoeses() {
        return this.contratoCondicoeses;
    }
    
    public void setContratoCondicoeses(Set contratoCondicoeses) {
        this.contratoCondicoeses = contratoCondicoeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAgeParametrosAgendamentos() {
        return this.ageParametrosAgendamentos;
    }
    
    public void setAgeParametrosAgendamentos(Set ageParametrosAgendamentos) {
        this.ageParametrosAgendamentos = ageParametrosAgendamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getTituloses() {
        return this.tituloses;
    }
    
    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMovimentoTitulos() {
        return this.movimentoTitulos;
    }
    
    public void setMovimentoTitulos(Set movimentoTitulos) {
        this.movimentoTitulos = movimentoTitulos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Set materials) {
        this.materials = materials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getComposicaoPagamentoProfs() {
        return this.composicaoPagamentoProfs;
    }
    
    public void setComposicaoPagamentoProfs(Set composicaoPagamentoProfs) {
        this.composicaoPagamentoProfs = composicaoPagamentoProfs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAgeProgAgendamentos() {
        return this.ageProgAgendamentos;
    }
    
    public void setAgeProgAgendamentos(Set ageProgAgendamentos) {
        this.ageProgAgendamentos = ageProgAgendamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPlanoContases() {
        return this.planoContases;
    }
    
    public void setPlanoContases(Set planoContases) {
        this.planoContases = planoContases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getTipoNotaFiscals() {
        return this.tipoNotaFiscals;
    }
    
    public void setTipoNotaFiscals(Set tipoNotaFiscals) {
        this.tipoNotaFiscals = tipoNotaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConsultorios() {
        return this.consultorios;
    }
    
    public void setConsultorios(Set consultorios) {
        this.consultorios = consultorios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMeioPagamentos() {
        return this.meioPagamentos;
    }
    
    public void setMeioPagamentos(Set meioPagamentos) {
        this.meioPagamentos = meioPagamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEmbalagemMaterials() {
        return this.embalagemMaterials;
    }
    
    public void setEmbalagemMaterials(Set embalagemMaterials) {
        this.embalagemMaterials = embalagemMaterials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getControleCaixas() {
        return this.controleCaixas;
    }
    
    public void setControleCaixas(Set controleCaixas) {
        this.controleCaixas = controleCaixas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConvenioBancarios() {
        return this.convenioBancarios;
    }
    
    public void setConvenioBancarios(Set convenioBancarios) {
        this.convenioBancarios = convenioBancarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getGuiaPacientes() {
        return this.guiaPacientes;
    }
    
    public void setGuiaPacientes(Set guiaPacientes) {
        this.guiaPacientes = guiaPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getTabelaConvenios() {
        return this.tabelaConvenios;
    }
    
    public void setTabelaConvenios(Set tabelaConvenios) {
        this.tabelaConvenios = tabelaConvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getItemProcedimentos() {
        return this.itemProcedimentos;
    }
    
    public void setItemProcedimentos(Set itemProcedimentos) {
        this.itemProcedimentos = itemProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEvolucaoPacientes() {
        return this.evolucaoPacientes;
    }
    
    public void setEvolucaoPacientes(Set evolucaoPacientes) {
        this.evolucaoPacientes = evolucaoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPortadors() {
        return this.portadors;
    }
    
    public void setPortadors(Set portadors) {
        this.portadors = portadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoContratos() {
        return this.procedimentoContratos;
    }
    
    public void setProcedimentoContratos(Set procedimentoContratos) {
        this.procedimentoContratos = procedimentoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getFormaPagamentos() {
        return this.formaPagamentos;
    }
    
    public void setFormaPagamentos(Set formaPagamentos) {
        this.formaPagamentos = formaPagamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getHorarioAberturaAgendas() {
        return this.horarioAberturaAgendas;
    }
    
    public void setHorarioAberturaAgendas(Set horarioAberturaAgendas) {
        this.horarioAberturaAgendas = horarioAberturaAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getArquivoLiquidacaos() {
        return this.arquivoLiquidacaos;
    }
    
    public void setArquivoLiquidacaos(Set arquivoLiquidacaos) {
        this.arquivoLiquidacaos = arquivoLiquidacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getBloqueioAgendas() {
        return this.bloqueioAgendas;
    }
    
    public void setBloqueioAgendas(Set bloqueioAgendas) {
        this.bloqueioAgendas = bloqueioAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getItemUnidades() {
        return this.itemUnidades;
    }
    
    public void setItemUnidades(Set itemUnidades) {
        this.itemUnidades = itemUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getLinhaNotaFiscals() {
        return this.linhaNotaFiscals;
    }
    
    public void setLinhaNotaFiscals(Set linhaNotaFiscals) {
        this.linhaNotaFiscals = linhaNotaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoNotaFiscals() {
        return this.pagamentoNotaFiscals;
    }
    
    public void setPagamentoNotaFiscals(Set pagamentoNotaFiscals) {
        this.pagamentoNotaFiscals = pagamentoNotaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getGuiaFechamentos() {
        return this.guiaFechamentos;
    }
    
    public void setGuiaFechamentos(Set guiaFechamentos) {
        this.guiaFechamentos = guiaFechamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getUnidadeUsuarios() {
        return this.unidadeUsuarios;
    }
    
    public void setUnidadeUsuarios(Set unidadeUsuarios) {
        this.unidadeUsuarios = unidadeUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getBalancoItems() {
        return this.balancoItems;
    }
    
    public void setBalancoItems(Set balancoItems) {
        this.balancoItems = balancoItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getContaPagars() {
        return this.contaPagars;
    }
    
    public void setContaPagars(Set contaPagars) {
        this.contaPagars = contaPagars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAgeAgendamentos() {
        return this.ageAgendamentos;
    }
    
    public void setAgeAgendamentos(Set ageAgendamentos) {
        this.ageAgendamentos = ageAgendamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getHorarioUnidades() {
        return this.horarioUnidades;
    }
    
    public void setHorarioUnidades(Set horarioUnidades) {
        this.horarioUnidades = horarioUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoGuiaFechamentos() {
        return this.procedimentoGuiaFechamentos;
    }
    
    public void setProcedimentoGuiaFechamentos(Set procedimentoGuiaFechamentos) {
        this.procedimentoGuiaFechamentos = procedimentoGuiaFechamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getOrigemPacientes() {
        return this.origemPacientes;
    }
    
    public void setOrigemPacientes(Set origemPacientes) {
        this.origemPacientes = origemPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAgeHitoricoProgAgends() {
        return this.ageHitoricoProgAgends;
    }
    
    public void setAgeHitoricoProgAgends(Set ageHitoricoProgAgends) {
        this.ageHitoricoProgAgends = ageHitoricoProgAgends;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set convenios) {
        this.convenios = convenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getValorIndiceAtualizacaos() {
        return this.valorIndiceAtualizacaos;
    }
    
    public void setValorIndiceAtualizacaos(Set valorIndiceAtualizacaos) {
        this.valorIndiceAtualizacaos = valorIndiceAtualizacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getSituacaoCheques() {
        return this.situacaoCheques;
    }
    
    public void setSituacaoCheques(Set situacaoCheques) {
        this.situacaoCheques = situacaoCheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCategoriaProcedimentos() {
        return this.categoriaProcedimentos;
    }
    
    public void setCategoriaProcedimentos(Set categoriaProcedimentos) {
        this.categoriaProcedimentos = categoriaProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getContas() {
        return this.contas;
    }
    
    public void setContas(Set contas) {
        this.contas = contas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMeioPagamentoContaUnidades() {
        return this.meioPagamentoContaUnidades;
    }
    
    public void setMeioPagamentoContaUnidades(Set meioPagamentoContaUnidades) {
        this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoProfissionals() {
        return this.pagamentoProfissionals;
    }
    
    public void setPagamentoProfissionals(Set pagamentoProfissionals) {
        this.pagamentoProfissionals = pagamentoProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getUsuarioUnidadeAgendas() {
        return this.usuarioUnidadeAgendas;
    }
    
    public void setUsuarioUnidadeAgendas(Set usuarioUnidadeAgendas) {
        this.usuarioUnidadeAgendas = usuarioUnidadeAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCategoriaItems() {
        return this.categoriaItems;
    }
    
    public void setCategoriaItems(Set categoriaItems) {
        this.categoriaItems = categoriaItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentoCobrancas() {
        return this.pagamentoCobrancas;
    }
    
    public void setPagamentoCobrancas(Set pagamentoCobrancas) {
        this.pagamentoCobrancas = pagamentoCobrancas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getGrupoUsuarios() {
        return this.grupoUsuarios;
    }
    
    public void setGrupoUsuarios(Set grupoUsuarios) {
        this.grupoUsuarios = grupoUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProcedimentoGuias() {
        return this.procedimentoGuias;
    }
    
    public void setProcedimentoGuias(Set procedimentoGuias) {
        this.procedimentoGuias = procedimentoGuias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Set especialidades) {
        this.especialidades = especialidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getLinhasArquivoLiquidacaos() {
        return this.linhasArquivoLiquidacaos;
    }
    
    public void setLinhasArquivoLiquidacaos(Set linhasArquivoLiquidacaos) {
        this.linhasArquivoLiquidacaos = linhasArquivoLiquidacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getNotaFiscals() {
        return this.notaFiscals;
    }
    
    public void setNotaFiscals(Set notaFiscals) {
        this.notaFiscals = notaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getMaterialPedidos() {
        return this.materialPedidos;
    }
    
    public void setMaterialPedidos(Set materialPedidos) {
        this.materialPedidos = materialPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEmbalagemItems() {
        return this.embalagemItems;
    }
    
    public void setEmbalagemItems(Set embalagemItems) {
        this.embalagemItems = embalagemItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getCampoLayouts() {
        return this.campoLayouts;
    }
    
    public void setCampoLayouts(Set campoLayouts) {
        this.campoLayouts = campoLayouts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPedidoPagamentoPedidos() {
        return this.pedidoPagamentoPedidos;
    }
    
    public void setPedidoPagamentoPedidos(Set pedidoPagamentoPedidos) {
        this.pedidoPagamentoPedidos = pedidoPagamentoPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getTipoAgendaProfissionals() {
        return this.tipoAgendaProfissionals;
    }
    
    public void setTipoAgendaProfissionals(Set tipoAgendaProfissionals) {
        this.tipoAgendaProfissionals = tipoAgendaProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAberturaAgendas() {
        return this.aberturaAgendas;
    }
    
    public void setAberturaAgendas(Set aberturaAgendas) {
        this.aberturaAgendas = aberturaAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPagamentosTituloses() {
        return this.pagamentosTituloses;
    }
    
    public void setPagamentosTituloses(Set pagamentosTituloses) {
        this.pagamentosTituloses = pagamentosTituloses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getProximaSituacaoCheques() {
        return this.proximaSituacaoCheques;
    }
    
    public void setProximaSituacaoCheques(Set proximaSituacaoCheques) {
        this.proximaSituacaoCheques = proximaSituacaoCheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getContaOperadors() {
        return this.contaOperadors;
    }
    
    public void setContaOperadors(Set contaOperadors) {
        this.contaOperadors = contaOperadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEmbalagemPedidos() {
        return this.embalagemPedidos;
    }
    
    public void setEmbalagemPedidos(Set embalagemPedidos) {
        this.embalagemPedidos = embalagemPedidos;
    }




}


