package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FechamentoConvenio generated by hbm2java
 */
@Entity
@Table(name="FECHAMENTO_CONVENIO"
    ,schema="DESENV"
)
public class FechamentoConvenio  implements java.io.Serializable {


     private BigDecimal id;
     private Convenio convenio;
     private Unidade unidade;
     private Empresa empresa;
     private Date dtFechamento;
     private BigDecimal valorPago;
     private BigDecimal valorGlosa;
     private BigDecimal valorImposto;
     private BigDecimal valorLiquido;
     private Date dtInicial;
     private Date dtFinal;
     private String descricao;
     private String flFechado;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set movimentoCaixas = new HashSet(0);
     private Set guiaFechamentos = new HashSet(0);
     private Set pagamentoFechamentoConvs = new HashSet(0);

    public FechamentoConvenio() {
    }

	
    public FechamentoConvenio(BigDecimal id, Convenio convenio, Unidade unidade, Empresa empresa, Date dtFechamento, BigDecimal valorImposto, BigDecimal valorLiquido, Date dtInicial, Date dtFinal, String descricao, String flFechado) {
        this.id = id;
        this.convenio = convenio;
        this.unidade = unidade;
        this.empresa = empresa;
        this.dtFechamento = dtFechamento;
        this.valorImposto = valorImposto;
        this.valorLiquido = valorLiquido;
        this.dtInicial = dtInicial;
        this.dtFinal = dtFinal;
        this.descricao = descricao;
        this.flFechado = flFechado;
    }
    public FechamentoConvenio(BigDecimal id, Convenio convenio, Unidade unidade, Empresa empresa, Date dtFechamento, BigDecimal valorPago, BigDecimal valorGlosa, BigDecimal valorImposto, BigDecimal valorLiquido, Date dtInicial, Date dtFinal, String descricao, String flFechado, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set movimentoCaixas, Set guiaFechamentos, Set pagamentoFechamentoConvs) {
       this.id = id;
       this.convenio = convenio;
       this.unidade = unidade;
       this.empresa = empresa;
       this.dtFechamento = dtFechamento;
       this.valorPago = valorPago;
       this.valorGlosa = valorGlosa;
       this.valorImposto = valorImposto;
       this.valorLiquido = valorLiquido;
       this.dtInicial = dtInicial;
       this.dtFinal = dtFinal;
       this.descricao = descricao;
       this.flFechado = flFechado;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.movimentoCaixas = movimentoCaixas;
       this.guiaFechamentos = guiaFechamentos;
       this.pagamentoFechamentoConvs = pagamentoFechamentoConvs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_ID", referencedColumnName="ID", nullable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false) } )
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FECHAMENTO", nullable=false, length=7)
    public Date getDtFechamento() {
        return this.dtFechamento;
    }
    
    public void setDtFechamento(Date dtFechamento) {
        this.dtFechamento = dtFechamento;
    }

    
    @Column(name="VALOR_PAGO", precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VALOR_GLOSA", precision=15)
    public BigDecimal getValorGlosa() {
        return this.valorGlosa;
    }
    
    public void setValorGlosa(BigDecimal valorGlosa) {
        this.valorGlosa = valorGlosa;
    }

    
    @Column(name="VALOR_IMPOSTO", nullable=false, precision=15)
    public BigDecimal getValorImposto() {
        return this.valorImposto;
    }
    
    public void setValorImposto(BigDecimal valorImposto) {
        this.valorImposto = valorImposto;
    }

    
    @Column(name="VALOR_LIQUIDO", nullable=false, precision=15)
    public BigDecimal getValorLiquido() {
        return this.valorLiquido;
    }
    
    public void setValorLiquido(BigDecimal valorLiquido) {
        this.valorLiquido = valorLiquido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_INICIAL", nullable=false, length=7)
    public Date getDtInicial() {
        return this.dtInicial;
    }
    
    public void setDtInicial(Date dtInicial) {
        this.dtInicial = dtInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_FINAL", nullable=false, length=7)
    public Date getDtFinal() {
        return this.dtFinal;
    }
    
    public void setDtFinal(Date dtFinal) {
        this.dtFinal = dtFinal;
    }

    
    @Column(name="DESCRICAO", nullable=false, length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="FL_FECHADO", nullable=false, length=1)
    public String getFlFechado() {
        return this.flFechado;
    }
    
    public void setFlFechado(String flFechado) {
        this.flFechado = flFechado;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fechamentoConvenio")
    public Set getMovimentoCaixas() {
        return this.movimentoCaixas;
    }
    
    public void setMovimentoCaixas(Set movimentoCaixas) {
        this.movimentoCaixas = movimentoCaixas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fechamentoConvenio")
    public Set getGuiaFechamentos() {
        return this.guiaFechamentos;
    }
    
    public void setGuiaFechamentos(Set guiaFechamentos) {
        this.guiaFechamentos = guiaFechamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fechamentoConvenio")
    public Set getPagamentoFechamentoConvs() {
        return this.pagamentoFechamentoConvs;
    }
    
    public void setPagamentoFechamentoConvs(Set pagamentoFechamentoConvs) {
        this.pagamentoFechamentoConvs = pagamentoFechamentoConvs;
    }




}


