package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name="FORMA_PAGAMENTO"
    ,schema="DESENV"
)
public class FormaPagamento  implements java.io.Serializable {


     private BigDecimal id;
     private Paciente paciente;
     private Empresa empresa;
     private Date dtAcordo;
     private String observacoes;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set procedimentoFormaPagamentos = new HashSet(0);
     private Set parcelamentos = new HashSet(0);

    public FormaPagamento() {
    }

	
    public FormaPagamento(BigDecimal id, Paciente paciente, Empresa empresa, Date dtAcordo) {
        this.id = id;
        this.paciente = paciente;
        this.empresa = empresa;
        this.dtAcordo = dtAcordo;
    }
    public FormaPagamento(BigDecimal id, Paciente paciente, Empresa empresa, Date dtAcordo, String observacoes, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set procedimentoFormaPagamentos, Set parcelamentos) {
       this.id = id;
       this.paciente = paciente;
       this.empresa = empresa;
       this.dtAcordo = dtAcordo;
       this.observacoes = observacoes;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.procedimentoFormaPagamentos = procedimentoFormaPagamentos;
       this.parcelamentos = parcelamentos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ACORDO", nullable=false, length=7)
    public Date getDtAcordo() {
        return this.dtAcordo;
    }
    
    public void setDtAcordo(Date dtAcordo) {
        this.dtAcordo = dtAcordo;
    }

    
    @Column(name="OBSERVACOES", length=4000)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPagamento")
    public Set getProcedimentoFormaPagamentos() {
        return this.procedimentoFormaPagamentos;
    }
    
    public void setProcedimentoFormaPagamentos(Set procedimentoFormaPagamentos) {
        this.procedimentoFormaPagamentos = procedimentoFormaPagamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPagamento")
    public Set getParcelamentos() {
        return this.parcelamentos;
    }
    
    public void setParcelamentos(Set parcelamentos) {
        this.parcelamentos = parcelamentos;
    }




}


