package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="FORNECEDOR"
    ,schema="DESENV"
)
public class Fornecedor  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private String nome;
     private String telefones;
     private String email;
     private String endereco;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private String flTipoPessoa;
     private String cpfCnpj;
     private String flAtivo;
     private String flInterno;
     private Set contaPagars = new HashSet(0);
     private Set pagamentoPedidos = new HashSet(0);
     private Set pagamentoFornecedors = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set movimentacaoCheques = new HashSet(0);
     private Set notaFiscals = new HashSet(0);
     private Set orcamentos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(BigDecimal id, Empresa empresa, String nome, String flTipoPessoa, String flAtivo, String flInterno) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.flTipoPessoa = flTipoPessoa;
        this.flAtivo = flAtivo;
        this.flInterno = flInterno;
    }
    public Fornecedor(BigDecimal id, Empresa empresa, String nome, String telefones, String email, String endereco, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, String flTipoPessoa, String cpfCnpj, String flAtivo, String flInterno, Set contaPagars, Set pagamentoPedidos, Set pagamentoFornecedors, Set pedidos, Set movimentacaoCheques, Set notaFiscals, Set orcamentos) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.telefones = telefones;
       this.email = email;
       this.endereco = endereco;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flTipoPessoa = flTipoPessoa;
       this.cpfCnpj = cpfCnpj;
       this.flAtivo = flAtivo;
       this.flInterno = flInterno;
       this.contaPagars = contaPagars;
       this.pagamentoPedidos = pagamentoPedidos;
       this.pagamentoFornecedors = pagamentoFornecedors;
       this.pedidos = pedidos;
       this.movimentacaoCheques = movimentacaoCheques;
       this.notaFiscals = notaFiscals;
       this.orcamentos = orcamentos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="TELEFONES", length=80)
    public String getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(String telefones) {
        this.telefones = telefones;
    }

    
    @Column(name="EMAIL", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ENDERECO", length=200)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_TIPO_PESSOA", nullable=false, length=1)
    public String getFlTipoPessoa() {
        return this.flTipoPessoa;
    }
    
    public void setFlTipoPessoa(String flTipoPessoa) {
        this.flTipoPessoa = flTipoPessoa;
    }

    
    @Column(name="CPF_CNPJ", length=14)
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="FL_INTERNO", nullable=false, length=1)
    public String getFlInterno() {
        return this.flInterno;
    }
    
    public void setFlInterno(String flInterno) {
        this.flInterno = flInterno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getContaPagars() {
        return this.contaPagars;
    }
    
    public void setContaPagars(Set contaPagars) {
        this.contaPagars = contaPagars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getPagamentoPedidos() {
        return this.pagamentoPedidos;
    }
    
    public void setPagamentoPedidos(Set pagamentoPedidos) {
        this.pagamentoPedidos = pagamentoPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getPagamentoFornecedors() {
        return this.pagamentoFornecedors;
    }
    
    public void setPagamentoFornecedors(Set pagamentoFornecedors) {
        this.pagamentoFornecedors = pagamentoFornecedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getMovimentacaoCheques() {
        return this.movimentacaoCheques;
    }
    
    public void setMovimentacaoCheques(Set movimentacaoCheques) {
        this.movimentacaoCheques = movimentacaoCheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getNotaFiscals() {
        return this.notaFiscals;
    }
    
    public void setNotaFiscals(Set notaFiscals) {
        this.notaFiscals = notaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Set orcamentos) {
        this.orcamentos = orcamentos;
    }




}


