package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * GrupoUsuario generated by hbm2java
 */
@Entity
@Table(name="GRUPO_USUARIO"
    ,schema="DESENV"
    , uniqueConstraints = @UniqueConstraint(columnNames="NM_USUARIO") 
)
public class GrupoUsuario  implements java.io.Serializable {


     private BigDecimal cdUsuario;
     private Empresa empresa;
     private String nmUsuario;
     private String nmUsuarioCompleto;
     private String flAtivo;
     private String dsSenha;
     private String flGrupoUsuario;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set processoGrupoUsuarios = new HashSet(0);
     private Set usuGrupoProgs = new HashSet(0);
     private Set grupoUsuarioGruposForGrusCdUsuario = new HashSet(0);
     private Set portadors = new HashSet(0);
     private Set usuGrupoTelaRelGras = new HashSet(0);
     private Set usuarioUnidadeAgendas = new HashSet(0);
     private Set contaOperadors = new HashSet(0);
     private Set logAcessoTelas = new HashSet(0);
     private Set portadorUsuarios = new HashSet(0);
     private Set unidadeUsuarios = new HashSet(0);
     private Set grupoUsuarioGruposForGrusCdUsuarioGrupo = new HashSet(0);
     private Set menuGrupoUsuarios = new HashSet(0);

    public GrupoUsuario() {
    }

	
    public GrupoUsuario(BigDecimal cdUsuario, Empresa empresa, String nmUsuario, String nmUsuarioCompleto, String flAtivo, String flGrupoUsuario, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdUsuario = cdUsuario;
        this.empresa = empresa;
        this.nmUsuario = nmUsuario;
        this.nmUsuarioCompleto = nmUsuarioCompleto;
        this.flAtivo = flAtivo;
        this.flGrupoUsuario = flGrupoUsuario;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public GrupoUsuario(BigDecimal cdUsuario, Empresa empresa, String nmUsuario, String nmUsuarioCompleto, String flAtivo, String dsSenha, String flGrupoUsuario, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set processoGrupoUsuarios, Set usuGrupoProgs, Set grupoUsuarioGruposForGrusCdUsuario, Set portadors, Set usuGrupoTelaRelGras, Set usuarioUnidadeAgendas, Set contaOperadors, Set logAcessoTelas, Set portadorUsuarios, Set unidadeUsuarios, Set grupoUsuarioGruposForGrusCdUsuarioGrupo, Set menuGrupoUsuarios) {
       this.cdUsuario = cdUsuario;
       this.empresa = empresa;
       this.nmUsuario = nmUsuario;
       this.nmUsuarioCompleto = nmUsuarioCompleto;
       this.flAtivo = flAtivo;
       this.dsSenha = dsSenha;
       this.flGrupoUsuario = flGrupoUsuario;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.processoGrupoUsuarios = processoGrupoUsuarios;
       this.usuGrupoProgs = usuGrupoProgs;
       this.grupoUsuarioGruposForGrusCdUsuario = grupoUsuarioGruposForGrusCdUsuario;
       this.portadors = portadors;
       this.usuGrupoTelaRelGras = usuGrupoTelaRelGras;
       this.usuarioUnidadeAgendas = usuarioUnidadeAgendas;
       this.contaOperadors = contaOperadors;
       this.logAcessoTelas = logAcessoTelas;
       this.portadorUsuarios = portadorUsuarios;
       this.unidadeUsuarios = unidadeUsuarios;
       this.grupoUsuarioGruposForGrusCdUsuarioGrupo = grupoUsuarioGruposForGrusCdUsuarioGrupo;
       this.menuGrupoUsuarios = menuGrupoUsuarios;
    }
   
     @Id 

    
    @Column(name="CD_USUARIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdUsuario() {
        return this.cdUsuario;
    }
    
    public void setCdUsuario(BigDecimal cdUsuario) {
        this.cdUsuario = cdUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NM_USUARIO", unique=true, nullable=false, length=15)
    public String getNmUsuario() {
        return this.nmUsuario;
    }
    
    public void setNmUsuario(String nmUsuario) {
        this.nmUsuario = nmUsuario;
    }

    
    @Column(name="NM_USUARIO_COMPLETO", nullable=false, length=80)
    public String getNmUsuarioCompleto() {
        return this.nmUsuarioCompleto;
    }
    
    public void setNmUsuarioCompleto(String nmUsuarioCompleto) {
        this.nmUsuarioCompleto = nmUsuarioCompleto;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="DS_SENHA", length=200)
    public String getDsSenha() {
        return this.dsSenha;
    }
    
    public void setDsSenha(String dsSenha) {
        this.dsSenha = dsSenha;
    }

    
    @Column(name="FL_GRUPO_USUARIO", nullable=false, length=1)
    public String getFlGrupoUsuario() {
        return this.flGrupoUsuario;
    }
    
    public void setFlGrupoUsuario(String flGrupoUsuario) {
        this.flGrupoUsuario = flGrupoUsuario;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getProcessoGrupoUsuarios() {
        return this.processoGrupoUsuarios;
    }
    
    public void setProcessoGrupoUsuarios(Set processoGrupoUsuarios) {
        this.processoGrupoUsuarios = processoGrupoUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getUsuGrupoProgs() {
        return this.usuGrupoProgs;
    }
    
    public void setUsuGrupoProgs(Set usuGrupoProgs) {
        this.usuGrupoProgs = usuGrupoProgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuarioByGrusCdUsuario")
    public Set getGrupoUsuarioGruposForGrusCdUsuario() {
        return this.grupoUsuarioGruposForGrusCdUsuario;
    }
    
    public void setGrupoUsuarioGruposForGrusCdUsuario(Set grupoUsuarioGruposForGrusCdUsuario) {
        this.grupoUsuarioGruposForGrusCdUsuario = grupoUsuarioGruposForGrusCdUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getPortadors() {
        return this.portadors;
    }
    
    public void setPortadors(Set portadors) {
        this.portadors = portadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getUsuGrupoTelaRelGras() {
        return this.usuGrupoTelaRelGras;
    }
    
    public void setUsuGrupoTelaRelGras(Set usuGrupoTelaRelGras) {
        this.usuGrupoTelaRelGras = usuGrupoTelaRelGras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getUsuarioUnidadeAgendas() {
        return this.usuarioUnidadeAgendas;
    }
    
    public void setUsuarioUnidadeAgendas(Set usuarioUnidadeAgendas) {
        this.usuarioUnidadeAgendas = usuarioUnidadeAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getContaOperadors() {
        return this.contaOperadors;
    }
    
    public void setContaOperadors(Set contaOperadors) {
        this.contaOperadors = contaOperadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getLogAcessoTelas() {
        return this.logAcessoTelas;
    }
    
    public void setLogAcessoTelas(Set logAcessoTelas) {
        this.logAcessoTelas = logAcessoTelas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getPortadorUsuarios() {
        return this.portadorUsuarios;
    }
    
    public void setPortadorUsuarios(Set portadorUsuarios) {
        this.portadorUsuarios = portadorUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getUnidadeUsuarios() {
        return this.unidadeUsuarios;
    }
    
    public void setUnidadeUsuarios(Set unidadeUsuarios) {
        this.unidadeUsuarios = unidadeUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuarioByGrusCdUsuarioGrupo")
    public Set getGrupoUsuarioGruposForGrusCdUsuarioGrupo() {
        return this.grupoUsuarioGruposForGrusCdUsuarioGrupo;
    }
    
    public void setGrupoUsuarioGruposForGrusCdUsuarioGrupo(Set grupoUsuarioGruposForGrusCdUsuarioGrupo) {
        this.grupoUsuarioGruposForGrusCdUsuarioGrupo = grupoUsuarioGruposForGrusCdUsuarioGrupo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoUsuario")
    public Set getMenuGrupoUsuarios() {
        return this.menuGrupoUsuarios;
    }
    
    public void setMenuGrupoUsuarios(Set menuGrupoUsuarios) {
        this.menuGrupoUsuarios = menuGrupoUsuarios;
    }




}


