package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrupoProcedimento generated by hbm2java
 */
@Entity
@Table(name="GRUPO_PROCEDIMENTO"
    ,schema="DESENV"
)
public class GrupoProcedimento  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private String nome;
     private String flAtivo;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set procedimentoGrupos = new HashSet(0);

    public GrupoProcedimento() {
    }

	
    public GrupoProcedimento(BigDecimal id, Empresa empresa, String nome, String flAtivo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.flAtivo = flAtivo;
        this.cdCriadoPor = cdCriadoPor;
        this.dtCriacao = dtCriacao;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public GrupoProcedimento(BigDecimal id, Empresa empresa, String nome, String flAtivo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set procedimentoGrupos) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.flAtivo = flAtivo;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.procedimentoGrupos = procedimentoGrupos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupoProcedimento")
    public Set getProcedimentoGrupos() {
        return this.procedimentoGrupos;
    }
    
    public void setProcedimentoGrupos(Set procedimentoGrupos) {
        this.procedimentoGrupos = procedimentoGrupos;
    }




}


