package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrupoUsuarioGrupo generated by hbm2java
 */
@Entity
@Table(name="GRUPO_USUARIO_GRUPO"
    ,schema="DESENV"
)
public class GrupoUsuarioGrupo  implements java.io.Serializable {


     private GrupoUsuarioGrupoId id;
     private GrupoUsuario grupoUsuarioByGrusCdUsuario;
     private GrupoUsuario grupoUsuarioByGrusCdUsuarioGrupo;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;

    public GrupoUsuarioGrupo() {
    }

    public GrupoUsuarioGrupo(GrupoUsuarioGrupoId id, GrupoUsuario grupoUsuarioByGrusCdUsuario, GrupoUsuario grupoUsuarioByGrusCdUsuarioGrupo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
       this.id = id;
       this.grupoUsuarioByGrusCdUsuario = grupoUsuarioByGrusCdUsuario;
       this.grupoUsuarioByGrusCdUsuarioGrupo = grupoUsuarioByGrusCdUsuarioGrupo;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="grusCdUsuario", column=@Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="grusCdUsuarioGrupo", column=@Column(name="GRUS_CD_USUARIO_GRUPO", nullable=false, precision=22, scale=0) ) } )
    public GrupoUsuarioGrupoId getId() {
        return this.id;
    }
    
    public void setId(GrupoUsuarioGrupoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUS_CD_USUARIO", nullable=false, insertable=false, updatable=false)
    public GrupoUsuario getGrupoUsuarioByGrusCdUsuario() {
        return this.grupoUsuarioByGrusCdUsuario;
    }
    
    public void setGrupoUsuarioByGrusCdUsuario(GrupoUsuario grupoUsuarioByGrusCdUsuario) {
        this.grupoUsuarioByGrusCdUsuario = grupoUsuarioByGrusCdUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUS_CD_USUARIO_GRUPO", nullable=false, insertable=false, updatable=false)
    public GrupoUsuario getGrupoUsuarioByGrusCdUsuarioGrupo() {
        return this.grupoUsuarioByGrusCdUsuarioGrupo;
    }
    
    public void setGrupoUsuarioByGrusCdUsuarioGrupo(GrupoUsuario grupoUsuarioByGrusCdUsuarioGrupo) {
        this.grupoUsuarioByGrusCdUsuarioGrupo = grupoUsuarioByGrusCdUsuarioGrupo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


