package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * GuiaPaciente generated by hbm2java
 */
@Entity
@Table(name="GUIA_PACIENTE"
    ,schema="DESENV"
    , uniqueConstraints = @UniqueConstraint(columnNames={"CODIGO", "CONPA_CONV_ID"}) 
)
public class GuiaPaciente  implements java.io.Serializable {


     private BigDecimal id;
     private ConvenioPaciente convenioPaciente;
     private Especialidade especialidade;
     private GuiaPaciente guiaPaciente;
     private Paciente paciente;
     private Profissional profissional;
     private Unidade unidade;
     private Empresa empresa;
     private String codigo;
     private Date dtGuia;
     private BigDecimal valorRepasse;
     private BigDecimal valorCoparticipacao;
     private BigDecimal vlReceberProfissional;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal vlTributacao;
     private GuiaFechamento guiaFechamento;
     private Set procedimentoGuias = new HashSet(0);
     private Set composicaoPagamentoProfs = new HashSet(0);
     private Set guiaPacientes = new HashSet(0);

    public GuiaPaciente() {
    }

	
    public GuiaPaciente(BigDecimal id, ConvenioPaciente convenioPaciente, Especialidade especialidade, Paciente paciente, Profissional profissional, Unidade unidade, Empresa empresa, String codigo, Date dtGuia, BigDecimal valorRepasse, BigDecimal valorCoparticipacao, BigDecimal vlTributacao) {
        this.id = id;
        this.convenioPaciente = convenioPaciente;
        this.especialidade = especialidade;
        this.paciente = paciente;
        this.profissional = profissional;
        this.unidade = unidade;
        this.empresa = empresa;
        this.codigo = codigo;
        this.dtGuia = dtGuia;
        this.valorRepasse = valorRepasse;
        this.valorCoparticipacao = valorCoparticipacao;
        this.vlTributacao = vlTributacao;
    }
    public GuiaPaciente(BigDecimal id, ConvenioPaciente convenioPaciente, Especialidade especialidade, GuiaPaciente guiaPaciente, Paciente paciente, Profissional profissional, Unidade unidade, Empresa empresa, String codigo, Date dtGuia, BigDecimal valorRepasse, BigDecimal valorCoparticipacao, BigDecimal vlReceberProfissional, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal vlTributacao, GuiaFechamento guiaFechamento, Set procedimentoGuias, Set composicaoPagamentoProfs, Set guiaPacientes) {
       this.id = id;
       this.convenioPaciente = convenioPaciente;
       this.especialidade = especialidade;
       this.guiaPaciente = guiaPaciente;
       this.paciente = paciente;
       this.profissional = profissional;
       this.unidade = unidade;
       this.empresa = empresa;
       this.codigo = codigo;
       this.dtGuia = dtGuia;
       this.valorRepasse = valorRepasse;
       this.valorCoparticipacao = valorCoparticipacao;
       this.vlReceberProfissional = vlReceberProfissional;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.vlTributacao = vlTributacao;
       this.guiaFechamento = guiaFechamento;
       this.procedimentoGuias = procedimentoGuias;
       this.composicaoPagamentoProfs = composicaoPagamentoProfs;
       this.guiaPacientes = guiaPacientes;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="PACIENTE_ID", referencedColumnName="PACIENTE_ID", nullable=false), 
        @JoinColumn(name="CONPA_CONV_ID", referencedColumnName="CONV_ID", nullable=false) } )
    public ConvenioPaciente getConvenioPaciente() {
        return this.convenioPaciente;
    }
    
    public void setConvenioPaciente(ConvenioPaciente convenioPaciente) {
        this.convenioPaciente = convenioPaciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ESP_ID", referencedColumnName="ID", nullable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false) } )
    public Especialidade getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(Especialidade especialidade) {
        this.especialidade = especialidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GUIA_ID")
    public GuiaPaciente getGuiaPaciente() {
        return this.guiaPaciente;
    }
    
    public void setGuiaPaciente(GuiaPaciente guiaPaciente) {
        this.guiaPaciente = guiaPaciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PACIENTE_ID", nullable=false, insertable=false, updatable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROFISSIONAL_ID", nullable=false)
    public Profissional getProfissional() {
        return this.profissional;
    }
    
    public void setProfissional(Profissional profissional) {
        this.profissional = profissional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="CODIGO", nullable=false, length=30)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_GUIA", nullable=false, length=7)
    public Date getDtGuia() {
        return this.dtGuia;
    }
    
    public void setDtGuia(Date dtGuia) {
        this.dtGuia = dtGuia;
    }

    
    @Column(name="VALOR_REPASSE", nullable=false, precision=15)
    public BigDecimal getValorRepasse() {
        return this.valorRepasse;
    }
    
    public void setValorRepasse(BigDecimal valorRepasse) {
        this.valorRepasse = valorRepasse;
    }

    
    @Column(name="VALOR_COPARTICIPACAO", nullable=false, precision=15)
    public BigDecimal getValorCoparticipacao() {
        return this.valorCoparticipacao;
    }
    
    public void setValorCoparticipacao(BigDecimal valorCoparticipacao) {
        this.valorCoparticipacao = valorCoparticipacao;
    }

    
    @Column(name="VL_RECEBER_PROFISSIONAL", precision=15)
    public BigDecimal getVlReceberProfissional() {
        return this.vlReceberProfissional;
    }
    
    public void setVlReceberProfissional(BigDecimal vlReceberProfissional) {
        this.vlReceberProfissional = vlReceberProfissional;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="VL_TRIBUTACAO", nullable=false, precision=15)
    public BigDecimal getVlTributacao() {
        return this.vlTributacao;
    }
    
    public void setVlTributacao(BigDecimal vlTributacao) {
        this.vlTributacao = vlTributacao;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="guiaPaciente")
    public GuiaFechamento getGuiaFechamento() {
        return this.guiaFechamento;
    }
    
    public void setGuiaFechamento(GuiaFechamento guiaFechamento) {
        this.guiaFechamento = guiaFechamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guiaPaciente")
    public Set getProcedimentoGuias() {
        return this.procedimentoGuias;
    }
    
    public void setProcedimentoGuias(Set procedimentoGuias) {
        this.procedimentoGuias = procedimentoGuias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guiaPaciente")
    public Set getComposicaoPagamentoProfs() {
        return this.composicaoPagamentoProfs;
    }
    
    public void setComposicaoPagamentoProfs(Set composicaoPagamentoProfs) {
        this.composicaoPagamentoProfs = composicaoPagamentoProfs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guiaPaciente")
    public Set getGuiaPacientes() {
        return this.guiaPacientes;
    }
    
    public void setGuiaPacientes(Set guiaPacientes) {
        this.guiaPacientes = guiaPacientes;
    }




}


