package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioAberturaAgenda generated by hbm2java
 */
@Entity
@Table(name="HORARIO_ABERTURA_AGENDA"
    ,schema="DESENV"
)
public class HorarioAberturaAgenda  implements java.io.Serializable {


     private BigDecimal id;
     private AberturaAgenda aberturaAgenda;
     private TipoAgenda tipoAgenda;
     private Empresa empresa;
     private BigDecimal nuDiaSemana;
     private Date hrInicio;
     private Date hrTermino;
     private BigDecimal consUniId;
     private BigDecimal consId;
     private String flParticular;
     private String flConvenio;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public HorarioAberturaAgenda() {
    }

	
    public HorarioAberturaAgenda(BigDecimal id, AberturaAgenda aberturaAgenda, TipoAgenda tipoAgenda, Empresa empresa, BigDecimal nuDiaSemana, Date hrInicio, Date hrTermino, BigDecimal consUniId, BigDecimal consId, String flParticular, String flConvenio) {
        this.id = id;
        this.aberturaAgenda = aberturaAgenda;
        this.tipoAgenda = tipoAgenda;
        this.empresa = empresa;
        this.nuDiaSemana = nuDiaSemana;
        this.hrInicio = hrInicio;
        this.hrTermino = hrTermino;
        this.consUniId = consUniId;
        this.consId = consId;
        this.flParticular = flParticular;
        this.flConvenio = flConvenio;
    }
    public HorarioAberturaAgenda(BigDecimal id, AberturaAgenda aberturaAgenda, TipoAgenda tipoAgenda, Empresa empresa, BigDecimal nuDiaSemana, Date hrInicio, Date hrTermino, BigDecimal consUniId, BigDecimal consId, String flParticular, String flConvenio, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.aberturaAgenda = aberturaAgenda;
       this.tipoAgenda = tipoAgenda;
       this.empresa = empresa;
       this.nuDiaSemana = nuDiaSemana;
       this.hrInicio = hrInicio;
       this.hrTermino = hrTermino;
       this.consUniId = consUniId;
       this.consId = consId;
       this.flParticular = flParticular;
       this.flConvenio = flConvenio;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ABEAGE_ID", nullable=false)
    public AberturaAgenda getAberturaAgenda() {
        return this.aberturaAgenda;
    }
    
    public void setAberturaAgenda(AberturaAgenda aberturaAgenda) {
        this.aberturaAgenda = aberturaAgenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="TIAGE_ID", referencedColumnName="ID", nullable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false) } )
    public TipoAgenda getTipoAgenda() {
        return this.tipoAgenda;
    }
    
    public void setTipoAgenda(TipoAgenda tipoAgenda) {
        this.tipoAgenda = tipoAgenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NU_DIA_SEMANA", nullable=false, precision=22, scale=0)
    public BigDecimal getNuDiaSemana() {
        return this.nuDiaSemana;
    }
    
    public void setNuDiaSemana(BigDecimal nuDiaSemana) {
        this.nuDiaSemana = nuDiaSemana;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HR_INICIO", nullable=false, length=7)
    public Date getHrInicio() {
        return this.hrInicio;
    }
    
    public void setHrInicio(Date hrInicio) {
        this.hrInicio = hrInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="HR_TERMINO", nullable=false, length=7)
    public Date getHrTermino() {
        return this.hrTermino;
    }
    
    public void setHrTermino(Date hrTermino) {
        this.hrTermino = hrTermino;
    }

    
    @Column(name="CONS_UNI_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getConsUniId() {
        return this.consUniId;
    }
    
    public void setConsUniId(BigDecimal consUniId) {
        this.consUniId = consUniId;
    }

    
    @Column(name="CONS_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getConsId() {
        return this.consId;
    }
    
    public void setConsId(BigDecimal consId) {
        this.consId = consId;
    }

    
    @Column(name="FL_PARTICULAR", nullable=false, length=1)
    public String getFlParticular() {
        return this.flParticular;
    }
    
    public void setFlParticular(String flParticular) {
        this.flParticular = flParticular;
    }

    
    @Column(name="FL_CONVENIO", nullable=false, length=1)
    public String getFlConvenio() {
        return this.flConvenio;
    }
    
    public void setFlConvenio(String flConvenio) {
        this.flConvenio = flConvenio;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


