package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HorarioUnidadeId generated by hbm2java
 */
@Embeddable
public class HorarioUnidadeId  implements java.io.Serializable {


     private String diaSemana;
     private BigDecimal uniId;

    public HorarioUnidadeId() {
    }

    public HorarioUnidadeId(String diaSemana, BigDecimal uniId) {
       this.diaSemana = diaSemana;
       this.uniId = uniId;
    }
   


    @Column(name="DIA_SEMANA", nullable=false, length=1)
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }


    @Column(name="UNI_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUniId() {
        return this.uniId;
    }
    
    public void setUniId(BigDecimal uniId) {
        this.uniId = uniId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HorarioUnidadeId) ) return false;
		 HorarioUnidadeId castOther = ( HorarioUnidadeId ) other; 
         
		 return ( (this.getDiaSemana()==castOther.getDiaSemana()) || ( this.getDiaSemana()!=null && castOther.getDiaSemana()!=null && this.getDiaSemana().equals(castOther.getDiaSemana()) ) )
 && ( (this.getUniId()==castOther.getUniId()) || ( this.getUniId()!=null && castOther.getUniId()!=null && this.getUniId().equals(castOther.getUniId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDiaSemana() == null ? 0 : this.getDiaSemana().hashCode() );
         result = 37 * result + ( getUniId() == null ? 0 : this.getUniId().hashCode() );
         return result;
   }   


}


