package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InventarioItem generated by hbm2java
 */
@Entity
@Table(name="INVENTARIO_ITEM"
    ,schema="DESENV"
)
public class InventarioItem  implements java.io.Serializable {


     private InventarioItemId id;
     private ItemUnidade itemUnidade;
     private Inventario inventario;
     private Item item;
     private Empresa empresa;
     private BigDecimal qtContagem;
     private BigDecimal qtEstoque;
     private String motivo;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;

    public InventarioItem() {
    }

	
    public InventarioItem(InventarioItemId id, ItemUnidade itemUnidade, Inventario inventario, Item item, Empresa empresa, BigDecimal qtEstoque, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.id = id;
        this.itemUnidade = itemUnidade;
        this.inventario = inventario;
        this.item = item;
        this.empresa = empresa;
        this.qtEstoque = qtEstoque;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public InventarioItem(InventarioItemId id, ItemUnidade itemUnidade, Inventario inventario, Item item, Empresa empresa, BigDecimal qtContagem, BigDecimal qtEstoque, String motivo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
       this.id = id;
       this.itemUnidade = itemUnidade;
       this.inventario = inventario;
       this.item = item;
       this.empresa = empresa;
       this.qtContagem = qtContagem;
       this.qtEstoque = qtEstoque;
       this.motivo = motivo;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="inveData", column=@Column(name="INVE_DATA", nullable=false, length=7) ), 
        @AttributeOverride(name="inveUniId", column=@Column(name="INVE_UNI_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, precision=22, scale=0) ) } )
    public InventarioItemId getId() {
        return this.id;
    }
    
    public void setId(InventarioItemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="INVE_UNI_ID", referencedColumnName="UNI_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ITEM_ID", referencedColumnName="ITEM_ID", nullable=false, insertable=false, updatable=false) } )
    public ItemUnidade getItemUnidade() {
        return this.itemUnidade;
    }
    
    public void setItemUnidade(ItemUnidade itemUnidade) {
        this.itemUnidade = itemUnidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="INVE_DATA", referencedColumnName="DATA", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="INVE_UNI_ID", referencedColumnName="UNI_ID", nullable=false, insertable=false, updatable=false) } )
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_ID", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="QT_CONTAGEM", precision=22, scale=0)
    public BigDecimal getQtContagem() {
        return this.qtContagem;
    }
    
    public void setQtContagem(BigDecimal qtContagem) {
        this.qtContagem = qtContagem;
    }

    
    @Column(name="QT_ESTOQUE", nullable=false, precision=22, scale=0)
    public BigDecimal getQtEstoque() {
        return this.qtEstoque;
    }
    
    public void setQtEstoque(BigDecimal qtEstoque) {
        this.qtEstoque = qtEstoque;
    }

    
    @Column(name="MOTIVO", length=4000)
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


