package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemUnidade generated by hbm2java
 */
@Entity
@Table(name="ITEM_UNIDADE"
    ,schema="DESENV"
)
public class ItemUnidade  implements java.io.Serializable {


     private ItemUnidadeId id;
     private Item item;
     private Unidade unidade;
     private Empresa empresa;
     private BigDecimal qtEstoque;
     private BigDecimal qtMinimaEstoque;
     private BigDecimal vlMedio;
     private Date dtUltimaCompra;
     private BigDecimal cdAlteradoPor;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set consumoItems = new HashSet(0);
     private Set inventarioItems = new HashSet(0);

    public ItemUnidade() {
    }

	
    public ItemUnidade(ItemUnidadeId id, Item item, Unidade unidade, Empresa empresa, BigDecimal qtEstoque, BigDecimal qtMinimaEstoque, BigDecimal vlMedio, BigDecimal cdAlteradoPor, BigDecimal cdCriadoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.id = id;
        this.item = item;
        this.unidade = unidade;
        this.empresa = empresa;
        this.qtEstoque = qtEstoque;
        this.qtMinimaEstoque = qtMinimaEstoque;
        this.vlMedio = vlMedio;
        this.cdAlteradoPor = cdAlteradoPor;
        this.cdCriadoPor = cdCriadoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public ItemUnidade(ItemUnidadeId id, Item item, Unidade unidade, Empresa empresa, BigDecimal qtEstoque, BigDecimal qtMinimaEstoque, BigDecimal vlMedio, Date dtUltimaCompra, BigDecimal cdAlteradoPor, BigDecimal cdCriadoPor, Date dtCriacao, Date dtUltimaAlteracao, Set consumoItems, Set inventarioItems) {
       this.id = id;
       this.item = item;
       this.unidade = unidade;
       this.empresa = empresa;
       this.qtEstoque = qtEstoque;
       this.qtMinimaEstoque = qtMinimaEstoque;
       this.vlMedio = vlMedio;
       this.dtUltimaCompra = dtUltimaCompra;
       this.cdAlteradoPor = cdAlteradoPor;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.consumoItems = consumoItems;
       this.inventarioItems = inventarioItems;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="uniId", column=@Column(name="UNI_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, precision=22, scale=0) ) } )
    public ItemUnidadeId getId() {
        return this.id;
    }
    
    public void setId(ItemUnidadeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_ID", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false, insertable=false, updatable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="QT_ESTOQUE", nullable=false, precision=22, scale=0)
    public BigDecimal getQtEstoque() {
        return this.qtEstoque;
    }
    
    public void setQtEstoque(BigDecimal qtEstoque) {
        this.qtEstoque = qtEstoque;
    }

    
    @Column(name="QT_MINIMA_ESTOQUE", nullable=false, precision=22, scale=0)
    public BigDecimal getQtMinimaEstoque() {
        return this.qtMinimaEstoque;
    }
    
    public void setQtMinimaEstoque(BigDecimal qtMinimaEstoque) {
        this.qtMinimaEstoque = qtMinimaEstoque;
    }

    
    @Column(name="VL_MEDIO", nullable=false, precision=21, scale=4)
    public BigDecimal getVlMedio() {
        return this.vlMedio;
    }
    
    public void setVlMedio(BigDecimal vlMedio) {
        this.vlMedio = vlMedio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_COMPRA", length=7)
    public Date getDtUltimaCompra() {
        return this.dtUltimaCompra;
    }
    
    public void setDtUltimaCompra(Date dtUltimaCompra) {
        this.dtUltimaCompra = dtUltimaCompra;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemUnidade")
    public Set getConsumoItems() {
        return this.consumoItems;
    }
    
    public void setConsumoItems(Set consumoItems) {
        this.consumoItems = consumoItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemUnidade")
    public Set getInventarioItems() {
        return this.inventarioItems;
    }
    
    public void setInventarioItems(Set inventarioItems) {
        this.inventarioItems = inventarioItems;
    }




}


