package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemMenu generated by hbm2java
 */
@Entity
@Table(name="ITEM_MENU"
    ,schema="DESENV"
)
public class ItemMenu  implements java.io.Serializable {


     private BigDecimal cdItemMenu;
     private ItemMenu itemMenu;
     private Menu menu;
     private TelaRelatorioGrafico telaRelatorioGrafico;
     private String dsItemMenu;
     private BigDecimal nuPrioridade;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set itemMenus = new HashSet(0);

    public ItemMenu() {
    }

	
    public ItemMenu(BigDecimal cdItemMenu, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdItemMenu = cdItemMenu;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public ItemMenu(BigDecimal cdItemMenu, ItemMenu itemMenu, Menu menu, TelaRelatorioGrafico telaRelatorioGrafico, String dsItemMenu, BigDecimal nuPrioridade, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set itemMenus) {
       this.cdItemMenu = cdItemMenu;
       this.itemMenu = itemMenu;
       this.menu = menu;
       this.telaRelatorioGrafico = telaRelatorioGrafico;
       this.dsItemMenu = dsItemMenu;
       this.nuPrioridade = nuPrioridade;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.itemMenus = itemMenus;
    }
   
     @Id 

    
    @Column(name="CD_ITEM_MENU", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdItemMenu() {
        return this.cdItemMenu;
    }
    
    public void setCdItemMenu(BigDecimal cdItemMenu) {
        this.cdItemMenu = cdItemMenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITME_CD_ITEM_MENU")
    public ItemMenu getItemMenu() {
        return this.itemMenu;
    }
    
    public void setItemMenu(ItemMenu itemMenu) {
        this.itemMenu = itemMenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MENU_CD_MENU")
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TERE_CD_TELA_RELATORIO")
    public TelaRelatorioGrafico getTelaRelatorioGrafico() {
        return this.telaRelatorioGrafico;
    }
    
    public void setTelaRelatorioGrafico(TelaRelatorioGrafico telaRelatorioGrafico) {
        this.telaRelatorioGrafico = telaRelatorioGrafico;
    }

    
    @Column(name="DS_ITEM_MENU", length=100)
    public String getDsItemMenu() {
        return this.dsItemMenu;
    }
    
    public void setDsItemMenu(String dsItemMenu) {
        this.dsItemMenu = dsItemMenu;
    }

    
    @Column(name="NU_PRIORIDADE", precision=22, scale=0)
    public BigDecimal getNuPrioridade() {
        return this.nuPrioridade;
    }
    
    public void setNuPrioridade(BigDecimal nuPrioridade) {
        this.nuPrioridade = nuPrioridade;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemMenu")
    public Set getItemMenus() {
        return this.itemMenus;
    }
    
    public void setItemMenus(Set itemMenus) {
        this.itemMenus = itemMenus;
    }




}


