package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LayoutBancario generated by hbm2java
 */
@Entity
@Table(name="LAYOUT_BANCARIO"
    ,schema="DESENV"
)
public class LayoutBancario  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private String nome;
     private String flTipo;
     private char flAtivo;
     private String nmViewRemessa;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set convenioBancarios = new HashSet(0);
     private Set comandoLayouts = new HashSet(0);
     private Set campoLayouts = new HashSet(0);

    public LayoutBancario() {
    }

	
    public LayoutBancario(BigDecimal id, Empresa empresa, String nome, String flTipo, char flAtivo, String nmViewRemessa) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.flTipo = flTipo;
        this.flAtivo = flAtivo;
        this.nmViewRemessa = nmViewRemessa;
    }
    public LayoutBancario(BigDecimal id, Empresa empresa, String nome, String flTipo, char flAtivo, String nmViewRemessa, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set convenioBancarios, Set comandoLayouts, Set campoLayouts) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.flTipo = flTipo;
       this.flAtivo = flAtivo;
       this.nmViewRemessa = nmViewRemessa;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.convenioBancarios = convenioBancarios;
       this.comandoLayouts = comandoLayouts;
       this.campoLayouts = campoLayouts;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_TIPO", nullable=false, length=3)
    public String getFlTipo() {
        return this.flTipo;
    }
    
    public void setFlTipo(String flTipo) {
        this.flTipo = flTipo;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public char getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(char flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="NM_VIEW_REMESSA", nullable=false, length=30)
    public String getNmViewRemessa() {
        return this.nmViewRemessa;
    }
    
    public void setNmViewRemessa(String nmViewRemessa) {
        this.nmViewRemessa = nmViewRemessa;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="layoutBancario")
    public Set getConvenioBancarios() {
        return this.convenioBancarios;
    }
    
    public void setConvenioBancarios(Set convenioBancarios) {
        this.convenioBancarios = convenioBancarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="layoutBancario")
    public Set getComandoLayouts() {
        return this.comandoLayouts;
    }
    
    public void setComandoLayouts(Set comandoLayouts) {
        this.comandoLayouts = comandoLayouts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="layoutBancario")
    public Set getCampoLayouts() {
        return this.campoLayouts;
    }
    
    public void setCampoLayouts(Set campoLayouts) {
        this.campoLayouts = campoLayouts;
    }




}


