package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LinhasArquivoLiquidacao generated by hbm2java
 */
@Entity
@Table(name="LINHAS_ARQUIVO_LIQUIDACAO"
    ,schema="DESENV"
)
public class LinhasArquivoLiquidacao  implements java.io.Serializable {


     private LinhasArquivoLiquidacaoId id;
     private ArquivoLiquidacao arquivoLiquidacao;
     private Empresa empresa;
     private String linha;
     private String status;
     private String tipo;
     private String erro;
     private String banco;
     private String agencia;
     private String cedente;
     private String nossoNumero;
     private BigDecimal valorPago;
     private BigDecimal valorJuros;
     private BigDecimal valorDesconto;
     private BigDecimal valorOutrosRecebimentos;
     private String comando;
     private Date dataCredito;
     private Date dataPagamento;
     private String dsMotivo;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set movimentoTitulos = new HashSet(0);
     private Set pagamentosTituloses = new HashSet(0);

    public LinhasArquivoLiquidacao() {
    }

	
    public LinhasArquivoLiquidacao(LinhasArquivoLiquidacaoId id, ArquivoLiquidacao arquivoLiquidacao, Empresa empresa, String linha, String status, String tipo) {
        this.id = id;
        this.arquivoLiquidacao = arquivoLiquidacao;
        this.empresa = empresa;
        this.linha = linha;
        this.status = status;
        this.tipo = tipo;
    }
    public LinhasArquivoLiquidacao(LinhasArquivoLiquidacaoId id, ArquivoLiquidacao arquivoLiquidacao, Empresa empresa, String linha, String status, String tipo, String erro, String banco, String agencia, String cedente, String nossoNumero, BigDecimal valorPago, BigDecimal valorJuros, BigDecimal valorDesconto, BigDecimal valorOutrosRecebimentos, String comando, Date dataCredito, Date dataPagamento, String dsMotivo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set movimentoTitulos, Set pagamentosTituloses) {
       this.id = id;
       this.arquivoLiquidacao = arquivoLiquidacao;
       this.empresa = empresa;
       this.linha = linha;
       this.status = status;
       this.tipo = tipo;
       this.erro = erro;
       this.banco = banco;
       this.agencia = agencia;
       this.cedente = cedente;
       this.nossoNumero = nossoNumero;
       this.valorPago = valorPago;
       this.valorJuros = valorJuros;
       this.valorDesconto = valorDesconto;
       this.valorOutrosRecebimentos = valorOutrosRecebimentos;
       this.comando = comando;
       this.dataCredito = dataCredito;
       this.dataPagamento = dataPagamento;
       this.dsMotivo = dsMotivo;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.movimentoTitulos = movimentoTitulos;
       this.pagamentosTituloses = pagamentosTituloses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="arqliqId", column=@Column(name="ARQLIQ_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false, precision=22, scale=0) ) } )
    public LinhasArquivoLiquidacaoId getId() {
        return this.id;
    }
    
    public void setId(LinhasArquivoLiquidacaoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ARQLIQ_ID", nullable=false, insertable=false, updatable=false)
    public ArquivoLiquidacao getArquivoLiquidacao() {
        return this.arquivoLiquidacao;
    }
    
    public void setArquivoLiquidacao(ArquivoLiquidacao arquivoLiquidacao) {
        this.arquivoLiquidacao = arquivoLiquidacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="LINHA", nullable=false, length=4000)
    public String getLinha() {
        return this.linha;
    }
    
    public void setLinha(String linha) {
        this.linha = linha;
    }

    
    @Column(name="STATUS", nullable=false, length=2)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="TIPO", nullable=false, length=2)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="ERRO", length=4000)
    public String getErro() {
        return this.erro;
    }
    
    public void setErro(String erro) {
        this.erro = erro;
    }

    
    @Column(name="BANCO", length=3)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

    
    @Column(name="AGENCIA", length=4)
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }

    
    @Column(name="CEDENTE", length=20)
    public String getCedente() {
        return this.cedente;
    }
    
    public void setCedente(String cedente) {
        this.cedente = cedente;
    }

    
    @Column(name="NOSSO_NUMERO", length=20)
    public String getNossoNumero() {
        return this.nossoNumero;
    }
    
    public void setNossoNumero(String nossoNumero) {
        this.nossoNumero = nossoNumero;
    }

    
    @Column(name="VALOR_PAGO", precision=22, scale=0)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VALOR_JUROS", precision=22, scale=0)
    public BigDecimal getValorJuros() {
        return this.valorJuros;
    }
    
    public void setValorJuros(BigDecimal valorJuros) {
        this.valorJuros = valorJuros;
    }

    
    @Column(name="VALOR_DESCONTO", precision=22, scale=0)
    public BigDecimal getValorDesconto() {
        return this.valorDesconto;
    }
    
    public void setValorDesconto(BigDecimal valorDesconto) {
        this.valorDesconto = valorDesconto;
    }

    
    @Column(name="VALOR_OUTROS_RECEBIMENTOS", precision=22, scale=0)
    public BigDecimal getValorOutrosRecebimentos() {
        return this.valorOutrosRecebimentos;
    }
    
    public void setValorOutrosRecebimentos(BigDecimal valorOutrosRecebimentos) {
        this.valorOutrosRecebimentos = valorOutrosRecebimentos;
    }

    
    @Column(name="COMANDO", length=2)
    public String getComando() {
        return this.comando;
    }
    
    public void setComando(String comando) {
        this.comando = comando;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_CREDITO", length=7)
    public Date getDataCredito() {
        return this.dataCredito;
    }
    
    public void setDataCredito(Date dataCredito) {
        this.dataCredito = dataCredito;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_PAGAMENTO", length=7)
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    
    @Column(name="DS_MOTIVO")
    public String getDsMotivo() {
        return this.dsMotivo;
    }
    
    public void setDsMotivo(String dsMotivo) {
        this.dsMotivo = dsMotivo;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="linhasArquivoLiquidacao")
    public Set getMovimentoTitulos() {
        return this.movimentoTitulos;
    }
    
    public void setMovimentoTitulos(Set movimentoTitulos) {
        this.movimentoTitulos = movimentoTitulos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="linhasArquivoLiquidacao")
    public Set getPagamentosTituloses() {
        return this.pagamentosTituloses;
    }
    
    public void setPagamentosTituloses(Set pagamentosTituloses) {
        this.pagamentosTituloses = pagamentosTituloses;
    }




}


