package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListaRegiaoProcedimento generated by hbm2java
 */
@Entity
@Table(name="LISTA_REGIAO_PROCEDIMENTO"
    ,schema="DESENV"
)
public class ListaRegiaoProcedimento  implements java.io.Serializable {


     private ListaRegiaoProcedimentoId id;
     private RegiaoProcedimento regiaoProcedimento;
     private Empresa empresa;
     private String descricao;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set procedimentoPacientes = new HashSet(0);
     private Set procedimentoContratos = new HashSet(0);
     private Set procedimentoGuias = new HashSet(0);

    public ListaRegiaoProcedimento() {
    }

	
    public ListaRegiaoProcedimento(ListaRegiaoProcedimentoId id, RegiaoProcedimento regiaoProcedimento, Empresa empresa, String descricao) {
        this.id = id;
        this.regiaoProcedimento = regiaoProcedimento;
        this.empresa = empresa;
        this.descricao = descricao;
    }
    public ListaRegiaoProcedimento(ListaRegiaoProcedimentoId id, RegiaoProcedimento regiaoProcedimento, Empresa empresa, String descricao, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set procedimentoPacientes, Set procedimentoContratos, Set procedimentoGuias) {
       this.id = id;
       this.regiaoProcedimento = regiaoProcedimento;
       this.empresa = empresa;
       this.descricao = descricao;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.procedimentoPacientes = procedimentoPacientes;
       this.procedimentoContratos = procedimentoContratos;
       this.procedimentoGuias = procedimentoGuias;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="regiao", column=@Column(name="REGIAO", nullable=false, length=10) ), 
        @AttributeOverride(name="regpId", column=@Column(name="REGP_ID", nullable=false, precision=22, scale=0) ) } )
    public ListaRegiaoProcedimentoId getId() {
        return this.id;
    }
    
    public void setId(ListaRegiaoProcedimentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGP_ID", nullable=false, insertable=false, updatable=false)
    public RegiaoProcedimento getRegiaoProcedimento() {
        return this.regiaoProcedimento;
    }
    
    public void setRegiaoProcedimento(RegiaoProcedimento regiaoProcedimento) {
        this.regiaoProcedimento = regiaoProcedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="DESCRICAO", nullable=false, length=40)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="listaRegiaoProcedimento")
    public Set getProcedimentoPacientes() {
        return this.procedimentoPacientes;
    }
    
    public void setProcedimentoPacientes(Set procedimentoPacientes) {
        this.procedimentoPacientes = procedimentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="listaRegiaoProcedimento")
    public Set getProcedimentoContratos() {
        return this.procedimentoContratos;
    }
    
    public void setProcedimentoContratos(Set procedimentoContratos) {
        this.procedimentoContratos = procedimentoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="listaRegiaoProcedimento")
    public Set getProcedimentoGuias() {
        return this.procedimentoGuias;
    }
    
    public void setProcedimentoGuias(Set procedimentoGuias) {
        this.procedimentoGuias = procedimentoGuias;
    }




}


