package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name="MATERIAL"
    ,schema="DESENV"
)
public class Material  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private String nome;
     private String flAtivo;
     private String unidadeMedida;
     private BigDecimal qtEstoque;
     private BigDecimal qtMinimaEstoque;
     private BigDecimal valorMinimo;
     private BigDecimal valorMaximo;
     private BigDecimal valorMedio;
     private Date dtUltimaCompra;
     private String flDuravel;
     private String informacaoMelhorCompra;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set materialProcedimentos = new HashSet(0);
     private Set consumoMaterials = new HashSet(0);
     private Set embalagemMaterials = new HashSet(0);
     private Set materialPedidos = new HashSet(0);

    public Material() {
    }

	
    public Material(BigDecimal id, Empresa empresa, String nome, String flAtivo, String unidadeMedida, BigDecimal qtEstoque, String flDuravel) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.flAtivo = flAtivo;
        this.unidadeMedida = unidadeMedida;
        this.qtEstoque = qtEstoque;
        this.flDuravel = flDuravel;
    }
    public Material(BigDecimal id, Empresa empresa, String nome, String flAtivo, String unidadeMedida, BigDecimal qtEstoque, BigDecimal qtMinimaEstoque, BigDecimal valorMinimo, BigDecimal valorMaximo, BigDecimal valorMedio, Date dtUltimaCompra, String flDuravel, String informacaoMelhorCompra, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set materialProcedimentos, Set consumoMaterials, Set embalagemMaterials, Set materialPedidos) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.flAtivo = flAtivo;
       this.unidadeMedida = unidadeMedida;
       this.qtEstoque = qtEstoque;
       this.qtMinimaEstoque = qtMinimaEstoque;
       this.valorMinimo = valorMinimo;
       this.valorMaximo = valorMaximo;
       this.valorMedio = valorMedio;
       this.dtUltimaCompra = dtUltimaCompra;
       this.flDuravel = flDuravel;
       this.informacaoMelhorCompra = informacaoMelhorCompra;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.materialProcedimentos = materialProcedimentos;
       this.consumoMaterials = consumoMaterials;
       this.embalagemMaterials = embalagemMaterials;
       this.materialPedidos = materialPedidos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="UNIDADE_MEDIDA", nullable=false, length=10)
    public String getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(String unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }

    
    @Column(name="QT_ESTOQUE", nullable=false, precision=22, scale=0)
    public BigDecimal getQtEstoque() {
        return this.qtEstoque;
    }
    
    public void setQtEstoque(BigDecimal qtEstoque) {
        this.qtEstoque = qtEstoque;
    }

    
    @Column(name="QT_MINIMA_ESTOQUE", precision=22, scale=0)
    public BigDecimal getQtMinimaEstoque() {
        return this.qtMinimaEstoque;
    }
    
    public void setQtMinimaEstoque(BigDecimal qtMinimaEstoque) {
        this.qtMinimaEstoque = qtMinimaEstoque;
    }

    
    @Column(name="VALOR_MINIMO", precision=15)
    public BigDecimal getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(BigDecimal valorMinimo) {
        this.valorMinimo = valorMinimo;
    }

    
    @Column(name="VALOR_MAXIMO", precision=15)
    public BigDecimal getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(BigDecimal valorMaximo) {
        this.valorMaximo = valorMaximo;
    }

    
    @Column(name="VALOR_MEDIO", precision=15)
    public BigDecimal getValorMedio() {
        return this.valorMedio;
    }
    
    public void setValorMedio(BigDecimal valorMedio) {
        this.valorMedio = valorMedio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_COMPRA", length=7)
    public Date getDtUltimaCompra() {
        return this.dtUltimaCompra;
    }
    
    public void setDtUltimaCompra(Date dtUltimaCompra) {
        this.dtUltimaCompra = dtUltimaCompra;
    }

    
    @Column(name="FL_DURAVEL", nullable=false, length=1)
    public String getFlDuravel() {
        return this.flDuravel;
    }
    
    public void setFlDuravel(String flDuravel) {
        this.flDuravel = flDuravel;
    }

    
    @Column(name="INFORMACAO_MELHOR_COMPRA", length=4000)
    public String getInformacaoMelhorCompra() {
        return this.informacaoMelhorCompra;
    }
    
    public void setInformacaoMelhorCompra(String informacaoMelhorCompra) {
        this.informacaoMelhorCompra = informacaoMelhorCompra;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="material")
    public Set getMaterialProcedimentos() {
        return this.materialProcedimentos;
    }
    
    public void setMaterialProcedimentos(Set materialProcedimentos) {
        this.materialProcedimentos = materialProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="material")
    public Set getConsumoMaterials() {
        return this.consumoMaterials;
    }
    
    public void setConsumoMaterials(Set consumoMaterials) {
        this.consumoMaterials = consumoMaterials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="material")
    public Set getEmbalagemMaterials() {
        return this.embalagemMaterials;
    }
    
    public void setEmbalagemMaterials(Set embalagemMaterials) {
        this.embalagemMaterials = embalagemMaterials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="material")
    public Set getMaterialPedidos() {
        return this.materialPedidos;
    }
    
    public void setMaterialPedidos(Set materialPedidos) {
        this.materialPedidos = materialPedidos;
    }




}


