package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaterialProcedimento generated by hbm2java
 */
@Entity
@Table(name="MATERIAL_PROCEDIMENTO"
    ,schema="DESENV"
)
public class MaterialProcedimento  implements java.io.Serializable {


     private MaterialProcedimentoId id;
     private Material material;
     private Procedimento procedimento;
     private Empresa empresa;
     private BigDecimal quantidade;
     private BigDecimal valorMedio;
     private char flRateio;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public MaterialProcedimento() {
    }

	
    public MaterialProcedimento(MaterialProcedimentoId id, Material material, Procedimento procedimento, Empresa empresa, BigDecimal quantidade, BigDecimal valorMedio, char flRateio) {
        this.id = id;
        this.material = material;
        this.procedimento = procedimento;
        this.empresa = empresa;
        this.quantidade = quantidade;
        this.valorMedio = valorMedio;
        this.flRateio = flRateio;
    }
    public MaterialProcedimento(MaterialProcedimentoId id, Material material, Procedimento procedimento, Empresa empresa, BigDecimal quantidade, BigDecimal valorMedio, char flRateio, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.material = material;
       this.procedimento = procedimento;
       this.empresa = empresa;
       this.quantidade = quantidade;
       this.valorMedio = valorMedio;
       this.flRateio = flRateio;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="procId", column=@Column(name="PROC_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="matId", column=@Column(name="MAT_ID", nullable=false, precision=22, scale=0) ) } )
    public MaterialProcedimentoId getId() {
        return this.id;
    }
    
    public void setId(MaterialProcedimentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MAT_ID", nullable=false, insertable=false, updatable=false)
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROC_ID", nullable=false, insertable=false, updatable=false)
    public Procedimento getProcedimento() {
        return this.procedimento;
    }
    
    public void setProcedimento(Procedimento procedimento) {
        this.procedimento = procedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="QUANTIDADE", nullable=false, precision=17, scale=4)
    public BigDecimal getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(BigDecimal quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="VALOR_MEDIO", nullable=false, precision=15)
    public BigDecimal getValorMedio() {
        return this.valorMedio;
    }
    
    public void setValorMedio(BigDecimal valorMedio) {
        this.valorMedio = valorMedio;
    }

    
    @Column(name="FL_RATEIO", nullable=false, length=1)
    public char getFlRateio() {
        return this.flRateio;
    }
    
    public void setFlRateio(char flRateio) {
        this.flRateio = flRateio;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


