package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaterialPedido generated by hbm2java
 */
@Entity
@Table(name="MATERIAL_PEDIDO"
    ,schema="DESENV"
)
public class MaterialPedido  implements java.io.Serializable {


     private MaterialPedidoId id;
     private EmbalagemPedido embalagemPedido;
     private Material material;
     private Pedido pedido;
     private Empresa empresa;
     private BigDecimal quantidade;
     private BigDecimal valorUnitario;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public MaterialPedido() {
    }

	
    public MaterialPedido(MaterialPedidoId id, EmbalagemPedido embalagemPedido, Material material, Pedido pedido, Empresa empresa, BigDecimal quantidade, BigDecimal valorUnitario) {
        this.id = id;
        this.embalagemPedido = embalagemPedido;
        this.material = material;
        this.pedido = pedido;
        this.empresa = empresa;
        this.quantidade = quantidade;
        this.valorUnitario = valorUnitario;
    }
    public MaterialPedido(MaterialPedidoId id, EmbalagemPedido embalagemPedido, Material material, Pedido pedido, Empresa empresa, BigDecimal quantidade, BigDecimal valorUnitario, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.embalagemPedido = embalagemPedido;
       this.material = material;
       this.pedido = pedido;
       this.empresa = empresa;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="matId", column=@Column(name="MAT_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="pedId", column=@Column(name="PED_ID", nullable=false, precision=22, scale=0) ) } )
    public MaterialPedidoId getId() {
        return this.id;
    }
    
    public void setId(MaterialPedidoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="EMPE_EMBMA_ID", referencedColumnName="EMBMA_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PED_ID", referencedColumnName="PEDIDO_ID", nullable=false, insertable=false, updatable=false) } )
    public EmbalagemPedido getEmbalagemPedido() {
        return this.embalagemPedido;
    }
    
    public void setEmbalagemPedido(EmbalagemPedido embalagemPedido) {
        this.embalagemPedido = embalagemPedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MAT_ID", nullable=false, insertable=false, updatable=false)
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PED_ID", nullable=false, insertable=false, updatable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="QUANTIDADE", nullable=false, precision=22, scale=0)
    public BigDecimal getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(BigDecimal quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="VALOR_UNITARIO", nullable=false, precision=15)
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


