package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeioPagamento generated by hbm2java
 */
@Entity
@Table(name="MEIO_PAGAMENTO"
    ,schema="DESENV"
)
public class MeioPagamento  implements java.io.Serializable {


     private BigDecimal id;
     private PlanoContas planoContasByPlaIdJuros;
     private PlanoContas planoContasByPlaId;
     private Empresa empresa;
     private String nome;
     private String tipo;
     private Short maximoParcelas;
     private BigDecimal valorMinimoParcela;
     private BigDecimal nuDiasPagamento;
     private BigDecimal pcDescontoOperadora;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set pagamentoPacientes = new HashSet(0);
     private Set meioPagamentoContaUnidades = new HashSet(0);
     private Set pagamentoCobrancas = new HashSet(0);

    public MeioPagamento() {
    }

	
    public MeioPagamento(BigDecimal id, Empresa empresa, String nome, String tipo) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.tipo = tipo;
    }
    public MeioPagamento(BigDecimal id, PlanoContas planoContasByPlaIdJuros, PlanoContas planoContasByPlaId, Empresa empresa, String nome, String tipo, Short maximoParcelas, BigDecimal valorMinimoParcela, BigDecimal nuDiasPagamento, BigDecimal pcDescontoOperadora, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set pagamentoPacientes, Set meioPagamentoContaUnidades, Set pagamentoCobrancas) {
       this.id = id;
       this.planoContasByPlaIdJuros = planoContasByPlaIdJuros;
       this.planoContasByPlaId = planoContasByPlaId;
       this.empresa = empresa;
       this.nome = nome;
       this.tipo = tipo;
       this.maximoParcelas = maximoParcelas;
       this.valorMinimoParcela = valorMinimoParcela;
       this.nuDiasPagamento = nuDiasPagamento;
       this.pcDescontoOperadora = pcDescontoOperadora;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.pagamentoPacientes = pagamentoPacientes;
       this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
       this.pagamentoCobrancas = pagamentoCobrancas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLA_ID_JUROS")
    public PlanoContas getPlanoContasByPlaIdJuros() {
        return this.planoContasByPlaIdJuros;
    }
    
    public void setPlanoContasByPlaIdJuros(PlanoContas planoContasByPlaIdJuros) {
        this.planoContasByPlaIdJuros = planoContasByPlaIdJuros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLA_ID")
    public PlanoContas getPlanoContasByPlaId() {
        return this.planoContasByPlaId;
    }
    
    public void setPlanoContasByPlaId(PlanoContas planoContasByPlaId) {
        this.planoContasByPlaId = planoContasByPlaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="TIPO", nullable=false, length=2)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="MAXIMO_PARCELAS", precision=3, scale=0)
    public Short getMaximoParcelas() {
        return this.maximoParcelas;
    }
    
    public void setMaximoParcelas(Short maximoParcelas) {
        this.maximoParcelas = maximoParcelas;
    }

    
    @Column(name="VALOR_MINIMO_PARCELA", precision=15)
    public BigDecimal getValorMinimoParcela() {
        return this.valorMinimoParcela;
    }
    
    public void setValorMinimoParcela(BigDecimal valorMinimoParcela) {
        this.valorMinimoParcela = valorMinimoParcela;
    }

    
    @Column(name="NU_DIAS_PAGAMENTO", precision=22, scale=0)
    public BigDecimal getNuDiasPagamento() {
        return this.nuDiasPagamento;
    }
    
    public void setNuDiasPagamento(BigDecimal nuDiasPagamento) {
        this.nuDiasPagamento = nuDiasPagamento;
    }

    
    @Column(name="PC_DESCONTO_OPERADORA", precision=5)
    public BigDecimal getPcDescontoOperadora() {
        return this.pcDescontoOperadora;
    }
    
    public void setPcDescontoOperadora(BigDecimal pcDescontoOperadora) {
        this.pcDescontoOperadora = pcDescontoOperadora;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meioPagamento")
    public Set getPagamentoPacientes() {
        return this.pagamentoPacientes;
    }
    
    public void setPagamentoPacientes(Set pagamentoPacientes) {
        this.pagamentoPacientes = pagamentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meioPagamento")
    public Set getMeioPagamentoContaUnidades() {
        return this.meioPagamentoContaUnidades;
    }
    
    public void setMeioPagamentoContaUnidades(Set meioPagamentoContaUnidades) {
        this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meioPagamento")
    public Set getPagamentoCobrancas() {
        return this.pagamentoCobrancas;
    }
    
    public void setPagamentoCobrancas(Set pagamentoCobrancas) {
        this.pagamentoCobrancas = pagamentoCobrancas;
    }




}


