package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MenuGrupoUsuarioId generated by hbm2java
 */
@Embeddable
public class MenuGrupoUsuarioId  implements java.io.Serializable {


     private BigDecimal grusCdUsuario;
     private BigDecimal menuCdMenu;

    public MenuGrupoUsuarioId() {
    }

    public MenuGrupoUsuarioId(BigDecimal grusCdUsuario, BigDecimal menuCdMenu) {
       this.grusCdUsuario = grusCdUsuario;
       this.menuCdMenu = menuCdMenu;
    }
   


    @Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getGrusCdUsuario() {
        return this.grusCdUsuario;
    }
    
    public void setGrusCdUsuario(BigDecimal grusCdUsuario) {
        this.grusCdUsuario = grusCdUsuario;
    }


    @Column(name="MENU_CD_MENU", nullable=false, precision=22, scale=0)
    public BigDecimal getMenuCdMenu() {
        return this.menuCdMenu;
    }
    
    public void setMenuCdMenu(BigDecimal menuCdMenu) {
        this.menuCdMenu = menuCdMenu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MenuGrupoUsuarioId) ) return false;
		 MenuGrupoUsuarioId castOther = ( MenuGrupoUsuarioId ) other; 
         
		 return ( (this.getGrusCdUsuario()==castOther.getGrusCdUsuario()) || ( this.getGrusCdUsuario()!=null && castOther.getGrusCdUsuario()!=null && this.getGrusCdUsuario().equals(castOther.getGrusCdUsuario()) ) )
 && ( (this.getMenuCdMenu()==castOther.getMenuCdMenu()) || ( this.getMenuCdMenu()!=null && castOther.getMenuCdMenu()!=null && this.getMenuCdMenu().equals(castOther.getMenuCdMenu()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrusCdUsuario() == null ? 0 : this.getGrusCdUsuario().hashCode() );
         result = 37 * result + ( getMenuCdMenu() == null ? 0 : this.getMenuCdMenu().hashCode() );
         return result;
   }   


}


