package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="MENU"
    ,schema="DESENV"
)
public class Menu  implements java.io.Serializable {


     private BigDecimal cdMenu;
     private String nmMenu;
     private String flAtivo;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set itemMenus = new HashSet(0);
     private Set menuGrupoUsuarios = new HashSet(0);

    public Menu() {
    }

	
    public Menu(BigDecimal cdMenu, String nmMenu, String flAtivo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdMenu = cdMenu;
        this.nmMenu = nmMenu;
        this.flAtivo = flAtivo;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public Menu(BigDecimal cdMenu, String nmMenu, String flAtivo, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set itemMenus, Set menuGrupoUsuarios) {
       this.cdMenu = cdMenu;
       this.nmMenu = nmMenu;
       this.flAtivo = flAtivo;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.itemMenus = itemMenus;
       this.menuGrupoUsuarios = menuGrupoUsuarios;
    }
   
     @Id 

    
    @Column(name="CD_MENU", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdMenu() {
        return this.cdMenu;
    }
    
    public void setCdMenu(BigDecimal cdMenu) {
        this.cdMenu = cdMenu;
    }

    
    @Column(name="NM_MENU", nullable=false, length=80)
    public String getNmMenu() {
        return this.nmMenu;
    }
    
    public void setNmMenu(String nmMenu) {
        this.nmMenu = nmMenu;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getItemMenus() {
        return this.itemMenus;
    }
    
    public void setItemMenus(Set itemMenus) {
        this.itemMenus = itemMenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menu")
    public Set getMenuGrupoUsuarios() {
        return this.menuGrupoUsuarios;
    }
    
    public void setMenuGrupoUsuarios(Set menuGrupoUsuarios) {
        this.menuGrupoUsuarios = menuGrupoUsuarios;
    }




}


