package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MotivoGlosa generated by hbm2java
 */
@Entity
@Table(name="MOTIVO_GLOSA"
    ,schema="DESENV"
)
public class MotivoGlosa  implements java.io.Serializable {


     private MotivoGlosaId id;
     private Convenio convenio;
     private Empresa empresa;
     private String descricao;
     private String descricaoDetalhada;
     private char flTodaGuia;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set procedimentoGuias = new HashSet(0);
     private Set procedimentoGuiaFechamentos = new HashSet(0);

    public MotivoGlosa() {
    }

	
    public MotivoGlosa(MotivoGlosaId id, Convenio convenio, Empresa empresa, String descricao, char flTodaGuia) {
        this.id = id;
        this.convenio = convenio;
        this.empresa = empresa;
        this.descricao = descricao;
        this.flTodaGuia = flTodaGuia;
    }
    public MotivoGlosa(MotivoGlosaId id, Convenio convenio, Empresa empresa, String descricao, String descricaoDetalhada, char flTodaGuia, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set procedimentoGuias, Set procedimentoGuiaFechamentos) {
       this.id = id;
       this.convenio = convenio;
       this.empresa = empresa;
       this.descricao = descricao;
       this.descricaoDetalhada = descricaoDetalhada;
       this.flTodaGuia = flTodaGuia;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.procedimentoGuias = procedimentoGuias;
       this.procedimentoGuiaFechamentos = procedimentoGuiaFechamentos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=20) ), 
        @AttributeOverride(name="convId", column=@Column(name="CONV_ID", nullable=false, precision=22, scale=0) ) } )
    public MotivoGlosaId getId() {
        return this.id;
    }
    
    public void setId(MotivoGlosaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false, insertable=false, updatable=false) } )
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="DESCRICAO", nullable=false, length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="DESCRICAO_DETALHADA", length=4000)
    public String getDescricaoDetalhada() {
        return this.descricaoDetalhada;
    }
    
    public void setDescricaoDetalhada(String descricaoDetalhada) {
        this.descricaoDetalhada = descricaoDetalhada;
    }

    
    @Column(name="FL_TODA_GUIA", nullable=false, length=1)
    public char getFlTodaGuia() {
        return this.flTodaGuia;
    }
    
    public void setFlTodaGuia(char flTodaGuia) {
        this.flTodaGuia = flTodaGuia;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motivoGlosa")
    public Set getProcedimentoGuias() {
        return this.procedimentoGuias;
    }
    
    public void setProcedimentoGuias(Set procedimentoGuias) {
        this.procedimentoGuias = procedimentoGuias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motivoGlosa")
    public Set getProcedimentoGuiaFechamentos() {
        return this.procedimentoGuiaFechamentos;
    }
    
    public void setProcedimentoGuiaFechamentos(Set procedimentoGuiaFechamentos) {
        this.procedimentoGuiaFechamentos = procedimentoGuiaFechamentos;
    }




}


