package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimentoTitulo generated by hbm2java
 */
@Entity
@Table(name="MOVIMENTO_TITULO"
    ,schema="DESENV"
)
public class MovimentoTitulo  implements java.io.Serializable {


     private BigDecimal id;
     private ComandoLayout comandoLayout;
     private LinhasArquivoLiquidacao linhasArquivoLiquidacao;
     private RemessaBancaria remessaBancaria;
     private Titulos titulos;
     private Empresa empresa;
     private Date dtMovimento;
     private String flStatusRegistro;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public MovimentoTitulo() {
    }

	
    public MovimentoTitulo(BigDecimal id, ComandoLayout comandoLayout, Titulos titulos, Empresa empresa, Date dtMovimento) {
        this.id = id;
        this.comandoLayout = comandoLayout;
        this.titulos = titulos;
        this.empresa = empresa;
        this.dtMovimento = dtMovimento;
    }
    public MovimentoTitulo(BigDecimal id, ComandoLayout comandoLayout, LinhasArquivoLiquidacao linhasArquivoLiquidacao, RemessaBancaria remessaBancaria, Titulos titulos, Empresa empresa, Date dtMovimento, String flStatusRegistro, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.comandoLayout = comandoLayout;
       this.linhasArquivoLiquidacao = linhasArquivoLiquidacao;
       this.remessaBancaria = remessaBancaria;
       this.titulos = titulos;
       this.empresa = empresa;
       this.dtMovimento = dtMovimento;
       this.flStatusRegistro = flStatusRegistro;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="COMLAY_FL_REMESSA_RETORNO", referencedColumnName="FL_REMESSA_RETORNO", nullable=false), 
        @JoinColumn(name="COMLAY_LAYBCO_ID", referencedColumnName="LAYBCO_ID", nullable=false), 
        @JoinColumn(name="COMLAY_NU_COMANDO", referencedColumnName="NU_COMANDO", nullable=false) } )
    public ComandoLayout getComandoLayout() {
        return this.comandoLayout;
    }
    
    public void setComandoLayout(ComandoLayout comandoLayout) {
        this.comandoLayout = comandoLayout;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="LARQLIQ_ARQLIQ_ID", referencedColumnName="ARQLIQ_ID"), 
        @JoinColumn(name="LARQLIQ_NUMERO", referencedColumnName="NUMERO") } )
    public LinhasArquivoLiquidacao getLinhasArquivoLiquidacao() {
        return this.linhasArquivoLiquidacao;
    }
    
    public void setLinhasArquivoLiquidacao(LinhasArquivoLiquidacao linhasArquivoLiquidacao) {
        this.linhasArquivoLiquidacao = linhasArquivoLiquidacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REM_ID")
    public RemessaBancaria getRemessaBancaria() {
        return this.remessaBancaria;
    }
    
    public void setRemessaBancaria(RemessaBancaria remessaBancaria) {
        this.remessaBancaria = remessaBancaria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIT_ID", nullable=false)
    public Titulos getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Titulos titulos) {
        this.titulos = titulos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_MOVIMENTO", nullable=false, length=7)
    public Date getDtMovimento() {
        return this.dtMovimento;
    }
    
    public void setDtMovimento(Date dtMovimento) {
        this.dtMovimento = dtMovimento;
    }

    
    @Column(name="FL_STATUS_REGISTRO", length=3)
    public String getFlStatusRegistro() {
        return this.flStatusRegistro;
    }
    
    public void setFlStatusRegistro(String flStatusRegistro) {
        this.flStatusRegistro = flStatusRegistro;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


