package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orcamento generated by hbm2java
 */
@Entity
@Table(name="ORCAMENTO"
    ,schema="DESENV"
)
public class Orcamento  implements java.io.Serializable {


     private BigDecimal id;
     private Fornecedor fornecedor;
     private PlanoContas planoContas;
     private Unidade unidade;
     private Empresa empresa;
     private Date data;
     private BigDecimal valorReceita;
     private BigDecimal valorDespesa;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private String descricao;

    public Orcamento() {
    }

	
    public Orcamento(BigDecimal id, Fornecedor fornecedor, PlanoContas planoContas, Unidade unidade, Empresa empresa, Date data, BigDecimal valorReceita, BigDecimal valorDespesa, String descricao) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.planoContas = planoContas;
        this.unidade = unidade;
        this.empresa = empresa;
        this.data = data;
        this.valorReceita = valorReceita;
        this.valorDespesa = valorDespesa;
        this.descricao = descricao;
    }
    public Orcamento(BigDecimal id, Fornecedor fornecedor, PlanoContas planoContas, Unidade unidade, Empresa empresa, Date data, BigDecimal valorReceita, BigDecimal valorDespesa, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, String descricao) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.planoContas = planoContas;
       this.unidade = unidade;
       this.empresa = empresa;
       this.data = data;
       this.valorReceita = valorReceita;
       this.valorDespesa = valorDespesa;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FORN_ID", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLA_ID", nullable=false)
    public PlanoContas getPlanoContas() {
        return this.planoContas;
    }
    
    public void setPlanoContas(PlanoContas planoContas) {
        this.planoContas = planoContas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA", nullable=false, length=7)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="VALOR_RECEITA", nullable=false, precision=15)
    public BigDecimal getValorReceita() {
        return this.valorReceita;
    }
    
    public void setValorReceita(BigDecimal valorReceita) {
        this.valorReceita = valorReceita;
    }

    
    @Column(name="VALOR_DESPESA", nullable=false, precision=15)
    public BigDecimal getValorDespesa() {
        return this.valorDespesa;
    }
    
    public void setValorDespesa(BigDecimal valorDespesa) {
        this.valorDespesa = valorDespesa;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="DESCRICAO", nullable=false, length=200)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


