package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PadraoMensagemErro generated by hbm2java
 */
@Entity
@Table(name="PADRAO_MENSAGEM_ERRO"
    ,schema="DESENV"
)
public class PadraoMensagemErro  implements java.io.Serializable {


     private BigDecimal cdErro;
     private String flTipoErro;
     private String dsErro;
     private String dsSolucao;
     private Byte nuTipoErro;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private String flExibir;
     private String flFormaExibicao;

    public PadraoMensagemErro() {
    }

	
    public PadraoMensagemErro(BigDecimal cdErro, String flExibir, String flFormaExibicao) {
        this.cdErro = cdErro;
        this.flExibir = flExibir;
        this.flFormaExibicao = flFormaExibicao;
    }
    public PadraoMensagemErro(BigDecimal cdErro, String flTipoErro, String dsErro, String dsSolucao, Byte nuTipoErro, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, String flExibir, String flFormaExibicao) {
       this.cdErro = cdErro;
       this.flTipoErro = flTipoErro;
       this.dsErro = dsErro;
       this.dsSolucao = dsSolucao;
       this.nuTipoErro = nuTipoErro;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flExibir = flExibir;
       this.flFormaExibicao = flFormaExibicao;
    }
   
     @Id 

    
    @Column(name="CD_ERRO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdErro() {
        return this.cdErro;
    }
    
    public void setCdErro(BigDecimal cdErro) {
        this.cdErro = cdErro;
    }

    
    @Column(name="FL_TIPO_ERRO", length=3)
    public String getFlTipoErro() {
        return this.flTipoErro;
    }
    
    public void setFlTipoErro(String flTipoErro) {
        this.flTipoErro = flTipoErro;
    }

    
    @Column(name="DS_ERRO", length=1000)
    public String getDsErro() {
        return this.dsErro;
    }
    
    public void setDsErro(String dsErro) {
        this.dsErro = dsErro;
    }

    
    @Column(name="DS_SOLUCAO", length=1000)
    public String getDsSolucao() {
        return this.dsSolucao;
    }
    
    public void setDsSolucao(String dsSolucao) {
        this.dsSolucao = dsSolucao;
    }

    
    @Column(name="NU_TIPO_ERRO", precision=2, scale=0)
    public Byte getNuTipoErro() {
        return this.nuTipoErro;
    }
    
    public void setNuTipoErro(Byte nuTipoErro) {
        this.nuTipoErro = nuTipoErro;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_EXIBIR", nullable=false, length=1)
    public String getFlExibir() {
        return this.flExibir;
    }
    
    public void setFlExibir(String flExibir) {
        this.flExibir = flExibir;
    }

    
    @Column(name="FL_FORMA_EXIBICAO", nullable=false, length=3)
    public String getFlFormaExibicao() {
        return this.flFormaExibicao;
    }
    
    public void setFlFormaExibicao(String flFormaExibicao) {
        this.flFormaExibicao = flFormaExibicao;
    }




}


