package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagamentoFechamentoConv generated by hbm2java
 */
@Entity
@Table(name="PAGAMENTO_FECHAMENTO_CONV"
    ,schema="DESENV"
)
public class PagamentoFechamentoConv  implements java.io.Serializable {


     private PagamentoFechamentoConvId id;
     private FechamentoConvenio fechamentoConvenio;
     private PagamentoProfissional pagamentoProfissional;
     private Empresa empresa;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public PagamentoFechamentoConv() {
    }

	
    public PagamentoFechamentoConv(PagamentoFechamentoConvId id, FechamentoConvenio fechamentoConvenio, PagamentoProfissional pagamentoProfissional, Empresa empresa) {
        this.id = id;
        this.fechamentoConvenio = fechamentoConvenio;
        this.pagamentoProfissional = pagamentoProfissional;
        this.empresa = empresa;
    }
    public PagamentoFechamentoConv(PagamentoFechamentoConvId id, FechamentoConvenio fechamentoConvenio, PagamentoProfissional pagamentoProfissional, Empresa empresa, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.fechamentoConvenio = fechamentoConvenio;
       this.pagamentoProfissional = pagamentoProfissional;
       this.empresa = empresa;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fecoId", column=@Column(name="FECO_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="pagproId", column=@Column(name="PAGPRO_ID", nullable=false, precision=22, scale=0) ) } )
    public PagamentoFechamentoConvId getId() {
        return this.id;
    }
    
    public void setId(PagamentoFechamentoConvId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FECO_ID", nullable=false, insertable=false, updatable=false)
    public FechamentoConvenio getFechamentoConvenio() {
        return this.fechamentoConvenio;
    }
    
    public void setFechamentoConvenio(FechamentoConvenio fechamentoConvenio) {
        this.fechamentoConvenio = fechamentoConvenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGPRO_ID", nullable=false, insertable=false, updatable=false)
    public PagamentoProfissional getPagamentoProfissional() {
        return this.pagamentoProfissional;
    }
    
    public void setPagamentoProfissional(PagamentoProfissional pagamentoProfissional) {
        this.pagamentoProfissional = pagamentoProfissional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


