package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PagamentoCobranca generated by hbm2java
 */
@Entity
@Table(name="PAGAMENTO_COBRANCA"
    ,schema="DESENV"
    , uniqueConstraints = @UniqueConstraint(columnNames="CHE_ID") 
)
public class PagamentoCobranca  implements java.io.Serializable {


     private BigDecimal id;
     private Cheque cheque;
     private Cobranca cobranca;
     private MeioPagamento meioPagamento;
     private Empresa empresa;
     private Date dtPagamento;
     private BigDecimal valorPago;
     private String flTributavel;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal nuParcelas;
     private BigDecimal valorJuros;
     private BigDecimal valorDesconto;
     private Set movimentoCaixas = new HashSet(0);

    public PagamentoCobranca() {
    }

	
    public PagamentoCobranca(BigDecimal id, Cobranca cobranca, MeioPagamento meioPagamento, Empresa empresa, Date dtPagamento, BigDecimal valorPago, String flTributavel, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal valorJuros, BigDecimal valorDesconto) {
        this.id = id;
        this.cobranca = cobranca;
        this.meioPagamento = meioPagamento;
        this.empresa = empresa;
        this.dtPagamento = dtPagamento;
        this.valorPago = valorPago;
        this.flTributavel = flTributavel;
        this.cdCriadoPor = cdCriadoPor;
        this.dtCriacao = dtCriacao;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
        this.valorJuros = valorJuros;
        this.valorDesconto = valorDesconto;
    }
    public PagamentoCobranca(BigDecimal id, Cheque cheque, Cobranca cobranca, MeioPagamento meioPagamento, Empresa empresa, Date dtPagamento, BigDecimal valorPago, String flTributavel, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal nuParcelas, BigDecimal valorJuros, BigDecimal valorDesconto, Set movimentoCaixas) {
       this.id = id;
       this.cheque = cheque;
       this.cobranca = cobranca;
       this.meioPagamento = meioPagamento;
       this.empresa = empresa;
       this.dtPagamento = dtPagamento;
       this.valorPago = valorPago;
       this.flTributavel = flTributavel;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.nuParcelas = nuParcelas;
       this.valorJuros = valorJuros;
       this.valorDesconto = valorDesconto;
       this.movimentoCaixas = movimentoCaixas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CHE_ID", unique=true)
    public Cheque getCheque() {
        return this.cheque;
    }
    
    public void setCheque(Cheque cheque) {
        this.cheque = cheque;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="COB_PARCELA", referencedColumnName="PARCELA", nullable=false), 
        @JoinColumn(name="COB_CONT_ID", referencedColumnName="CONT_ID", nullable=false) } )
    public Cobranca getCobranca() {
        return this.cobranca;
    }
    
    public void setCobranca(Cobranca cobranca) {
        this.cobranca = cobranca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MEIO_ID", nullable=false)
    public MeioPagamento getMeioPagamento() {
        return this.meioPagamento;
    }
    
    public void setMeioPagamento(MeioPagamento meioPagamento) {
        this.meioPagamento = meioPagamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_PAGAMENTO", nullable=false, length=7)
    public Date getDtPagamento() {
        return this.dtPagamento;
    }
    
    public void setDtPagamento(Date dtPagamento) {
        this.dtPagamento = dtPagamento;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="FL_TRIBUTAVEL", nullable=false, length=1)
    public String getFlTributavel() {
        return this.flTributavel;
    }
    
    public void setFlTributavel(String flTributavel) {
        this.flTributavel = flTributavel;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="NU_PARCELAS", precision=22, scale=0)
    public BigDecimal getNuParcelas() {
        return this.nuParcelas;
    }
    
    public void setNuParcelas(BigDecimal nuParcelas) {
        this.nuParcelas = nuParcelas;
    }

    
    @Column(name="VALOR_JUROS", nullable=false, precision=15)
    public BigDecimal getValorJuros() {
        return this.valorJuros;
    }
    
    public void setValorJuros(BigDecimal valorJuros) {
        this.valorJuros = valorJuros;
    }

    
    @Column(name="VALOR_DESCONTO", nullable=false, precision=15)
    public BigDecimal getValorDesconto() {
        return this.valorDesconto;
    }
    
    public void setValorDesconto(BigDecimal valorDesconto) {
        this.valorDesconto = valorDesconto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagamentoCobranca")
    public Set getMovimentoCaixas() {
        return this.movimentoCaixas;
    }
    
    public void setMovimentoCaixas(Set movimentoCaixas) {
        this.movimentoCaixas = movimentoCaixas;
    }




}


