package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagamentoFechamentoConvId generated by hbm2java
 */
@Embeddable
public class PagamentoFechamentoConvId  implements java.io.Serializable {


     private BigDecimal fecoId;
     private BigDecimal pagproId;

    public PagamentoFechamentoConvId() {
    }

    public PagamentoFechamentoConvId(BigDecimal fecoId, BigDecimal pagproId) {
       this.fecoId = fecoId;
       this.pagproId = pagproId;
    }
   


    @Column(name="FECO_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getFecoId() {
        return this.fecoId;
    }
    
    public void setFecoId(BigDecimal fecoId) {
        this.fecoId = fecoId;
    }


    @Column(name="PAGPRO_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getPagproId() {
        return this.pagproId;
    }
    
    public void setPagproId(BigDecimal pagproId) {
        this.pagproId = pagproId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagamentoFechamentoConvId) ) return false;
		 PagamentoFechamentoConvId castOther = ( PagamentoFechamentoConvId ) other; 
         
		 return ( (this.getFecoId()==castOther.getFecoId()) || ( this.getFecoId()!=null && castOther.getFecoId()!=null && this.getFecoId().equals(castOther.getFecoId()) ) )
 && ( (this.getPagproId()==castOther.getPagproId()) || ( this.getPagproId()!=null && castOther.getPagproId()!=null && this.getPagproId().equals(castOther.getPagproId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecoId() == null ? 0 : this.getFecoId().hashCode() );
         result = 37 * result + ( getPagproId() == null ? 0 : this.getPagproId().hashCode() );
         return result;
   }   


}


