package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagamentoPedido generated by hbm2java
 */
@Entity
@Table(name="PAGAMENTO_PEDIDO"
    ,schema="DESENV"
)
public class PagamentoPedido  implements java.io.Serializable {


     private BigDecimal id;
     private Fornecedor fornecedor;
     private Empresa empresa;
     private Date dtPagamento;
     private BigDecimal valorDinheiro;
     private BigDecimal valorTotal;
     private String descricao;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set chequePagamentoPedidos = new HashSet(0);
     private Set pedidoPagamentoPedidos = new HashSet(0);

    public PagamentoPedido() {
    }

	
    public PagamentoPedido(BigDecimal id, Fornecedor fornecedor, Empresa empresa, Date dtPagamento, BigDecimal valorDinheiro, BigDecimal valorTotal) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.empresa = empresa;
        this.dtPagamento = dtPagamento;
        this.valorDinheiro = valorDinheiro;
        this.valorTotal = valorTotal;
    }
    public PagamentoPedido(BigDecimal id, Fornecedor fornecedor, Empresa empresa, Date dtPagamento, BigDecimal valorDinheiro, BigDecimal valorTotal, String descricao, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set chequePagamentoPedidos, Set pedidoPagamentoPedidos) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.empresa = empresa;
       this.dtPagamento = dtPagamento;
       this.valorDinheiro = valorDinheiro;
       this.valorTotal = valorTotal;
       this.descricao = descricao;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.chequePagamentoPedidos = chequePagamentoPedidos;
       this.pedidoPagamentoPedidos = pedidoPagamentoPedidos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FORN_ID", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_PAGAMENTO", nullable=false, length=7)
    public Date getDtPagamento() {
        return this.dtPagamento;
    }
    
    public void setDtPagamento(Date dtPagamento) {
        this.dtPagamento = dtPagamento;
    }

    
    @Column(name="VALOR_DINHEIRO", nullable=false, precision=15)
    public BigDecimal getValorDinheiro() {
        return this.valorDinheiro;
    }
    
    public void setValorDinheiro(BigDecimal valorDinheiro) {
        this.valorDinheiro = valorDinheiro;
    }

    
    @Column(name="VALOR_TOTAL", nullable=false, precision=15)
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="DESCRICAO", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagamentoPedido")
    public Set getChequePagamentoPedidos() {
        return this.chequePagamentoPedidos;
    }
    
    public void setChequePagamentoPedidos(Set chequePagamentoPedidos) {
        this.chequePagamentoPedidos = chequePagamentoPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagamentoPedido")
    public Set getPedidoPagamentoPedidos() {
        return this.pedidoPagamentoPedidos;
    }
    
    public void setPedidoPagamentoPedidos(Set pedidoPagamentoPedidos) {
        this.pedidoPagamentoPedidos = pedidoPagamentoPedidos;
    }




}


