package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagamentosTitulos generated by hbm2java
 */
@Entity
@Table(name="PAGAMENTOS_TITULOS"
    ,schema="DESENV"
)
public class PagamentosTitulos  implements java.io.Serializable {


     private BigDecimal id;
     private LinhasArquivoLiquidacao linhasArquivoLiquidacao;
     private Titulos titulos;
     private Empresa empresa;
     private Date dataPagamento;
     private Date dataCredito;
     private BigDecimal valorPago;
     private BigDecimal valorJuros;
     private BigDecimal valorDesconto;
     private BigDecimal valorOutrosRecebimentos;
     private String ocorrencia;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set pagamentoPacientes = new HashSet(0);
     private Set movimentoCaixas = new HashSet(0);

    public PagamentosTitulos() {
    }

	
    public PagamentosTitulos(BigDecimal id, Titulos titulos, Empresa empresa, Date dataPagamento, Date dataCredito, BigDecimal valorPago, BigDecimal valorJuros, BigDecimal valorDesconto, BigDecimal valorOutrosRecebimentos) {
        this.id = id;
        this.titulos = titulos;
        this.empresa = empresa;
        this.dataPagamento = dataPagamento;
        this.dataCredito = dataCredito;
        this.valorPago = valorPago;
        this.valorJuros = valorJuros;
        this.valorDesconto = valorDesconto;
        this.valorOutrosRecebimentos = valorOutrosRecebimentos;
    }
    public PagamentosTitulos(BigDecimal id, LinhasArquivoLiquidacao linhasArquivoLiquidacao, Titulos titulos, Empresa empresa, Date dataPagamento, Date dataCredito, BigDecimal valorPago, BigDecimal valorJuros, BigDecimal valorDesconto, BigDecimal valorOutrosRecebimentos, String ocorrencia, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set pagamentoPacientes, Set movimentoCaixas) {
       this.id = id;
       this.linhasArquivoLiquidacao = linhasArquivoLiquidacao;
       this.titulos = titulos;
       this.empresa = empresa;
       this.dataPagamento = dataPagamento;
       this.dataCredito = dataCredito;
       this.valorPago = valorPago;
       this.valorJuros = valorJuros;
       this.valorDesconto = valorDesconto;
       this.valorOutrosRecebimentos = valorOutrosRecebimentos;
       this.ocorrencia = ocorrencia;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.pagamentoPacientes = pagamentoPacientes;
       this.movimentoCaixas = movimentoCaixas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="LARQLIQ_ARQLIQ_ID", referencedColumnName="ARQLIQ_ID"), 
        @JoinColumn(name="LARQLIQ_NUMERO", referencedColumnName="NUMERO") } )
    public LinhasArquivoLiquidacao getLinhasArquivoLiquidacao() {
        return this.linhasArquivoLiquidacao;
    }
    
    public void setLinhasArquivoLiquidacao(LinhasArquivoLiquidacao linhasArquivoLiquidacao) {
        this.linhasArquivoLiquidacao = linhasArquivoLiquidacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIT_ID", nullable=false)
    public Titulos getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Titulos titulos) {
        this.titulos = titulos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_PAGAMENTO", nullable=false, length=7)
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_CREDITO", nullable=false, length=7)
    public Date getDataCredito() {
        return this.dataCredito;
    }
    
    public void setDataCredito(Date dataCredito) {
        this.dataCredito = dataCredito;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=17)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VALOR_JUROS", nullable=false, precision=17)
    public BigDecimal getValorJuros() {
        return this.valorJuros;
    }
    
    public void setValorJuros(BigDecimal valorJuros) {
        this.valorJuros = valorJuros;
    }

    
    @Column(name="VALOR_DESCONTO", nullable=false, precision=17)
    public BigDecimal getValorDesconto() {
        return this.valorDesconto;
    }
    
    public void setValorDesconto(BigDecimal valorDesconto) {
        this.valorDesconto = valorDesconto;
    }

    
    @Column(name="VALOR_OUTROS_RECEBIMENTOS", nullable=false, precision=17)
    public BigDecimal getValorOutrosRecebimentos() {
        return this.valorOutrosRecebimentos;
    }
    
    public void setValorOutrosRecebimentos(BigDecimal valorOutrosRecebimentos) {
        this.valorOutrosRecebimentos = valorOutrosRecebimentos;
    }

    
    @Column(name="OCORRENCIA", length=4000)
    public String getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(String ocorrencia) {
        this.ocorrencia = ocorrencia;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagamentosTitulos")
    public Set getPagamentoPacientes() {
        return this.pagamentoPacientes;
    }
    
    public void setPagamentoPacientes(Set pagamentoPacientes) {
        this.pagamentoPacientes = pagamentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pagamentosTitulos")
    public Set getMovimentoCaixas() {
        return this.movimentoCaixas;
    }
    
    public void setMovimentoCaixas(Set movimentoCaixas) {
        this.movimentoCaixas = movimentoCaixas;
    }




}


