package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Parcelamento generated by hbm2java
 */
@Entity
@Table(name="PARCELAMENTO"
    ,schema="DESENV"
    , uniqueConstraints = @UniqueConstraint(columnNames={"PARCELA", "FORPA_ID"}) 
)
public class Parcelamento  implements java.io.Serializable {


     private BigDecimal id;
     private FormaPagamento formaPagamento;
     private Empresa empresa;
     private byte parcela;
     private Date dtVencimento;
     private BigDecimal valorParcela;
     private BigDecimal valorRecebido;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public Parcelamento() {
    }

	
    public Parcelamento(BigDecimal id, FormaPagamento formaPagamento, Empresa empresa, byte parcela, Date dtVencimento, BigDecimal valorParcela, BigDecimal valorRecebido) {
        this.id = id;
        this.formaPagamento = formaPagamento;
        this.empresa = empresa;
        this.parcela = parcela;
        this.dtVencimento = dtVencimento;
        this.valorParcela = valorParcela;
        this.valorRecebido = valorRecebido;
    }
    public Parcelamento(BigDecimal id, FormaPagamento formaPagamento, Empresa empresa, byte parcela, Date dtVencimento, BigDecimal valorParcela, BigDecimal valorRecebido, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.formaPagamento = formaPagamento;
       this.empresa = empresa;
       this.parcela = parcela;
       this.dtVencimento = dtVencimento;
       this.valorParcela = valorParcela;
       this.valorRecebido = valorRecebido;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FORPA_ID", nullable=false)
    public FormaPagamento getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(FormaPagamento formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="PARCELA", nullable=false, precision=2, scale=0)
    public byte getParcela() {
        return this.parcela;
    }
    
    public void setParcela(byte parcela) {
        this.parcela = parcela;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_VENCIMENTO", nullable=false, length=7)
    public Date getDtVencimento() {
        return this.dtVencimento;
    }
    
    public void setDtVencimento(Date dtVencimento) {
        this.dtVencimento = dtVencimento;
    }

    
    @Column(name="VALOR_PARCELA", nullable=false, precision=15)
    public BigDecimal getValorParcela() {
        return this.valorParcela;
    }
    
    public void setValorParcela(BigDecimal valorParcela) {
        this.valorParcela = valorParcela;
    }

    
    @Column(name="VALOR_RECEBIDO", nullable=false, precision=15)
    public BigDecimal getValorRecebido() {
        return this.valorRecebido;
    }
    
    public void setValorRecebido(BigDecimal valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


