package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PedidoPagamentoPedidoId generated by hbm2java
 */
@Embeddable
public class PedidoPagamentoPedidoId  implements java.io.Serializable {


     private BigDecimal pedId;
     private BigDecimal pagpeId;

    public PedidoPagamentoPedidoId() {
    }

    public PedidoPagamentoPedidoId(BigDecimal pedId, BigDecimal pagpeId) {
       this.pedId = pedId;
       this.pagpeId = pagpeId;
    }
   


    @Column(name="PED_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getPedId() {
        return this.pedId;
    }
    
    public void setPedId(BigDecimal pedId) {
        this.pedId = pedId;
    }


    @Column(name="PAGPE_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getPagpeId() {
        return this.pagpeId;
    }
    
    public void setPagpeId(BigDecimal pagpeId) {
        this.pagpeId = pagpeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidoPagamentoPedidoId) ) return false;
		 PedidoPagamentoPedidoId castOther = ( PedidoPagamentoPedidoId ) other; 
         
		 return ( (this.getPedId()==castOther.getPedId()) || ( this.getPedId()!=null && castOther.getPedId()!=null && this.getPedId().equals(castOther.getPedId()) ) )
 && ( (this.getPagpeId()==castOther.getPagpeId()) || ( this.getPagpeId()!=null && castOther.getPagpeId()!=null && this.getPagpeId().equals(castOther.getPagpeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPedId() == null ? 0 : this.getPedId().hashCode() );
         result = 37 * result + ( getPagpeId() == null ? 0 : this.getPagpeId().hashCode() );
         return result;
   }   


}


