package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="PEDIDO"
    ,schema="DESENV"
    , uniqueConstraints = @UniqueConstraint(columnNames={"NUMERO", "FORN_ID"}) 
)
public class Pedido  implements java.io.Serializable {


     private BigDecimal id;
     private Fornecedor fornecedor;
     private PlanoContas planoContas;
     private Empresa empresa;
     private BigDecimal numero;
     private Date dtPedido;
     private BigDecimal valorPedido;
     private BigDecimal valorPago;
     private String descricao;
     private BigDecimal valorAjuste;
     private char flPago;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set contaPagars = new HashSet(0);
     private Set materialPedidos = new HashSet(0);
     private Set pedidoPagamentoPedidos = new HashSet(0);
     private Set embalagemPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(BigDecimal id, Fornecedor fornecedor, PlanoContas planoContas, Empresa empresa, BigDecimal numero, Date dtPedido, BigDecimal valorPedido, BigDecimal valorPago, String descricao, BigDecimal valorAjuste, char flPago) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.planoContas = planoContas;
        this.empresa = empresa;
        this.numero = numero;
        this.dtPedido = dtPedido;
        this.valorPedido = valorPedido;
        this.valorPago = valorPago;
        this.descricao = descricao;
        this.valorAjuste = valorAjuste;
        this.flPago = flPago;
    }
    public Pedido(BigDecimal id, Fornecedor fornecedor, PlanoContas planoContas, Empresa empresa, BigDecimal numero, Date dtPedido, BigDecimal valorPedido, BigDecimal valorPago, String descricao, BigDecimal valorAjuste, char flPago, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set contaPagars, Set materialPedidos, Set pedidoPagamentoPedidos, Set embalagemPedidos) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.planoContas = planoContas;
       this.empresa = empresa;
       this.numero = numero;
       this.dtPedido = dtPedido;
       this.valorPedido = valorPedido;
       this.valorPago = valorPago;
       this.descricao = descricao;
       this.valorAjuste = valorAjuste;
       this.flPago = flPago;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.contaPagars = contaPagars;
       this.materialPedidos = materialPedidos;
       this.pedidoPagamentoPedidos = pedidoPagamentoPedidos;
       this.embalagemPedidos = embalagemPedidos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FORN_ID", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLA_ID", nullable=false)
    public PlanoContas getPlanoContas() {
        return this.planoContas;
    }
    
    public void setPlanoContas(PlanoContas planoContas) {
        this.planoContas = planoContas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NUMERO", nullable=false, precision=22, scale=0)
    public BigDecimal getNumero() {
        return this.numero;
    }
    
    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_PEDIDO", nullable=false, length=7)
    public Date getDtPedido() {
        return this.dtPedido;
    }
    
    public void setDtPedido(Date dtPedido) {
        this.dtPedido = dtPedido;
    }

    
    @Column(name="VALOR_PEDIDO", nullable=false, precision=15)
    public BigDecimal getValorPedido() {
        return this.valorPedido;
    }
    
    public void setValorPedido(BigDecimal valorPedido) {
        this.valorPedido = valorPedido;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="DESCRICAO", nullable=false, length=4000)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="VALOR_AJUSTE", nullable=false, precision=15)
    public BigDecimal getValorAjuste() {
        return this.valorAjuste;
    }
    
    public void setValorAjuste(BigDecimal valorAjuste) {
        this.valorAjuste = valorAjuste;
    }

    
    @Column(name="FL_PAGO", nullable=false, length=1)
    public char getFlPago() {
        return this.flPago;
    }
    
    public void setFlPago(char flPago) {
        this.flPago = flPago;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getContaPagars() {
        return this.contaPagars;
    }
    
    public void setContaPagars(Set contaPagars) {
        this.contaPagars = contaPagars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getMaterialPedidos() {
        return this.materialPedidos;
    }
    
    public void setMaterialPedidos(Set materialPedidos) {
        this.materialPedidos = materialPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getPedidoPagamentoPedidos() {
        return this.pedidoPagamentoPedidos;
    }
    
    public void setPedidoPagamentoPedidos(Set pedidoPagamentoPedidos) {
        this.pedidoPagamentoPedidos = pedidoPagamentoPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getEmbalagemPedidos() {
        return this.embalagemPedidos;
    }
    
    public void setEmbalagemPedidos(Set embalagemPedidos) {
        this.embalagemPedidos = embalagemPedidos;
    }




}


