package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanoContas generated by hbm2java
 */
@Entity
@Table(name="PLANO_CONTAS"
    ,schema="DESENV"
)
public class PlanoContas  implements java.io.Serializable {


     private BigDecimal id;
     private PlanoContas planoContas;
     private Empresa empresa;
     private String nome;
     private String ativo;
     private String flAutomatico;
     private String flTipo;
     private String flTransferencia;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private String flEncargo;
     private Set linhaNotaFiscals = new HashSet(0);
     private Set items = new HashSet(0);
     private Set meioPagamentosForPlaIdJuros = new HashSet(0);
     private Set contaPagars = new HashSet(0);
     private Set meioPagamentosForPlaId = new HashSet(0);
     private Set movimentoCaixas = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set orcamentos = new HashSet(0);
     private Set planoContases = new HashSet(0);
     private Set situacaoCheques = new HashSet(0);

    public PlanoContas() {
    }

	
    public PlanoContas(BigDecimal id, Empresa empresa, String nome, String ativo, String flAutomatico, String flTipo, String flTransferencia, String flEncargo) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.ativo = ativo;
        this.flAutomatico = flAutomatico;
        this.flTipo = flTipo;
        this.flTransferencia = flTransferencia;
        this.flEncargo = flEncargo;
    }
    public PlanoContas(BigDecimal id, PlanoContas planoContas, Empresa empresa, String nome, String ativo, String flAutomatico, String flTipo, String flTransferencia, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, String flEncargo, Set linhaNotaFiscals, Set items, Set meioPagamentosForPlaIdJuros, Set contaPagars, Set meioPagamentosForPlaId, Set movimentoCaixas, Set pedidos, Set orcamentos, Set planoContases, Set situacaoCheques) {
       this.id = id;
       this.planoContas = planoContas;
       this.empresa = empresa;
       this.nome = nome;
       this.ativo = ativo;
       this.flAutomatico = flAutomatico;
       this.flTipo = flTipo;
       this.flTransferencia = flTransferencia;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flEncargo = flEncargo;
       this.linhaNotaFiscals = linhaNotaFiscals;
       this.items = items;
       this.meioPagamentosForPlaIdJuros = meioPagamentosForPlaIdJuros;
       this.contaPagars = contaPagars;
       this.meioPagamentosForPlaId = meioPagamentosForPlaId;
       this.movimentoCaixas = movimentoCaixas;
       this.pedidos = pedidos;
       this.orcamentos = orcamentos;
       this.planoContases = planoContases;
       this.situacaoCheques = situacaoCheques;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLA_ID")
    public PlanoContas getPlanoContas() {
        return this.planoContas;
    }
    
    public void setPlanoContas(PlanoContas planoContas) {
        this.planoContas = planoContas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="ATIVO", nullable=false, length=1)
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="FL_AUTOMATICO", nullable=false, length=1)
    public String getFlAutomatico() {
        return this.flAutomatico;
    }
    
    public void setFlAutomatico(String flAutomatico) {
        this.flAutomatico = flAutomatico;
    }

    
    @Column(name="FL_TIPO", nullable=false, length=1)
    public String getFlTipo() {
        return this.flTipo;
    }
    
    public void setFlTipo(String flTipo) {
        this.flTipo = flTipo;
    }

    
    @Column(name="FL_TRANSFERENCIA", nullable=false, length=1)
    public String getFlTransferencia() {
        return this.flTransferencia;
    }
    
    public void setFlTransferencia(String flTransferencia) {
        this.flTransferencia = flTransferencia;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_ENCARGO", nullable=false, length=1)
    public String getFlEncargo() {
        return this.flEncargo;
    }
    
    public void setFlEncargo(String flEncargo) {
        this.flEncargo = flEncargo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getLinhaNotaFiscals() {
        return this.linhaNotaFiscals;
    }
    
    public void setLinhaNotaFiscals(Set linhaNotaFiscals) {
        this.linhaNotaFiscals = linhaNotaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContasByPlaIdJuros")
    public Set getMeioPagamentosForPlaIdJuros() {
        return this.meioPagamentosForPlaIdJuros;
    }
    
    public void setMeioPagamentosForPlaIdJuros(Set meioPagamentosForPlaIdJuros) {
        this.meioPagamentosForPlaIdJuros = meioPagamentosForPlaIdJuros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getContaPagars() {
        return this.contaPagars;
    }
    
    public void setContaPagars(Set contaPagars) {
        this.contaPagars = contaPagars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContasByPlaId")
    public Set getMeioPagamentosForPlaId() {
        return this.meioPagamentosForPlaId;
    }
    
    public void setMeioPagamentosForPlaId(Set meioPagamentosForPlaId) {
        this.meioPagamentosForPlaId = meioPagamentosForPlaId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getMovimentoCaixas() {
        return this.movimentoCaixas;
    }
    
    public void setMovimentoCaixas(Set movimentoCaixas) {
        this.movimentoCaixas = movimentoCaixas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Set orcamentos) {
        this.orcamentos = orcamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getPlanoContases() {
        return this.planoContases;
    }
    
    public void setPlanoContases(Set planoContases) {
        this.planoContases = planoContases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoContas")
    public Set getSituacaoCheques() {
        return this.situacaoCheques;
    }
    
    public void setSituacaoCheques(Set situacaoCheques) {
        this.situacaoCheques = situacaoCheques;
    }




}


