package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PortadorUsuario generated by hbm2java
 */
@Entity
@Table(name="PORTADOR_USUARIO"
    ,schema="DESENV"
)
public class PortadorUsuario  implements java.io.Serializable {


     private PortadorUsuarioId id;
     private GrupoUsuario grupoUsuario;
     private Portador portador;
     private Empresa empresa;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public PortadorUsuario() {
    }

	
    public PortadorUsuario(PortadorUsuarioId id, GrupoUsuario grupoUsuario, Portador portador, Empresa empresa) {
        this.id = id;
        this.grupoUsuario = grupoUsuario;
        this.portador = portador;
        this.empresa = empresa;
    }
    public PortadorUsuario(PortadorUsuarioId id, GrupoUsuario grupoUsuario, Portador portador, Empresa empresa, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.grupoUsuario = grupoUsuario;
       this.portador = portador;
       this.empresa = empresa;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="grusCdUsuario", column=@Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="porId", column=@Column(name="POR_ID", nullable=false, precision=10, scale=0) ) } )
    public PortadorUsuarioId getId() {
        return this.id;
    }
    
    public void setId(PortadorUsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUS_CD_USUARIO", nullable=false, insertable=false, updatable=false)
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="POR_ID", nullable=false, insertable=false, updatable=false)
    public Portador getPortador() {
        return this.portador;
    }
    
    public void setPortador(Portador portador) {
        this.portador = portador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


