package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Portador generated by hbm2java
 */
@Entity
@Table(name="PORTADOR"
    ,schema="DESENV"
)
public class Portador  implements java.io.Serializable {


     private long id;
     private Conta conta;
     private GrupoUsuario grupoUsuario;
     private Unidade unidade;
     private Empresa empresa;
     private String nome;
     private char flAtivo;
     private String flTipo;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set movimentacaoCheques = new HashSet(0);
     private Set portadorUsuarios = new HashSet(0);
     private Set cheques = new HashSet(0);

    public Portador() {
    }

	
    public Portador(long id, Unidade unidade, Empresa empresa, String nome, char flAtivo, String flTipo) {
        this.id = id;
        this.unidade = unidade;
        this.empresa = empresa;
        this.nome = nome;
        this.flAtivo = flAtivo;
        this.flTipo = flTipo;
    }
    public Portador(long id, Conta conta, GrupoUsuario grupoUsuario, Unidade unidade, Empresa empresa, String nome, char flAtivo, String flTipo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set movimentacaoCheques, Set portadorUsuarios, Set cheques) {
       this.id = id;
       this.conta = conta;
       this.grupoUsuario = grupoUsuario;
       this.unidade = unidade;
       this.empresa = empresa;
       this.nome = nome;
       this.flAtivo = flAtivo;
       this.flTipo = flTipo;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.movimentacaoCheques = movimentacaoCheques;
       this.portadorUsuarios = portadorUsuarios;
       this.cheques = cheques;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CON_ID")
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUS_CD_USUARIO")
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public char getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(char flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="FL_TIPO", nullable=false, length=3)
    public String getFlTipo() {
        return this.flTipo;
    }
    
    public void setFlTipo(String flTipo) {
        this.flTipo = flTipo;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="portador")
    public Set getMovimentacaoCheques() {
        return this.movimentacaoCheques;
    }
    
    public void setMovimentacaoCheques(Set movimentacaoCheques) {
        this.movimentacaoCheques = movimentacaoCheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="portador")
    public Set getPortadorUsuarios() {
        return this.portadorUsuarios;
    }
    
    public void setPortadorUsuarios(Set portadorUsuarios) {
        this.portadorUsuarios = portadorUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="portador")
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }




}


