package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcedimentoGuia generated by hbm2java
 */
@Entity
@Table(name="PROCEDIMENTO_GUIA"
    ,schema="DESENV"
)
public class ProcedimentoGuia  implements java.io.Serializable {


     private BigDecimal id;
     private GuiaPaciente guiaPaciente;
     private ListaRegiaoProcedimento listaRegiaoProcedimento;
     private MotivoGlosa motivoGlosa;
     private Procedimento procedimento;
     private Empresa empresa;
     private Date dtProcedimento;
     private BigDecimal valorRepasse;
     private BigDecimal valorCoparticipacao;
     private BigDecimal vlReceberProfissional;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal vlTributacao;
     private String face;
     private ProcedimentoGuiaFechamento procedimentoGuiaFechamento;

    public ProcedimentoGuia() {
    }

	
    public ProcedimentoGuia(BigDecimal id, GuiaPaciente guiaPaciente, Procedimento procedimento, Empresa empresa, Date dtProcedimento, BigDecimal valorRepasse, BigDecimal valorCoparticipacao, BigDecimal vlReceberProfissional, BigDecimal vlTributacao) {
        this.id = id;
        this.guiaPaciente = guiaPaciente;
        this.procedimento = procedimento;
        this.empresa = empresa;
        this.dtProcedimento = dtProcedimento;
        this.valorRepasse = valorRepasse;
        this.valorCoparticipacao = valorCoparticipacao;
        this.vlReceberProfissional = vlReceberProfissional;
        this.vlTributacao = vlTributacao;
    }
    public ProcedimentoGuia(BigDecimal id, GuiaPaciente guiaPaciente, ListaRegiaoProcedimento listaRegiaoProcedimento, MotivoGlosa motivoGlosa, Procedimento procedimento, Empresa empresa, Date dtProcedimento, BigDecimal valorRepasse, BigDecimal valorCoparticipacao, BigDecimal vlReceberProfissional, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal vlTributacao, String face, ProcedimentoGuiaFechamento procedimentoGuiaFechamento) {
       this.id = id;
       this.guiaPaciente = guiaPaciente;
       this.listaRegiaoProcedimento = listaRegiaoProcedimento;
       this.motivoGlosa = motivoGlosa;
       this.procedimento = procedimento;
       this.empresa = empresa;
       this.dtProcedimento = dtProcedimento;
       this.valorRepasse = valorRepasse;
       this.valorCoparticipacao = valorCoparticipacao;
       this.vlReceberProfissional = vlReceberProfissional;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.vlTributacao = vlTributacao;
       this.face = face;
       this.procedimentoGuiaFechamento = procedimentoGuiaFechamento;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GUIA_ID", nullable=false)
    public GuiaPaciente getGuiaPaciente() {
        return this.guiaPaciente;
    }
    
    public void setGuiaPaciente(GuiaPaciente guiaPaciente) {
        this.guiaPaciente = guiaPaciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="LIREP_REGIAO", referencedColumnName="REGIAO"), 
        @JoinColumn(name="LIREP_REGP_ID", referencedColumnName="REGP_ID") } )
    public ListaRegiaoProcedimento getListaRegiaoProcedimento() {
        return this.listaRegiaoProcedimento;
    }
    
    public void setListaRegiaoProcedimento(ListaRegiaoProcedimento listaRegiaoProcedimento) {
        this.listaRegiaoProcedimento = listaRegiaoProcedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="MOGLO_CODIGO", referencedColumnName="CODIGO"), 
        @JoinColumn(name="MOGLO_CONV_ID", referencedColumnName="CONV_ID") } )
    public MotivoGlosa getMotivoGlosa() {
        return this.motivoGlosa;
    }
    
    public void setMotivoGlosa(MotivoGlosa motivoGlosa) {
        this.motivoGlosa = motivoGlosa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCEDIMENTO_ID", nullable=false)
    public Procedimento getProcedimento() {
        return this.procedimento;
    }
    
    public void setProcedimento(Procedimento procedimento) {
        this.procedimento = procedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_PROCEDIMENTO", nullable=false, length=7)
    public Date getDtProcedimento() {
        return this.dtProcedimento;
    }
    
    public void setDtProcedimento(Date dtProcedimento) {
        this.dtProcedimento = dtProcedimento;
    }

    
    @Column(name="VALOR_REPASSE", nullable=false, precision=15)
    public BigDecimal getValorRepasse() {
        return this.valorRepasse;
    }
    
    public void setValorRepasse(BigDecimal valorRepasse) {
        this.valorRepasse = valorRepasse;
    }

    
    @Column(name="VALOR_COPARTICIPACAO", nullable=false, precision=15)
    public BigDecimal getValorCoparticipacao() {
        return this.valorCoparticipacao;
    }
    
    public void setValorCoparticipacao(BigDecimal valorCoparticipacao) {
        this.valorCoparticipacao = valorCoparticipacao;
    }

    
    @Column(name="VL_RECEBER_PROFISSIONAL", nullable=false, precision=15)
    public BigDecimal getVlReceberProfissional() {
        return this.vlReceberProfissional;
    }
    
    public void setVlReceberProfissional(BigDecimal vlReceberProfissional) {
        this.vlReceberProfissional = vlReceberProfissional;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="VL_TRIBUTACAO", nullable=false, precision=15)
    public BigDecimal getVlTributacao() {
        return this.vlTributacao;
    }
    
    public void setVlTributacao(BigDecimal vlTributacao) {
        this.vlTributacao = vlTributacao;
    }

    
    @Column(name="FACE", length=10)
    public String getFace() {
        return this.face;
    }
    
    public void setFace(String face) {
        this.face = face;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="procedimentoGuia")
    public ProcedimentoGuiaFechamento getProcedimentoGuiaFechamento() {
        return this.procedimentoGuiaFechamento;
    }
    
    public void setProcedimentoGuiaFechamento(ProcedimentoGuiaFechamento procedimentoGuiaFechamento) {
        this.procedimentoGuiaFechamento = procedimentoGuiaFechamento;
    }




}


