package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Procedimento generated by hbm2java
 */
@Entity
@Table(name="PROCEDIMENTO"
    ,schema="DESENV"
)
public class Procedimento  implements java.io.Serializable {


     private BigDecimal id;
     private CategoriaProcedimento categoriaProcedimento;
     private Especialidade especialidade;
     private RegiaoProcedimento regiaoProcedimento;
     private Empresa empresa;
     private String nome;
     private BigDecimal valorBrutoOld;
     private BigDecimal custoMaterial;
     private BigDecimal custoLaboratorial;
     private BigDecimal outrosCustos;
     private short tempoDuracao;
     private short numeroConsultas;
     private char flAtivo;
     private char flFalta;
     private BigDecimal valorEncargoOld;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private Set materialProcedimentos = new HashSet(0);
     private Set procedimentoUnidades = new HashSet(0);
     private Set procedimentoContratos = new HashSet(0);
     private Set procedimentoGuias = new HashSet(0);
     private Set procedimentoGrupos = new HashSet(0);
     private Set procedimentoPacientes = new HashSet(0);
     private Set tabelaConvenios = new HashSet(0);
     private Set itemProcedimentos = new HashSet(0);
     private Set repasseProfissionals = new HashSet(0);

    public Procedimento() {
    }

	
    public Procedimento(BigDecimal id, CategoriaProcedimento categoriaProcedimento, Especialidade especialidade, Empresa empresa, String nome, BigDecimal valorBrutoOld, BigDecimal custoMaterial, BigDecimal custoLaboratorial, BigDecimal outrosCustos, short tempoDuracao, short numeroConsultas, char flAtivo, char flFalta) {
        this.id = id;
        this.categoriaProcedimento = categoriaProcedimento;
        this.especialidade = especialidade;
        this.empresa = empresa;
        this.nome = nome;
        this.valorBrutoOld = valorBrutoOld;
        this.custoMaterial = custoMaterial;
        this.custoLaboratorial = custoLaboratorial;
        this.outrosCustos = outrosCustos;
        this.tempoDuracao = tempoDuracao;
        this.numeroConsultas = numeroConsultas;
        this.flAtivo = flAtivo;
        this.flFalta = flFalta;
    }
    public Procedimento(BigDecimal id, CategoriaProcedimento categoriaProcedimento, Especialidade especialidade, RegiaoProcedimento regiaoProcedimento, Empresa empresa, String nome, BigDecimal valorBrutoOld, BigDecimal custoMaterial, BigDecimal custoLaboratorial, BigDecimal outrosCustos, short tempoDuracao, short numeroConsultas, char flAtivo, char flFalta, BigDecimal valorEncargoOld, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, Set materialProcedimentos, Set procedimentoUnidades, Set procedimentoContratos, Set procedimentoGuias, Set procedimentoGrupos, Set procedimentoPacientes, Set tabelaConvenios, Set itemProcedimentos, Set repasseProfissionals) {
       this.id = id;
       this.categoriaProcedimento = categoriaProcedimento;
       this.especialidade = especialidade;
       this.regiaoProcedimento = regiaoProcedimento;
       this.empresa = empresa;
       this.nome = nome;
       this.valorBrutoOld = valorBrutoOld;
       this.custoMaterial = custoMaterial;
       this.custoLaboratorial = custoLaboratorial;
       this.outrosCustos = outrosCustos;
       this.tempoDuracao = tempoDuracao;
       this.numeroConsultas = numeroConsultas;
       this.flAtivo = flAtivo;
       this.flFalta = flFalta;
       this.valorEncargoOld = valorEncargoOld;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.materialProcedimentos = materialProcedimentos;
       this.procedimentoUnidades = procedimentoUnidades;
       this.procedimentoContratos = procedimentoContratos;
       this.procedimentoGuias = procedimentoGuias;
       this.procedimentoGrupos = procedimentoGrupos;
       this.procedimentoPacientes = procedimentoPacientes;
       this.tabelaConvenios = tabelaConvenios;
       this.itemProcedimentos = itemProcedimentos;
       this.repasseProfissionals = repasseProfissionals;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATPRO_ID", nullable=false)
    public CategoriaProcedimento getCategoriaProcedimento() {
        return this.categoriaProcedimento;
    }
    
    public void setCategoriaProcedimento(CategoriaProcedimento categoriaProcedimento) {
        this.categoriaProcedimento = categoriaProcedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ESP_ID", referencedColumnName="ID", nullable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false) } )
    public Especialidade getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(Especialidade especialidade) {
        this.especialidade = especialidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGP_ID")
    public RegiaoProcedimento getRegiaoProcedimento() {
        return this.regiaoProcedimento;
    }
    
    public void setRegiaoProcedimento(RegiaoProcedimento regiaoProcedimento) {
        this.regiaoProcedimento = regiaoProcedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="VALOR_BRUTO_OLD", nullable=false, precision=15)
    public BigDecimal getValorBrutoOld() {
        return this.valorBrutoOld;
    }
    
    public void setValorBrutoOld(BigDecimal valorBrutoOld) {
        this.valorBrutoOld = valorBrutoOld;
    }

    
    @Column(name="CUSTO_MATERIAL", nullable=false, precision=15)
    public BigDecimal getCustoMaterial() {
        return this.custoMaterial;
    }
    
    public void setCustoMaterial(BigDecimal custoMaterial) {
        this.custoMaterial = custoMaterial;
    }

    
    @Column(name="CUSTO_LABORATORIAL", nullable=false, precision=15)
    public BigDecimal getCustoLaboratorial() {
        return this.custoLaboratorial;
    }
    
    public void setCustoLaboratorial(BigDecimal custoLaboratorial) {
        this.custoLaboratorial = custoLaboratorial;
    }

    
    @Column(name="OUTROS_CUSTOS", nullable=false, precision=15)
    public BigDecimal getOutrosCustos() {
        return this.outrosCustos;
    }
    
    public void setOutrosCustos(BigDecimal outrosCustos) {
        this.outrosCustos = outrosCustos;
    }

    
    @Column(name="TEMPO_DURACAO", nullable=false, precision=4, scale=0)
    public short getTempoDuracao() {
        return this.tempoDuracao;
    }
    
    public void setTempoDuracao(short tempoDuracao) {
        this.tempoDuracao = tempoDuracao;
    }

    
    @Column(name="NUMERO_CONSULTAS", nullable=false, precision=3, scale=0)
    public short getNumeroConsultas() {
        return this.numeroConsultas;
    }
    
    public void setNumeroConsultas(short numeroConsultas) {
        this.numeroConsultas = numeroConsultas;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=1)
    public char getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(char flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="FL_FALTA", nullable=false, length=1)
    public char getFlFalta() {
        return this.flFalta;
    }
    
    public void setFlFalta(char flFalta) {
        this.flFalta = flFalta;
    }

    
    @Column(name="VALOR_ENCARGO_OLD", precision=15)
    public BigDecimal getValorEncargoOld() {
        return this.valorEncargoOld;
    }
    
    public void setValorEncargoOld(BigDecimal valorEncargoOld) {
        this.valorEncargoOld = valorEncargoOld;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getMaterialProcedimentos() {
        return this.materialProcedimentos;
    }
    
    public void setMaterialProcedimentos(Set materialProcedimentos) {
        this.materialProcedimentos = materialProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getProcedimentoUnidades() {
        return this.procedimentoUnidades;
    }
    
    public void setProcedimentoUnidades(Set procedimentoUnidades) {
        this.procedimentoUnidades = procedimentoUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getProcedimentoContratos() {
        return this.procedimentoContratos;
    }
    
    public void setProcedimentoContratos(Set procedimentoContratos) {
        this.procedimentoContratos = procedimentoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getProcedimentoGuias() {
        return this.procedimentoGuias;
    }
    
    public void setProcedimentoGuias(Set procedimentoGuias) {
        this.procedimentoGuias = procedimentoGuias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getProcedimentoGrupos() {
        return this.procedimentoGrupos;
    }
    
    public void setProcedimentoGrupos(Set procedimentoGrupos) {
        this.procedimentoGrupos = procedimentoGrupos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getProcedimentoPacientes() {
        return this.procedimentoPacientes;
    }
    
    public void setProcedimentoPacientes(Set procedimentoPacientes) {
        this.procedimentoPacientes = procedimentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getTabelaConvenios() {
        return this.tabelaConvenios;
    }
    
    public void setTabelaConvenios(Set tabelaConvenios) {
        this.tabelaConvenios = tabelaConvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getItemProcedimentos() {
        return this.itemProcedimentos;
    }
    
    public void setItemProcedimentos(Set itemProcedimentos) {
        this.itemProcedimentos = itemProcedimentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimento")
    public Set getRepasseProfissionals() {
        return this.repasseProfissionals;
    }
    
    public void setRepasseProfissionals(Set repasseProfissionals) {
        this.repasseProfissionals = repasseProfissionals;
    }




}


