package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcedimentoPaciente generated by hbm2java
 */
@Entity
@Table(name="PROCEDIMENTO_PACIENTE"
    ,schema="DESENV"
)
public class ProcedimentoPaciente  implements java.io.Serializable {


     private BigDecimal id;
     private Contrato contrato;
     private ListaRegiaoProcedimento listaRegiaoProcedimento;
     private Paciente paciente;
     private Procedimento procedimento;
     private Profissional profissional;
     private Unidade unidade;
     private Empresa empresa;
     private Date dtOrcamento;
     private String flExecutado;
     private Date dtExecucao;
     private String descricao;
     private BigDecimal valor;
     private BigDecimal valorPago;
     private BigDecimal vlReceberProfissional;
     private BigDecimal vlPagoProfissional;
     private Date dtPagamentoProfissional;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal vlTributacao;
     private Set procedimentoFormaPagamentos = new HashSet(0);
     private Set composicaoPagamentoProfs = new HashSet(0);

    public ProcedimentoPaciente() {
    }

	
    public ProcedimentoPaciente(BigDecimal id, Paciente paciente, Procedimento procedimento, Unidade unidade, Empresa empresa, Date dtOrcamento, String flExecutado, BigDecimal valor, BigDecimal valorPago) {
        this.id = id;
        this.paciente = paciente;
        this.procedimento = procedimento;
        this.unidade = unidade;
        this.empresa = empresa;
        this.dtOrcamento = dtOrcamento;
        this.flExecutado = flExecutado;
        this.valor = valor;
        this.valorPago = valorPago;
    }
    public ProcedimentoPaciente(BigDecimal id, Contrato contrato, ListaRegiaoProcedimento listaRegiaoProcedimento, Paciente paciente, Procedimento procedimento, Profissional profissional, Unidade unidade, Empresa empresa, Date dtOrcamento, String flExecutado, Date dtExecucao, String descricao, BigDecimal valor, BigDecimal valorPago, BigDecimal vlReceberProfissional, BigDecimal vlPagoProfissional, Date dtPagamentoProfissional, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal vlTributacao, Set procedimentoFormaPagamentos, Set composicaoPagamentoProfs) {
       this.id = id;
       this.contrato = contrato;
       this.listaRegiaoProcedimento = listaRegiaoProcedimento;
       this.paciente = paciente;
       this.procedimento = procedimento;
       this.profissional = profissional;
       this.unidade = unidade;
       this.empresa = empresa;
       this.dtOrcamento = dtOrcamento;
       this.flExecutado = flExecutado;
       this.dtExecucao = dtExecucao;
       this.descricao = descricao;
       this.valor = valor;
       this.valorPago = valorPago;
       this.vlReceberProfissional = vlReceberProfissional;
       this.vlPagoProfissional = vlPagoProfissional;
       this.dtPagamentoProfissional = dtPagamentoProfissional;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.vlTributacao = vlTributacao;
       this.procedimentoFormaPagamentos = procedimentoFormaPagamentos;
       this.composicaoPagamentoProfs = composicaoPagamentoProfs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONT_ID")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="LIREP_REGIAO", referencedColumnName="REGIAO"), 
        @JoinColumn(name="LIREP_REGP_ID", referencedColumnName="REGP_ID") } )
    public ListaRegiaoProcedimento getListaRegiaoProcedimento() {
        return this.listaRegiaoProcedimento;
    }
    
    public void setListaRegiaoProcedimento(ListaRegiaoProcedimento listaRegiaoProcedimento) {
        this.listaRegiaoProcedimento = listaRegiaoProcedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROC_ID", nullable=false)
    public Procedimento getProcedimento() {
        return this.procedimento;
    }
    
    public void setProcedimento(Procedimento procedimento) {
        this.procedimento = procedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROF_ID")
    public Profissional getProfissional() {
        return this.profissional;
    }
    
    public void setProfissional(Profissional profissional) {
        this.profissional = profissional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ORCAMENTO", nullable=false, length=7)
    public Date getDtOrcamento() {
        return this.dtOrcamento;
    }
    
    public void setDtOrcamento(Date dtOrcamento) {
        this.dtOrcamento = dtOrcamento;
    }

    
    @Column(name="FL_EXECUTADO", nullable=false, length=1)
    public String getFlExecutado() {
        return this.flExecutado;
    }
    
    public void setFlExecutado(String flExecutado) {
        this.flExecutado = flExecutado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_EXECUCAO", length=7)
    public Date getDtExecucao() {
        return this.dtExecucao;
    }
    
    public void setDtExecucao(Date dtExecucao) {
        this.dtExecucao = dtExecucao;
    }

    
    @Column(name="DESCRICAO", length=4000)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="VALOR", nullable=false, precision=15)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VL_RECEBER_PROFISSIONAL", precision=15)
    public BigDecimal getVlReceberProfissional() {
        return this.vlReceberProfissional;
    }
    
    public void setVlReceberProfissional(BigDecimal vlReceberProfissional) {
        this.vlReceberProfissional = vlReceberProfissional;
    }

    
    @Column(name="VL_PAGO_PROFISSIONAL", precision=15)
    public BigDecimal getVlPagoProfissional() {
        return this.vlPagoProfissional;
    }
    
    public void setVlPagoProfissional(BigDecimal vlPagoProfissional) {
        this.vlPagoProfissional = vlPagoProfissional;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_PAGAMENTO_PROFISSIONAL", length=7)
    public Date getDtPagamentoProfissional() {
        return this.dtPagamentoProfissional;
    }
    
    public void setDtPagamentoProfissional(Date dtPagamentoProfissional) {
        this.dtPagamentoProfissional = dtPagamentoProfissional;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="VL_TRIBUTACAO", precision=15)
    public BigDecimal getVlTributacao() {
        return this.vlTributacao;
    }
    
    public void setVlTributacao(BigDecimal vlTributacao) {
        this.vlTributacao = vlTributacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimentoPaciente")
    public Set getProcedimentoFormaPagamentos() {
        return this.procedimentoFormaPagamentos;
    }
    
    public void setProcedimentoFormaPagamentos(Set procedimentoFormaPagamentos) {
        this.procedimentoFormaPagamentos = procedimentoFormaPagamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedimentoPaciente")
    public Set getComposicaoPagamentoProfs() {
        return this.composicaoPagamentoProfs;
    }
    
    public void setComposicaoPagamentoProfs(Set composicaoPagamentoProfs) {
        this.composicaoPagamentoProfs = composicaoPagamentoProfs;
    }




}


