package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processo generated by hbm2java
 */
@Entity
@Table(name="PROCESSO"
    ,schema="DESENV"
)
public class Processo  implements java.io.Serializable {


     private BigDecimal cdProcesso;
     private String dsProcesso;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set processoGrupoUsuarios = new HashSet(0);

    public Processo() {
    }

	
    public Processo(BigDecimal cdProcesso, String dsProcesso, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdProcesso = cdProcesso;
        this.dsProcesso = dsProcesso;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public Processo(BigDecimal cdProcesso, String dsProcesso, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set processoGrupoUsuarios) {
       this.cdProcesso = cdProcesso;
       this.dsProcesso = dsProcesso;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.processoGrupoUsuarios = processoGrupoUsuarios;
    }
   
     @Id 

    
    @Column(name="CD_PROCESSO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdProcesso() {
        return this.cdProcesso;
    }
    
    public void setCdProcesso(BigDecimal cdProcesso) {
        this.cdProcesso = cdProcesso;
    }

    
    @Column(name="DS_PROCESSO", nullable=false, length=50)
    public String getDsProcesso() {
        return this.dsProcesso;
    }
    
    public void setDsProcesso(String dsProcesso) {
        this.dsProcesso = dsProcesso;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="processo")
    public Set getProcessoGrupoUsuarios() {
        return this.processoGrupoUsuarios;
    }
    
    public void setProcessoGrupoUsuarios(Set processoGrupoUsuarios) {
        this.processoGrupoUsuarios = processoGrupoUsuarios;
    }




}


