package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessoGrupoUsuarioId generated by hbm2java
 */
@Embeddable
public class ProcessoGrupoUsuarioId  implements java.io.Serializable {


     private BigDecimal grusCdUsuario;
     private BigDecimal procCdProcesso;

    public ProcessoGrupoUsuarioId() {
    }

    public ProcessoGrupoUsuarioId(BigDecimal grusCdUsuario, BigDecimal procCdProcesso) {
       this.grusCdUsuario = grusCdUsuario;
       this.procCdProcesso = procCdProcesso;
    }
   


    @Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getGrusCdUsuario() {
        return this.grusCdUsuario;
    }
    
    public void setGrusCdUsuario(BigDecimal grusCdUsuario) {
        this.grusCdUsuario = grusCdUsuario;
    }


    @Column(name="PROC_CD_PROCESSO", nullable=false, precision=22, scale=0)
    public BigDecimal getProcCdProcesso() {
        return this.procCdProcesso;
    }
    
    public void setProcCdProcesso(BigDecimal procCdProcesso) {
        this.procCdProcesso = procCdProcesso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessoGrupoUsuarioId) ) return false;
		 ProcessoGrupoUsuarioId castOther = ( ProcessoGrupoUsuarioId ) other; 
         
		 return ( (this.getGrusCdUsuario()==castOther.getGrusCdUsuario()) || ( this.getGrusCdUsuario()!=null && castOther.getGrusCdUsuario()!=null && this.getGrusCdUsuario().equals(castOther.getGrusCdUsuario()) ) )
 && ( (this.getProcCdProcesso()==castOther.getProcCdProcesso()) || ( this.getProcCdProcesso()!=null && castOther.getProcCdProcesso()!=null && this.getProcCdProcesso().equals(castOther.getProcCdProcesso()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrusCdUsuario() == null ? 0 : this.getGrusCdUsuario().hashCode() );
         result = 37 * result + ( getProcCdProcesso() == null ? 0 : this.getProcCdProcesso().hashCode() );
         return result;
   }   


}


