package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProcedimentoGuiaFechamento generated by hbm2java
 */
@Entity
@Table(name="PROCEDIMENTO_GUIA_FECHAMENTO"
    ,schema="DESENV"
)
public class ProcedimentoGuiaFechamento  implements java.io.Serializable {


     private BigDecimal pguiaId;
     private GuiaFechamento guiaFechamento;
     private MotivoGlosa motivoGlosa;
     private ProcedimentoGuia procedimentoGuia;
     private Empresa empresa;
     private BigDecimal valorPago;
     private BigDecimal valorGlosa;
     private BigDecimal vlReceberProfissional;
     private BigDecimal valorIgnorado;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal vlTributacao;

    public ProcedimentoGuiaFechamento() {
    }

	
    public ProcedimentoGuiaFechamento(GuiaFechamento guiaFechamento, ProcedimentoGuia procedimentoGuia, Empresa empresa, BigDecimal valorPago, BigDecimal valorGlosa, BigDecimal vlReceberProfissional, BigDecimal valorIgnorado, BigDecimal vlTributacao) {
        this.guiaFechamento = guiaFechamento;
        this.procedimentoGuia = procedimentoGuia;
        this.empresa = empresa;
        this.valorPago = valorPago;
        this.valorGlosa = valorGlosa;
        this.vlReceberProfissional = vlReceberProfissional;
        this.valorIgnorado = valorIgnorado;
        this.vlTributacao = vlTributacao;
    }
    public ProcedimentoGuiaFechamento(GuiaFechamento guiaFechamento, MotivoGlosa motivoGlosa, ProcedimentoGuia procedimentoGuia, Empresa empresa, BigDecimal valorPago, BigDecimal valorGlosa, BigDecimal vlReceberProfissional, BigDecimal valorIgnorado, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal vlTributacao) {
       this.guiaFechamento = guiaFechamento;
       this.motivoGlosa = motivoGlosa;
       this.procedimentoGuia = procedimentoGuia;
       this.empresa = empresa;
       this.valorPago = valorPago;
       this.valorGlosa = valorGlosa;
       this.vlReceberProfissional = vlReceberProfissional;
       this.valorIgnorado = valorIgnorado;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.vlTributacao = vlTributacao;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="procedimentoGuia"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="PGUIA_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPguiaId() {
        return this.pguiaId;
    }
    
    public void setPguiaId(BigDecimal pguiaId) {
        this.pguiaId = pguiaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GUIFE_GUIA_ID", nullable=false)
    public GuiaFechamento getGuiaFechamento() {
        return this.guiaFechamento;
    }
    
    public void setGuiaFechamento(GuiaFechamento guiaFechamento) {
        this.guiaFechamento = guiaFechamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="MOGLO_CODIGO", referencedColumnName="CODIGO"), 
        @JoinColumn(name="MOGLO_CONV_ID", referencedColumnName="CONV_ID") } )
    public MotivoGlosa getMotivoGlosa() {
        return this.motivoGlosa;
    }
    
    public void setMotivoGlosa(MotivoGlosa motivoGlosa) {
        this.motivoGlosa = motivoGlosa;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public ProcedimentoGuia getProcedimentoGuia() {
        return this.procedimentoGuia;
    }
    
    public void setProcedimentoGuia(ProcedimentoGuia procedimentoGuia) {
        this.procedimentoGuia = procedimentoGuia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VALOR_GLOSA", nullable=false, precision=15)
    public BigDecimal getValorGlosa() {
        return this.valorGlosa;
    }
    
    public void setValorGlosa(BigDecimal valorGlosa) {
        this.valorGlosa = valorGlosa;
    }

    
    @Column(name="VL_RECEBER_PROFISSIONAL", nullable=false, precision=15)
    public BigDecimal getVlReceberProfissional() {
        return this.vlReceberProfissional;
    }
    
    public void setVlReceberProfissional(BigDecimal vlReceberProfissional) {
        this.vlReceberProfissional = vlReceberProfissional;
    }

    
    @Column(name="VALOR_IGNORADO", nullable=false, precision=15)
    public BigDecimal getValorIgnorado() {
        return this.valorIgnorado;
    }
    
    public void setValorIgnorado(BigDecimal valorIgnorado) {
        this.valorIgnorado = valorIgnorado;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="VL_TRIBUTACAO", nullable=false, precision=15)
    public BigDecimal getVlTributacao() {
        return this.vlTributacao;
    }
    
    public void setVlTributacao(BigDecimal vlTributacao) {
        this.vlTributacao = vlTributacao;
    }




}


