package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProgramacaoPagamentoNfId generated by hbm2java
 */
@Embeddable
public class ProgramacaoPagamentoNfId  implements java.io.Serializable {


     private BigDecimal nfId;
     private BigDecimal parcela;

    public ProgramacaoPagamentoNfId() {
    }

    public ProgramacaoPagamentoNfId(BigDecimal nfId, BigDecimal parcela) {
       this.nfId = nfId;
       this.parcela = parcela;
    }
   


    @Column(name="NF_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getNfId() {
        return this.nfId;
    }
    
    public void setNfId(BigDecimal nfId) {
        this.nfId = nfId;
    }


    @Column(name="PARCELA", nullable=false, precision=22, scale=0)
    public BigDecimal getParcela() {
        return this.parcela;
    }
    
    public void setParcela(BigDecimal parcela) {
        this.parcela = parcela;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProgramacaoPagamentoNfId) ) return false;
		 ProgramacaoPagamentoNfId castOther = ( ProgramacaoPagamentoNfId ) other; 
         
		 return ( (this.getNfId()==castOther.getNfId()) || ( this.getNfId()!=null && castOther.getNfId()!=null && this.getNfId().equals(castOther.getNfId()) ) )
 && ( (this.getParcela()==castOther.getParcela()) || ( this.getParcela()!=null && castOther.getParcela()!=null && this.getParcela().equals(castOther.getParcela()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNfId() == null ? 0 : this.getNfId().hashCode() );
         result = 37 * result + ( getParcela() == null ? 0 : this.getParcela().hashCode() );
         return result;
   }   


}


