package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgramacaoPagamentoNf generated by hbm2java
 */
@Entity
@Table(name="PROGRAMACAO_PAGAMENTO_NF"
    ,schema="DESENV"
)
public class ProgramacaoPagamentoNf  implements java.io.Serializable {


     private ProgramacaoPagamentoNfId id;
     private Conta conta;
     private NotaFiscal notaFiscal;
     private Empresa empresa;
     private String flStatus;
     private Date dataVencimento;
     private BigDecimal valorParcela;
     private BigDecimal valorPago;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Date dtAgendamento;
     private Set pagamentoNotaFiscals = new HashSet(0);

    public ProgramacaoPagamentoNf() {
    }

	
    public ProgramacaoPagamentoNf(ProgramacaoPagamentoNfId id, NotaFiscal notaFiscal, Empresa empresa, String flStatus, Date dataVencimento, BigDecimal valorParcela, BigDecimal valorPago) {
        this.id = id;
        this.notaFiscal = notaFiscal;
        this.empresa = empresa;
        this.flStatus = flStatus;
        this.dataVencimento = dataVencimento;
        this.valorParcela = valorParcela;
        this.valorPago = valorPago;
    }
    public ProgramacaoPagamentoNf(ProgramacaoPagamentoNfId id, Conta conta, NotaFiscal notaFiscal, Empresa empresa, String flStatus, Date dataVencimento, BigDecimal valorParcela, BigDecimal valorPago, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Date dtAgendamento, Set pagamentoNotaFiscals) {
       this.id = id;
       this.conta = conta;
       this.notaFiscal = notaFiscal;
       this.empresa = empresa;
       this.flStatus = flStatus;
       this.dataVencimento = dataVencimento;
       this.valorParcela = valorParcela;
       this.valorPago = valorPago;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.dtAgendamento = dtAgendamento;
       this.pagamentoNotaFiscals = pagamentoNotaFiscals;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nfId", column=@Column(name="NF_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="parcela", column=@Column(name="PARCELA", nullable=false, precision=22, scale=0) ) } )
    public ProgramacaoPagamentoNfId getId() {
        return this.id;
    }
    
    public void setId(ProgramacaoPagamentoNfId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CON_ID")
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NF_ID", nullable=false, insertable=false, updatable=false)
    public NotaFiscal getNotaFiscal() {
        return this.notaFiscal;
    }
    
    public void setNotaFiscal(NotaFiscal notaFiscal) {
        this.notaFiscal = notaFiscal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="FL_STATUS", nullable=false, length=1)
    public String getFlStatus() {
        return this.flStatus;
    }
    
    public void setFlStatus(String flStatus) {
        this.flStatus = flStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_VENCIMENTO", nullable=false, length=7)
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    
    @Column(name="VALOR_PARCELA", nullable=false, precision=15)
    public BigDecimal getValorParcela() {
        return this.valorParcela;
    }
    
    public void setValorParcela(BigDecimal valorParcela) {
        this.valorParcela = valorParcela;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_AGENDAMENTO", length=7)
    public Date getDtAgendamento() {
        return this.dtAgendamento;
    }
    
    public void setDtAgendamento(Date dtAgendamento) {
        this.dtAgendamento = dtAgendamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="programacaoPagamentoNf")
    public Set getPagamentoNotaFiscals() {
        return this.pagamentoNotaFiscals;
    }
    
    public void setPagamentoNotaFiscals(Set pagamentoNotaFiscals) {
        this.pagamentoNotaFiscals = pagamentoNotaFiscals;
    }




}


