package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SituacaoCheque generated by hbm2java
 */
@Entity
@Table(name="SITUACAO_CHEQUE"
    ,schema="DESENV"
)
public class SituacaoCheque  implements java.io.Serializable {


     private BigDecimal id;
     private PlanoContas planoContas;
     private Empresa empresa;
     private String nome;
     private char flIndicaQuitacao;
     private char flSituacaoInicial;
     private String flTipoMovimentoCaixa;
     private String flTipoPortador;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private char flIndicaContaReceber;
     private Set movimentacaoCheques = new HashSet(0);
     private Set proximaSituacaoChequesForSicheId = new HashSet(0);
     private Set proximaSituacaoChequesForSicheIdProxima = new HashSet(0);
     private Set cheques = new HashSet(0);

    public SituacaoCheque() {
    }

	
    public SituacaoCheque(BigDecimal id, Empresa empresa, String nome, char flIndicaQuitacao, char flSituacaoInicial, String flTipoMovimentoCaixa, String flTipoPortador, char flIndicaContaReceber) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.flIndicaQuitacao = flIndicaQuitacao;
        this.flSituacaoInicial = flSituacaoInicial;
        this.flTipoMovimentoCaixa = flTipoMovimentoCaixa;
        this.flTipoPortador = flTipoPortador;
        this.flIndicaContaReceber = flIndicaContaReceber;
    }
    public SituacaoCheque(BigDecimal id, PlanoContas planoContas, Empresa empresa, String nome, char flIndicaQuitacao, char flSituacaoInicial, String flTipoMovimentoCaixa, String flTipoPortador, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, char flIndicaContaReceber, Set movimentacaoCheques, Set proximaSituacaoChequesForSicheId, Set proximaSituacaoChequesForSicheIdProxima, Set cheques) {
       this.id = id;
       this.planoContas = planoContas;
       this.empresa = empresa;
       this.nome = nome;
       this.flIndicaQuitacao = flIndicaQuitacao;
       this.flSituacaoInicial = flSituacaoInicial;
       this.flTipoMovimentoCaixa = flTipoMovimentoCaixa;
       this.flTipoPortador = flTipoPortador;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flIndicaContaReceber = flIndicaContaReceber;
       this.movimentacaoCheques = movimentacaoCheques;
       this.proximaSituacaoChequesForSicheId = proximaSituacaoChequesForSicheId;
       this.proximaSituacaoChequesForSicheIdProxima = proximaSituacaoChequesForSicheIdProxima;
       this.cheques = cheques;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLA_ID")
    public PlanoContas getPlanoContas() {
        return this.planoContas;
    }
    
    public void setPlanoContas(PlanoContas planoContas) {
        this.planoContas = planoContas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="FL_INDICA_QUITACAO", nullable=false, length=1)
    public char getFlIndicaQuitacao() {
        return this.flIndicaQuitacao;
    }
    
    public void setFlIndicaQuitacao(char flIndicaQuitacao) {
        this.flIndicaQuitacao = flIndicaQuitacao;
    }

    
    @Column(name="FL_SITUACAO_INICIAL", nullable=false, length=1)
    public char getFlSituacaoInicial() {
        return this.flSituacaoInicial;
    }
    
    public void setFlSituacaoInicial(char flSituacaoInicial) {
        this.flSituacaoInicial = flSituacaoInicial;
    }

    
    @Column(name="FL_TIPO_MOVIMENTO_CAIXA", nullable=false, length=3)
    public String getFlTipoMovimentoCaixa() {
        return this.flTipoMovimentoCaixa;
    }
    
    public void setFlTipoMovimentoCaixa(String flTipoMovimentoCaixa) {
        this.flTipoMovimentoCaixa = flTipoMovimentoCaixa;
    }

    
    @Column(name="FL_TIPO_PORTADOR", nullable=false, length=3)
    public String getFlTipoPortador() {
        return this.flTipoPortador;
    }
    
    public void setFlTipoPortador(String flTipoPortador) {
        this.flTipoPortador = flTipoPortador;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_INDICA_CONTA_RECEBER", nullable=false, length=1)
    public char getFlIndicaContaReceber() {
        return this.flIndicaContaReceber;
    }
    
    public void setFlIndicaContaReceber(char flIndicaContaReceber) {
        this.flIndicaContaReceber = flIndicaContaReceber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="situacaoCheque")
    public Set getMovimentacaoCheques() {
        return this.movimentacaoCheques;
    }
    
    public void setMovimentacaoCheques(Set movimentacaoCheques) {
        this.movimentacaoCheques = movimentacaoCheques;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="situacaoChequeBySicheId")
    public Set getProximaSituacaoChequesForSicheId() {
        return this.proximaSituacaoChequesForSicheId;
    }
    
    public void setProximaSituacaoChequesForSicheId(Set proximaSituacaoChequesForSicheId) {
        this.proximaSituacaoChequesForSicheId = proximaSituacaoChequesForSicheId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="situacaoChequeBySicheIdProxima")
    public Set getProximaSituacaoChequesForSicheIdProxima() {
        return this.proximaSituacaoChequesForSicheIdProxima;
    }
    
    public void setProximaSituacaoChequesForSicheIdProxima(Set proximaSituacaoChequesForSicheIdProxima) {
        this.proximaSituacaoChequesForSicheIdProxima = proximaSituacaoChequesForSicheIdProxima;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="situacaoCheque")
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }




}


