package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TabelaConvenio generated by hbm2java
 */
@Entity
@Table(name="TABELA_CONVENIO"
    ,schema="DESENV"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"PROCEDIMENTO_ID", "CONV_ID"}), @UniqueConstraint(columnNames={"CONV_ID", "CODIGO_CONVENIO"})} 
)
public class TabelaConvenio  implements java.io.Serializable {


     private BigDecimal id;
     private Convenio convenio;
     private Procedimento procedimento;
     private Empresa empresa;
     private BigDecimal valor;
     private String codigoConvenio;
     private BigDecimal quantidadeUo;
     private String flAtivo;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private String flObrigaFace;

    public TabelaConvenio() {
    }

	
    public TabelaConvenio(BigDecimal id, Convenio convenio, Procedimento procedimento, Empresa empresa, String codigoConvenio, String flAtivo, String flObrigaFace) {
        this.id = id;
        this.convenio = convenio;
        this.procedimento = procedimento;
        this.empresa = empresa;
        this.codigoConvenio = codigoConvenio;
        this.flAtivo = flAtivo;
        this.flObrigaFace = flObrigaFace;
    }
    public TabelaConvenio(BigDecimal id, Convenio convenio, Procedimento procedimento, Empresa empresa, BigDecimal valor, String codigoConvenio, BigDecimal quantidadeUo, String flAtivo, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, String flObrigaFace) {
       this.id = id;
       this.convenio = convenio;
       this.procedimento = procedimento;
       this.empresa = empresa;
       this.valor = valor;
       this.codigoConvenio = codigoConvenio;
       this.quantidadeUo = quantidadeUo;
       this.flAtivo = flAtivo;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flObrigaFace = flObrigaFace;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_ID", referencedColumnName="ID", nullable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false) } )
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROCEDIMENTO_ID", nullable=false)
    public Procedimento getProcedimento() {
        return this.procedimento;
    }
    
    public void setProcedimento(Procedimento procedimento) {
        this.procedimento = procedimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="VALOR", precision=15)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="CODIGO_CONVENIO", nullable=false, length=15)
    public String getCodigoConvenio() {
        return this.codigoConvenio;
    }
    
    public void setCodigoConvenio(String codigoConvenio) {
        this.codigoConvenio = codigoConvenio;
    }

    
    @Column(name="QUANTIDADE_UO", precision=15)
    public BigDecimal getQuantidadeUo() {
        return this.quantidadeUo;
    }
    
    public void setQuantidadeUo(BigDecimal quantidadeUo) {
        this.quantidadeUo = quantidadeUo;
    }

    
    @Column(name="FL_ATIVO", nullable=false, length=240)
    public String getFlAtivo() {
        return this.flAtivo;
    }
    
    public void setFlAtivo(String flAtivo) {
        this.flAtivo = flAtivo;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_OBRIGA_FACE", nullable=false, length=1)
    public String getFlObrigaFace() {
        return this.flObrigaFace;
    }
    
    public void setFlObrigaFace(String flObrigaFace) {
        this.flObrigaFace = flObrigaFace;
    }




}


