package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TelaRelatorioGrafico generated by hbm2java
 */
@Entity
@Table(name="TELA_RELATORIO_GRAFICO"
    ,schema="DESENV"
)
public class TelaRelatorioGrafico  implements java.io.Serializable {


     private BigDecimal cdTelaRelatorio;
     private String nmTelaRelatorio;
     private String dsTelaRelatorio;
     private String flTelaRelatorio;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;
     private Set usuGrupoTelaRelGras = new HashSet(0);
     private Set itemMenus = new HashSet(0);

    public TelaRelatorioGrafico() {
    }

	
    public TelaRelatorioGrafico(BigDecimal cdTelaRelatorio, String nmTelaRelatorio, String dsTelaRelatorio, String flTelaRelatorio, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
        this.cdTelaRelatorio = cdTelaRelatorio;
        this.nmTelaRelatorio = nmTelaRelatorio;
        this.dsTelaRelatorio = dsTelaRelatorio;
        this.flTelaRelatorio = flTelaRelatorio;
        this.cdCriadoPor = cdCriadoPor;
        this.cdAlteradoPor = cdAlteradoPor;
        this.dtCriacao = dtCriacao;
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
    public TelaRelatorioGrafico(BigDecimal cdTelaRelatorio, String nmTelaRelatorio, String dsTelaRelatorio, String flTelaRelatorio, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao, Set usuGrupoTelaRelGras, Set itemMenus) {
       this.cdTelaRelatorio = cdTelaRelatorio;
       this.nmTelaRelatorio = nmTelaRelatorio;
       this.dsTelaRelatorio = dsTelaRelatorio;
       this.flTelaRelatorio = flTelaRelatorio;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.usuGrupoTelaRelGras = usuGrupoTelaRelGras;
       this.itemMenus = itemMenus;
    }
   
     @Id 

    
    @Column(name="CD_TELA_RELATORIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCdTelaRelatorio() {
        return this.cdTelaRelatorio;
    }
    
    public void setCdTelaRelatorio(BigDecimal cdTelaRelatorio) {
        this.cdTelaRelatorio = cdTelaRelatorio;
    }

    
    @Column(name="NM_TELA_RELATORIO", nullable=false, length=30)
    public String getNmTelaRelatorio() {
        return this.nmTelaRelatorio;
    }
    
    public void setNmTelaRelatorio(String nmTelaRelatorio) {
        this.nmTelaRelatorio = nmTelaRelatorio;
    }

    
    @Column(name="DS_TELA_RELATORIO", nullable=false, length=80)
    public String getDsTelaRelatorio() {
        return this.dsTelaRelatorio;
    }
    
    public void setDsTelaRelatorio(String dsTelaRelatorio) {
        this.dsTelaRelatorio = dsTelaRelatorio;
    }

    
    @Column(name="FL_TELA_RELATORIO", nullable=false, length=1)
    public String getFlTelaRelatorio() {
        return this.flTelaRelatorio;
    }
    
    public void setFlTelaRelatorio(String flTelaRelatorio) {
        this.flTelaRelatorio = flTelaRelatorio;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="telaRelatorioGrafico")
    public Set getUsuGrupoTelaRelGras() {
        return this.usuGrupoTelaRelGras;
    }
    
    public void setUsuGrupoTelaRelGras(Set usuGrupoTelaRelGras) {
        this.usuGrupoTelaRelGras = usuGrupoTelaRelGras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="telaRelatorioGrafico")
    public Set getItemMenus() {
        return this.itemMenus;
    }
    
    public void setItemMenus(Set itemMenus) {
        this.itemMenus = itemMenus;
    }




}


