package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name="TIPO_CONTRATO"
    ,schema="DESENV"
)
public class TipoContrato  implements java.io.Serializable {


     private BigDecimal id;
     private ConvenioBancario convenioBancario;
     private DocumentoEspaco documentoEspacoByTpcontDocesTituloFk;
     private DocumentoEspaco documentoEspacoByTpcontDocesCabFk;
     private DocumentoEspaco documentoEspacoByTpcontDocesRodapeFk;
     private DocumentoEspaco documentoEspacoByTpcontDocesCorpoFk;
     private IndiceAtualizacao indiceAtualizacaoByIndMultaId;
     private IndiceAtualizacao indiceAtualizacaoByIndMoraId;
     private IndiceAtualizacao indiceAtualizacaoByIndParcId;
     private Unidade unidade;
     private Empresa empresa;
     private String nome;
     private BigDecimal nuMaxParcelas;
     private String instrucaoParcela1;
     private String instrucaoParcelas;
     private BigDecimal nuDiasProtesto;
     private BigDecimal pcDesconto;
     private char modalidade;
     private BigDecimal nuDiasValidade;
     private BigDecimal valorTaxaBoleto;
     private BigDecimal nuMinParcelas;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private char flTipoCobranca;
     private char flRenovavel;
     private Set contratoCondicoeses = new HashSet(0);
     private Set contratos = new HashSet(0);

    public TipoContrato() {
    }

	
    public TipoContrato(BigDecimal id, ConvenioBancario convenioBancario, DocumentoEspaco documentoEspacoByTpcontDocesTituloFk, DocumentoEspaco documentoEspacoByTpcontDocesCabFk, DocumentoEspaco documentoEspacoByTpcontDocesRodapeFk, DocumentoEspaco documentoEspacoByTpcontDocesCorpoFk, IndiceAtualizacao indiceAtualizacaoByIndMultaId, IndiceAtualizacao indiceAtualizacaoByIndMoraId, IndiceAtualizacao indiceAtualizacaoByIndParcId, Unidade unidade, Empresa empresa, String nome, BigDecimal nuMaxParcelas, String instrucaoParcela1, String instrucaoParcelas, BigDecimal pcDesconto, char modalidade, BigDecimal nuDiasValidade, BigDecimal valorTaxaBoleto, BigDecimal nuMinParcelas, char flTipoCobranca, char flRenovavel) {
        this.id = id;
        this.convenioBancario = convenioBancario;
        this.documentoEspacoByTpcontDocesTituloFk = documentoEspacoByTpcontDocesTituloFk;
        this.documentoEspacoByTpcontDocesCabFk = documentoEspacoByTpcontDocesCabFk;
        this.documentoEspacoByTpcontDocesRodapeFk = documentoEspacoByTpcontDocesRodapeFk;
        this.documentoEspacoByTpcontDocesCorpoFk = documentoEspacoByTpcontDocesCorpoFk;
        this.indiceAtualizacaoByIndMultaId = indiceAtualizacaoByIndMultaId;
        this.indiceAtualizacaoByIndMoraId = indiceAtualizacaoByIndMoraId;
        this.indiceAtualizacaoByIndParcId = indiceAtualizacaoByIndParcId;
        this.unidade = unidade;
        this.empresa = empresa;
        this.nome = nome;
        this.nuMaxParcelas = nuMaxParcelas;
        this.instrucaoParcela1 = instrucaoParcela1;
        this.instrucaoParcelas = instrucaoParcelas;
        this.pcDesconto = pcDesconto;
        this.modalidade = modalidade;
        this.nuDiasValidade = nuDiasValidade;
        this.valorTaxaBoleto = valorTaxaBoleto;
        this.nuMinParcelas = nuMinParcelas;
        this.flTipoCobranca = flTipoCobranca;
        this.flRenovavel = flRenovavel;
    }
    public TipoContrato(BigDecimal id, ConvenioBancario convenioBancario, DocumentoEspaco documentoEspacoByTpcontDocesTituloFk, DocumentoEspaco documentoEspacoByTpcontDocesCabFk, DocumentoEspaco documentoEspacoByTpcontDocesRodapeFk, DocumentoEspaco documentoEspacoByTpcontDocesCorpoFk, IndiceAtualizacao indiceAtualizacaoByIndMultaId, IndiceAtualizacao indiceAtualizacaoByIndMoraId, IndiceAtualizacao indiceAtualizacaoByIndParcId, Unidade unidade, Empresa empresa, String nome, BigDecimal nuMaxParcelas, String instrucaoParcela1, String instrucaoParcelas, BigDecimal nuDiasProtesto, BigDecimal pcDesconto, char modalidade, BigDecimal nuDiasValidade, BigDecimal valorTaxaBoleto, BigDecimal nuMinParcelas, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, char flTipoCobranca, char flRenovavel, Set contratoCondicoeses, Set contratos) {
       this.id = id;
       this.convenioBancario = convenioBancario;
       this.documentoEspacoByTpcontDocesTituloFk = documentoEspacoByTpcontDocesTituloFk;
       this.documentoEspacoByTpcontDocesCabFk = documentoEspacoByTpcontDocesCabFk;
       this.documentoEspacoByTpcontDocesRodapeFk = documentoEspacoByTpcontDocesRodapeFk;
       this.documentoEspacoByTpcontDocesCorpoFk = documentoEspacoByTpcontDocesCorpoFk;
       this.indiceAtualizacaoByIndMultaId = indiceAtualizacaoByIndMultaId;
       this.indiceAtualizacaoByIndMoraId = indiceAtualizacaoByIndMoraId;
       this.indiceAtualizacaoByIndParcId = indiceAtualizacaoByIndParcId;
       this.unidade = unidade;
       this.empresa = empresa;
       this.nome = nome;
       this.nuMaxParcelas = nuMaxParcelas;
       this.instrucaoParcela1 = instrucaoParcela1;
       this.instrucaoParcelas = instrucaoParcelas;
       this.nuDiasProtesto = nuDiasProtesto;
       this.pcDesconto = pcDesconto;
       this.modalidade = modalidade;
       this.nuDiasValidade = nuDiasValidade;
       this.valorTaxaBoleto = valorTaxaBoleto;
       this.nuMinParcelas = nuMinParcelas;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.flTipoCobranca = flTipoCobranca;
       this.flRenovavel = flRenovavel;
       this.contratoCondicoeses = contratoCondicoeses;
       this.contratos = contratos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_BANCO", referencedColumnName="BANCO", nullable=false), 
        @JoinColumn(name="CONV_AGENCIA", referencedColumnName="AGENCIA", nullable=false), 
        @JoinColumn(name="CONV_CEDENTE", referencedColumnName="CEDENTE", nullable=false), 
        @JoinColumn(name="CONV_CARTEIRA", referencedColumnName="CARTEIRA", nullable=false), 
        @JoinColumn(name="CONV_CONVENIO", referencedColumnName="CONVENIO", nullable=false) } )
    public ConvenioBancario getConvenioBancario() {
        return this.convenioBancario;
    }
    
    public void setConvenioBancario(ConvenioBancario convenioBancario) {
        this.convenioBancario = convenioBancario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="DOCES_DOC_TITULO_ID", referencedColumnName="ID", nullable=false), 
        @JoinColumn(name="DOCES_ID", referencedColumnName="DOC_ID", nullable=false) } )
    public DocumentoEspaco getDocumentoEspacoByTpcontDocesTituloFk() {
        return this.documentoEspacoByTpcontDocesTituloFk;
    }
    
    public void setDocumentoEspacoByTpcontDocesTituloFk(DocumentoEspaco documentoEspacoByTpcontDocesTituloFk) {
        this.documentoEspacoByTpcontDocesTituloFk = documentoEspacoByTpcontDocesTituloFk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="DOCES_DOC_CAB_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DOCES_ID", referencedColumnName="DOC_ID", nullable=false, insertable=false, updatable=false) } )
    public DocumentoEspaco getDocumentoEspacoByTpcontDocesCabFk() {
        return this.documentoEspacoByTpcontDocesCabFk;
    }
    
    public void setDocumentoEspacoByTpcontDocesCabFk(DocumentoEspaco documentoEspacoByTpcontDocesCabFk) {
        this.documentoEspacoByTpcontDocesCabFk = documentoEspacoByTpcontDocesCabFk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="DOCES_DOC_RODAPE_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DOCES_ID", referencedColumnName="DOC_ID", nullable=false, insertable=false, updatable=false) } )
    public DocumentoEspaco getDocumentoEspacoByTpcontDocesRodapeFk() {
        return this.documentoEspacoByTpcontDocesRodapeFk;
    }
    
    public void setDocumentoEspacoByTpcontDocesRodapeFk(DocumentoEspaco documentoEspacoByTpcontDocesRodapeFk) {
        this.documentoEspacoByTpcontDocesRodapeFk = documentoEspacoByTpcontDocesRodapeFk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="DOCES_DOC_CORPO_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DOCES_ID", referencedColumnName="DOC_ID", nullable=false, insertable=false, updatable=false) } )
    public DocumentoEspaco getDocumentoEspacoByTpcontDocesCorpoFk() {
        return this.documentoEspacoByTpcontDocesCorpoFk;
    }
    
    public void setDocumentoEspacoByTpcontDocesCorpoFk(DocumentoEspaco documentoEspacoByTpcontDocesCorpoFk) {
        this.documentoEspacoByTpcontDocesCorpoFk = documentoEspacoByTpcontDocesCorpoFk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IND_MULTA_ID", nullable=false)
    public IndiceAtualizacao getIndiceAtualizacaoByIndMultaId() {
        return this.indiceAtualizacaoByIndMultaId;
    }
    
    public void setIndiceAtualizacaoByIndMultaId(IndiceAtualizacao indiceAtualizacaoByIndMultaId) {
        this.indiceAtualizacaoByIndMultaId = indiceAtualizacaoByIndMultaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IND_MORA_ID", nullable=false)
    public IndiceAtualizacao getIndiceAtualizacaoByIndMoraId() {
        return this.indiceAtualizacaoByIndMoraId;
    }
    
    public void setIndiceAtualizacaoByIndMoraId(IndiceAtualizacao indiceAtualizacaoByIndMoraId) {
        this.indiceAtualizacaoByIndMoraId = indiceAtualizacaoByIndMoraId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IND_PARC_ID", nullable=false)
    public IndiceAtualizacao getIndiceAtualizacaoByIndParcId() {
        return this.indiceAtualizacaoByIndParcId;
    }
    
    public void setIndiceAtualizacaoByIndParcId(IndiceAtualizacao indiceAtualizacaoByIndParcId) {
        this.indiceAtualizacaoByIndParcId = indiceAtualizacaoByIndParcId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="NU_MAX_PARCELAS", nullable=false, precision=22, scale=0)
    public BigDecimal getNuMaxParcelas() {
        return this.nuMaxParcelas;
    }
    
    public void setNuMaxParcelas(BigDecimal nuMaxParcelas) {
        this.nuMaxParcelas = nuMaxParcelas;
    }

    
    @Column(name="INSTRUCAO_PARCELA1", nullable=false, length=4000)
    public String getInstrucaoParcela1() {
        return this.instrucaoParcela1;
    }
    
    public void setInstrucaoParcela1(String instrucaoParcela1) {
        this.instrucaoParcela1 = instrucaoParcela1;
    }

    
    @Column(name="INSTRUCAO_PARCELAS", nullable=false, length=4000)
    public String getInstrucaoParcelas() {
        return this.instrucaoParcelas;
    }
    
    public void setInstrucaoParcelas(String instrucaoParcelas) {
        this.instrucaoParcelas = instrucaoParcelas;
    }

    
    @Column(name="NU_DIAS_PROTESTO", precision=22, scale=0)
    public BigDecimal getNuDiasProtesto() {
        return this.nuDiasProtesto;
    }
    
    public void setNuDiasProtesto(BigDecimal nuDiasProtesto) {
        this.nuDiasProtesto = nuDiasProtesto;
    }

    
    @Column(name="PC_DESCONTO", nullable=false, precision=7, scale=4)
    public BigDecimal getPcDesconto() {
        return this.pcDesconto;
    }
    
    public void setPcDesconto(BigDecimal pcDesconto) {
        this.pcDesconto = pcDesconto;
    }

    
    @Column(name="MODALIDADE", nullable=false, length=1)
    public char getModalidade() {
        return this.modalidade;
    }
    
    public void setModalidade(char modalidade) {
        this.modalidade = modalidade;
    }

    
    @Column(name="NU_DIAS_VALIDADE", nullable=false, precision=22, scale=0)
    public BigDecimal getNuDiasValidade() {
        return this.nuDiasValidade;
    }
    
    public void setNuDiasValidade(BigDecimal nuDiasValidade) {
        this.nuDiasValidade = nuDiasValidade;
    }

    
    @Column(name="VALOR_TAXA_BOLETO", nullable=false, precision=15)
    public BigDecimal getValorTaxaBoleto() {
        return this.valorTaxaBoleto;
    }
    
    public void setValorTaxaBoleto(BigDecimal valorTaxaBoleto) {
        this.valorTaxaBoleto = valorTaxaBoleto;
    }

    
    @Column(name="NU_MIN_PARCELAS", nullable=false, precision=22, scale=0)
    public BigDecimal getNuMinParcelas() {
        return this.nuMinParcelas;
    }
    
    public void setNuMinParcelas(BigDecimal nuMinParcelas) {
        this.nuMinParcelas = nuMinParcelas;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="FL_TIPO_COBRANCA", nullable=false, length=1)
    public char getFlTipoCobranca() {
        return this.flTipoCobranca;
    }
    
    public void setFlTipoCobranca(char flTipoCobranca) {
        this.flTipoCobranca = flTipoCobranca;
    }

    
    @Column(name="FL_RENOVAVEL", nullable=false, length=1)
    public char getFlRenovavel() {
        return this.flRenovavel;
    }
    
    public void setFlRenovavel(char flRenovavel) {
        this.flRenovavel = flRenovavel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoContrato")
    public Set getContratoCondicoeses() {
        return this.contratoCondicoeses;
    }
    
    public void setContratoCondicoeses(Set contratoCondicoeses) {
        this.contratoCondicoeses = contratoCondicoeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoContrato")
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


