package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoAgenda generated by hbm2java
 */
@Entity
@Table(name="TIPO_AGENDA"
    ,schema="DESENV"
)
public class TipoAgenda  implements java.io.Serializable {


     private TipoAgendaId id;
     private Empresa empresa;
     private String nome;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private String nomeReduzido;
     private String flEncaixe;
     private Set horarioAberturaAgendas = new HashSet(0);
     private Set tipoAgendaProfissionals = new HashSet(0);
     private Set agendas = new HashSet(0);

    public TipoAgenda() {
    }

	
    public TipoAgenda(TipoAgendaId id, Empresa empresa, String nome, String nomeReduzido, String flEncaixe) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.nomeReduzido = nomeReduzido;
        this.flEncaixe = flEncaixe;
    }
    public TipoAgenda(TipoAgendaId id, Empresa empresa, String nome, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, String nomeReduzido, String flEncaixe, Set horarioAberturaAgendas, Set tipoAgendaProfissionals, Set agendas) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.nomeReduzido = nomeReduzido;
       this.flEncaixe = flEncaixe;
       this.horarioAberturaAgendas = horarioAberturaAgendas;
       this.tipoAgendaProfissionals = tipoAgendaProfissionals;
       this.agendas = agendas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="empId", column=@Column(name="EMP_ID", nullable=false, precision=22, scale=0) ) } )
    public TipoAgendaId getId() {
        return this.id;
    }
    
    public void setId(TipoAgendaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="NOME_REDUZIDO", nullable=false, length=12)
    public String getNomeReduzido() {
        return this.nomeReduzido;
    }
    
    public void setNomeReduzido(String nomeReduzido) {
        this.nomeReduzido = nomeReduzido;
    }

    
    @Column(name="FL_ENCAIXE", nullable=false, length=1)
    public String getFlEncaixe() {
        return this.flEncaixe;
    }
    
    public void setFlEncaixe(String flEncaixe) {
        this.flEncaixe = flEncaixe;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoAgenda")
    public Set getHorarioAberturaAgendas() {
        return this.horarioAberturaAgendas;
    }
    
    public void setHorarioAberturaAgendas(Set horarioAberturaAgendas) {
        this.horarioAberturaAgendas = horarioAberturaAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoAgenda")
    public Set getTipoAgendaProfissionals() {
        return this.tipoAgendaProfissionals;
    }
    
    public void setTipoAgendaProfissionals(Set tipoAgendaProfissionals) {
        this.tipoAgendaProfissionals = tipoAgendaProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoAgenda")
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }




}


