package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoAgendaProfissional generated by hbm2java
 */
@Entity
@Table(name="TIPO_AGENDA_PROFISSIONAL"
    ,schema="DESENV"
)
public class TipoAgendaProfissional  implements java.io.Serializable {


     private TipoAgendaProfissionalId id;
     private Profissional profissional;
     private TipoAgenda tipoAgenda;
     private Empresa empresa;
     private short duracaoConsulta;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public TipoAgendaProfissional() {
    }

	
    public TipoAgendaProfissional(TipoAgendaProfissionalId id, Profissional profissional, TipoAgenda tipoAgenda, Empresa empresa, short duracaoConsulta) {
        this.id = id;
        this.profissional = profissional;
        this.tipoAgenda = tipoAgenda;
        this.empresa = empresa;
        this.duracaoConsulta = duracaoConsulta;
    }
    public TipoAgendaProfissional(TipoAgendaProfissionalId id, Profissional profissional, TipoAgenda tipoAgenda, Empresa empresa, short duracaoConsulta, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.profissional = profissional;
       this.tipoAgenda = tipoAgenda;
       this.empresa = empresa;
       this.duracaoConsulta = duracaoConsulta;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tiageId", column=@Column(name="TIAGE_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="profId", column=@Column(name="PROF_ID", nullable=false, precision=22, scale=0) ) } )
    public TipoAgendaProfissionalId getId() {
        return this.id;
    }
    
    public void setId(TipoAgendaProfissionalId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROF_ID", nullable=false, insertable=false, updatable=false)
    public Profissional getProfissional() {
        return this.profissional;
    }
    
    public void setProfissional(Profissional profissional) {
        this.profissional = profissional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="TIAGE_ID", referencedColumnName="ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="EMP_ID", referencedColumnName="EMP_ID", nullable=false, insertable=false, updatable=false) } )
    public TipoAgenda getTipoAgenda() {
        return this.tipoAgenda;
    }
    
    public void setTipoAgenda(TipoAgenda tipoAgenda) {
        this.tipoAgenda = tipoAgenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="DURACAO_CONSULTA", nullable=false, precision=3, scale=0)
    public short getDuracaoConsulta() {
        return this.duracaoConsulta;
    }
    
    public void setDuracaoConsulta(short duracaoConsulta) {
        this.duracaoConsulta = duracaoConsulta;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


