package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titulos generated by hbm2java
 */
@Entity
@Table(name="TITULOS"
    ,schema="DESENV"
)
public class Titulos  implements java.io.Serializable {


     private BigDecimal id;
     private Cobranca cobranca;
     private ConvenioBancario convenioBancario;
     private Paciente paciente;
     private Unidade unidade;
     private Empresa empresa;
     private BigDecimal nuDiasProtesto;
     private String flStatusRegistro;
     private String nossoNumero;
     private String nossoNumeroDv;
     private String linhaDigitavel;
     private String codigoBarras;
     private Date vencimento;
     private BigDecimal valorTitulo;
     private BigDecimal valorJurosGeracao;
     private BigDecimal valorMoraDia;
     private BigDecimal valorMulta;
     private BigDecimal valorPago;
     private BigDecimal valorPagoJuros;
     private BigDecimal valorPagoDesconto;
     private BigDecimal valorPagoOutrosRecebimentos;
     private String instrucao;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private char status;
     private Set pagamentosTituloses = new HashSet(0);
     private Set movimentoTitulos = new HashSet(0);

    public Titulos() {
    }

	
    public Titulos(BigDecimal id, ConvenioBancario convenioBancario, Paciente paciente, Unidade unidade, Empresa empresa, String nossoNumero, String linhaDigitavel, String codigoBarras, Date vencimento, BigDecimal valorTitulo, BigDecimal valorJurosGeracao, BigDecimal valorMoraDia, BigDecimal valorMulta, BigDecimal valorPago, BigDecimal valorPagoJuros, BigDecimal valorPagoDesconto, BigDecimal valorPagoOutrosRecebimentos, String instrucao, char status) {
        this.id = id;
        this.convenioBancario = convenioBancario;
        this.paciente = paciente;
        this.unidade = unidade;
        this.empresa = empresa;
        this.nossoNumero = nossoNumero;
        this.linhaDigitavel = linhaDigitavel;
        this.codigoBarras = codigoBarras;
        this.vencimento = vencimento;
        this.valorTitulo = valorTitulo;
        this.valorJurosGeracao = valorJurosGeracao;
        this.valorMoraDia = valorMoraDia;
        this.valorMulta = valorMulta;
        this.valorPago = valorPago;
        this.valorPagoJuros = valorPagoJuros;
        this.valorPagoDesconto = valorPagoDesconto;
        this.valorPagoOutrosRecebimentos = valorPagoOutrosRecebimentos;
        this.instrucao = instrucao;
        this.status = status;
    }
    public Titulos(BigDecimal id, Cobranca cobranca, ConvenioBancario convenioBancario, Paciente paciente, Unidade unidade, Empresa empresa, BigDecimal nuDiasProtesto, String flStatusRegistro, String nossoNumero, String nossoNumeroDv, String linhaDigitavel, String codigoBarras, Date vencimento, BigDecimal valorTitulo, BigDecimal valorJurosGeracao, BigDecimal valorMoraDia, BigDecimal valorMulta, BigDecimal valorPago, BigDecimal valorPagoJuros, BigDecimal valorPagoDesconto, BigDecimal valorPagoOutrosRecebimentos, String instrucao, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, char status, Set pagamentosTituloses, Set movimentoTitulos) {
       this.id = id;
       this.cobranca = cobranca;
       this.convenioBancario = convenioBancario;
       this.paciente = paciente;
       this.unidade = unidade;
       this.empresa = empresa;
       this.nuDiasProtesto = nuDiasProtesto;
       this.flStatusRegistro = flStatusRegistro;
       this.nossoNumero = nossoNumero;
       this.nossoNumeroDv = nossoNumeroDv;
       this.linhaDigitavel = linhaDigitavel;
       this.codigoBarras = codigoBarras;
       this.vencimento = vencimento;
       this.valorTitulo = valorTitulo;
       this.valorJurosGeracao = valorJurosGeracao;
       this.valorMoraDia = valorMoraDia;
       this.valorMulta = valorMulta;
       this.valorPago = valorPago;
       this.valorPagoJuros = valorPagoJuros;
       this.valorPagoDesconto = valorPagoDesconto;
       this.valorPagoOutrosRecebimentos = valorPagoOutrosRecebimentos;
       this.instrucao = instrucao;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.status = status;
       this.pagamentosTituloses = pagamentosTituloses;
       this.movimentoTitulos = movimentoTitulos;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="COB_PARCELA", referencedColumnName="PARCELA"), 
        @JoinColumn(name="COB_CONT_ID", referencedColumnName="CONT_ID") } )
    public Cobranca getCobranca() {
        return this.cobranca;
    }
    
    public void setCobranca(Cobranca cobranca) {
        this.cobranca = cobranca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CONV_BANCO", referencedColumnName="BANCO", nullable=false), 
        @JoinColumn(name="CONV_AGENCIA", referencedColumnName="AGENCIA", nullable=false), 
        @JoinColumn(name="CONV_CEDENTE", referencedColumnName="CEDENTE", nullable=false), 
        @JoinColumn(name="CONV_CARTEIRA", referencedColumnName="CARTEIRA", nullable=false), 
        @JoinColumn(name="CONV_CONVENIO", referencedColumnName="CONVENIO", nullable=false) } )
    public ConvenioBancario getConvenioBancario() {
        return this.convenioBancario;
    }
    
    public void setConvenioBancario(ConvenioBancario convenioBancario) {
        this.convenioBancario = convenioBancario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAC_ID", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NU_DIAS_PROTESTO", precision=22, scale=0)
    public BigDecimal getNuDiasProtesto() {
        return this.nuDiasProtesto;
    }
    
    public void setNuDiasProtesto(BigDecimal nuDiasProtesto) {
        this.nuDiasProtesto = nuDiasProtesto;
    }

    
    @Column(name="FL_STATUS_REGISTRO", length=3)
    public String getFlStatusRegistro() {
        return this.flStatusRegistro;
    }
    
    public void setFlStatusRegistro(String flStatusRegistro) {
        this.flStatusRegistro = flStatusRegistro;
    }

    
    @Column(name="NOSSO_NUMERO", nullable=false, length=25)
    public String getNossoNumero() {
        return this.nossoNumero;
    }
    
    public void setNossoNumero(String nossoNumero) {
        this.nossoNumero = nossoNumero;
    }

    
    @Column(name="NOSSO_NUMERO_DV", length=2)
    public String getNossoNumeroDv() {
        return this.nossoNumeroDv;
    }
    
    public void setNossoNumeroDv(String nossoNumeroDv) {
        this.nossoNumeroDv = nossoNumeroDv;
    }

    
    @Column(name="LINHA_DIGITAVEL", nullable=false)
    public String getLinhaDigitavel() {
        return this.linhaDigitavel;
    }
    
    public void setLinhaDigitavel(String linhaDigitavel) {
        this.linhaDigitavel = linhaDigitavel;
    }

    
    @Column(name="CODIGO_BARRAS", nullable=false)
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VENCIMENTO", nullable=false, length=7)
    public Date getVencimento() {
        return this.vencimento;
    }
    
    public void setVencimento(Date vencimento) {
        this.vencimento = vencimento;
    }

    
    @Column(name="VALOR_TITULO", nullable=false, precision=15)
    public BigDecimal getValorTitulo() {
        return this.valorTitulo;
    }
    
    public void setValorTitulo(BigDecimal valorTitulo) {
        this.valorTitulo = valorTitulo;
    }

    
    @Column(name="VALOR_JUROS_GERACAO", nullable=false, precision=15)
    public BigDecimal getValorJurosGeracao() {
        return this.valorJurosGeracao;
    }
    
    public void setValorJurosGeracao(BigDecimal valorJurosGeracao) {
        this.valorJurosGeracao = valorJurosGeracao;
    }

    
    @Column(name="VALOR_MORA_DIA", nullable=false, precision=15)
    public BigDecimal getValorMoraDia() {
        return this.valorMoraDia;
    }
    
    public void setValorMoraDia(BigDecimal valorMoraDia) {
        this.valorMoraDia = valorMoraDia;
    }

    
    @Column(name="VALOR_MULTA", nullable=false, precision=15)
    public BigDecimal getValorMulta() {
        return this.valorMulta;
    }
    
    public void setValorMulta(BigDecimal valorMulta) {
        this.valorMulta = valorMulta;
    }

    
    @Column(name="VALOR_PAGO", nullable=false, precision=15)
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    
    @Column(name="VALOR_PAGO_JUROS", nullable=false, precision=15)
    public BigDecimal getValorPagoJuros() {
        return this.valorPagoJuros;
    }
    
    public void setValorPagoJuros(BigDecimal valorPagoJuros) {
        this.valorPagoJuros = valorPagoJuros;
    }

    
    @Column(name="VALOR_PAGO_DESCONTO", nullable=false, precision=15)
    public BigDecimal getValorPagoDesconto() {
        return this.valorPagoDesconto;
    }
    
    public void setValorPagoDesconto(BigDecimal valorPagoDesconto) {
        this.valorPagoDesconto = valorPagoDesconto;
    }

    
    @Column(name="VALOR_PAGO_OUTROS_RECEBIMENTOS", nullable=false, precision=15)
    public BigDecimal getValorPagoOutrosRecebimentos() {
        return this.valorPagoOutrosRecebimentos;
    }
    
    public void setValorPagoOutrosRecebimentos(BigDecimal valorPagoOutrosRecebimentos) {
        this.valorPagoOutrosRecebimentos = valorPagoOutrosRecebimentos;
    }

    
    @Column(name="INSTRUCAO", nullable=false, length=4000)
    public String getInstrucao() {
        return this.instrucao;
    }
    
    public void setInstrucao(String instrucao) {
        this.instrucao = instrucao;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="STATUS", nullable=false, length=1)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="titulos")
    public Set getPagamentosTituloses() {
        return this.pagamentosTituloses;
    }
    
    public void setPagamentosTituloses(Set pagamentosTituloses) {
        this.pagamentosTituloses = pagamentosTituloses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="titulos")
    public Set getMovimentoTitulos() {
        return this.movimentoTitulos;
    }
    
    public void setMovimentoTitulos(Set movimentoTitulos) {
        this.movimentoTitulos = movimentoTitulos;
    }




}


