package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name="UNIDADE"
    ,schema="DESENV"
)
public class Unidade  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private String nome;
     private char ativa;
     private String nomeReduzido;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;
     private BigDecimal pcTributacao;
     private String obrigaCrm;
     private String cnpj;
     private String razaoSocial;
     private Set meioPagamentoContaUnidades = new HashSet(0);
     private Set procedimentoUnidades = new HashSet(0);
     private Set guiaPacientes = new HashSet(0);
     private Set usuarioUnidadeAgendas = new HashSet(0);
     private Set consumoItems = new HashSet(0);
     private Set cfgBancariaUnidades = new HashSet(0);
     private Set fechamentoConvenios = new HashSet(0);
     private Set itemUnidades = new HashSet(0);
     private Set pagamentoPacientes = new HashSet(0);
     private Set procedimentoPacientes = new HashSet(0);
     private Set contas = new HashSet(0);
     private Set documentoMensagemUnidades = new HashSet(0);
     private Set orcamentos = new HashSet(0);
     private Set balancoItems = new HashSet(0);
     private Set horarioUnidades = new HashSet(0);
     private Set repasseProfissionals = new HashSet(0);
     private Set tipoContratos = new HashSet(0);
     private Set pacientes = new HashSet(0);
     private Set consultorios = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set notaFiscals = new HashSet(0);
     private Set unidadeUsuarios = new HashSet(0);
     private Set inventarios = new HashSet(0);
     private Set portadors = new HashSet(0);
     private Set pagamentoProfissionals = new HashSet(0);
     private Set tituloses = new HashSet(0);

    public Unidade() {
    }

	
    public Unidade(BigDecimal id, Empresa empresa, String nome, char ativa, String nomeReduzido, BigDecimal pcTributacao, String razaoSocial) {
        this.id = id;
        this.empresa = empresa;
        this.nome = nome;
        this.ativa = ativa;
        this.nomeReduzido = nomeReduzido;
        this.pcTributacao = pcTributacao;
        this.razaoSocial = razaoSocial;
    }
    public Unidade(BigDecimal id, Empresa empresa, String nome, char ativa, String nomeReduzido, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao, BigDecimal pcTributacao, String obrigaCrm, String cnpj, String razaoSocial, Set meioPagamentoContaUnidades, Set procedimentoUnidades, Set guiaPacientes, Set usuarioUnidadeAgendas, Set consumoItems, Set cfgBancariaUnidades, Set fechamentoConvenios, Set itemUnidades, Set pagamentoPacientes, Set procedimentoPacientes, Set contas, Set documentoMensagemUnidades, Set orcamentos, Set balancoItems, Set horarioUnidades, Set repasseProfissionals, Set tipoContratos, Set pacientes, Set consultorios, Set contratos, Set notaFiscals, Set unidadeUsuarios, Set inventarios, Set portadors, Set pagamentoProfissionals, Set tituloses) {
       this.id = id;
       this.empresa = empresa;
       this.nome = nome;
       this.ativa = ativa;
       this.nomeReduzido = nomeReduzido;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
       this.pcTributacao = pcTributacao;
       this.obrigaCrm = obrigaCrm;
       this.cnpj = cnpj;
       this.razaoSocial = razaoSocial;
       this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
       this.procedimentoUnidades = procedimentoUnidades;
       this.guiaPacientes = guiaPacientes;
       this.usuarioUnidadeAgendas = usuarioUnidadeAgendas;
       this.consumoItems = consumoItems;
       this.cfgBancariaUnidades = cfgBancariaUnidades;
       this.fechamentoConvenios = fechamentoConvenios;
       this.itemUnidades = itemUnidades;
       this.pagamentoPacientes = pagamentoPacientes;
       this.procedimentoPacientes = procedimentoPacientes;
       this.contas = contas;
       this.documentoMensagemUnidades = documentoMensagemUnidades;
       this.orcamentos = orcamentos;
       this.balancoItems = balancoItems;
       this.horarioUnidades = horarioUnidades;
       this.repasseProfissionals = repasseProfissionals;
       this.tipoContratos = tipoContratos;
       this.pacientes = pacientes;
       this.consultorios = consultorios;
       this.contratos = contratos;
       this.notaFiscals = notaFiscals;
       this.unidadeUsuarios = unidadeUsuarios;
       this.inventarios = inventarios;
       this.portadors = portadors;
       this.pagamentoProfissionals = pagamentoProfissionals;
       this.tituloses = tituloses;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOME", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="ATIVA", nullable=false, length=1)
    public char getAtiva() {
        return this.ativa;
    }
    
    public void setAtiva(char ativa) {
        this.ativa = ativa;
    }

    
    @Column(name="NOME_REDUZIDO", nullable=false, length=15)
    public String getNomeReduzido() {
        return this.nomeReduzido;
    }
    
    public void setNomeReduzido(String nomeReduzido) {
        this.nomeReduzido = nomeReduzido;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }

    
    @Column(name="PC_TRIBUTACAO", nullable=false, precision=7, scale=4)
    public BigDecimal getPcTributacao() {
        return this.pcTributacao;
    }
    
    public void setPcTributacao(BigDecimal pcTributacao) {
        this.pcTributacao = pcTributacao;
    }

    
    @Column(name="OBRIGA_CRM", length=1)
    public String getObrigaCrm() {
        return this.obrigaCrm;
    }
    
    public void setObrigaCrm(String obrigaCrm) {
        this.obrigaCrm = obrigaCrm;
    }

    
    @Column(name="CNPJ", length=14)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="RAZAO_SOCIAL", nullable=false, length=100)
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getMeioPagamentoContaUnidades() {
        return this.meioPagamentoContaUnidades;
    }
    
    public void setMeioPagamentoContaUnidades(Set meioPagamentoContaUnidades) {
        this.meioPagamentoContaUnidades = meioPagamentoContaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getProcedimentoUnidades() {
        return this.procedimentoUnidades;
    }
    
    public void setProcedimentoUnidades(Set procedimentoUnidades) {
        this.procedimentoUnidades = procedimentoUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getGuiaPacientes() {
        return this.guiaPacientes;
    }
    
    public void setGuiaPacientes(Set guiaPacientes) {
        this.guiaPacientes = guiaPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getUsuarioUnidadeAgendas() {
        return this.usuarioUnidadeAgendas;
    }
    
    public void setUsuarioUnidadeAgendas(Set usuarioUnidadeAgendas) {
        this.usuarioUnidadeAgendas = usuarioUnidadeAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getConsumoItems() {
        return this.consumoItems;
    }
    
    public void setConsumoItems(Set consumoItems) {
        this.consumoItems = consumoItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getCfgBancariaUnidades() {
        return this.cfgBancariaUnidades;
    }
    
    public void setCfgBancariaUnidades(Set cfgBancariaUnidades) {
        this.cfgBancariaUnidades = cfgBancariaUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getFechamentoConvenios() {
        return this.fechamentoConvenios;
    }
    
    public void setFechamentoConvenios(Set fechamentoConvenios) {
        this.fechamentoConvenios = fechamentoConvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getItemUnidades() {
        return this.itemUnidades;
    }
    
    public void setItemUnidades(Set itemUnidades) {
        this.itemUnidades = itemUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getPagamentoPacientes() {
        return this.pagamentoPacientes;
    }
    
    public void setPagamentoPacientes(Set pagamentoPacientes) {
        this.pagamentoPacientes = pagamentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getProcedimentoPacientes() {
        return this.procedimentoPacientes;
    }
    
    public void setProcedimentoPacientes(Set procedimentoPacientes) {
        this.procedimentoPacientes = procedimentoPacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getContas() {
        return this.contas;
    }
    
    public void setContas(Set contas) {
        this.contas = contas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getDocumentoMensagemUnidades() {
        return this.documentoMensagemUnidades;
    }
    
    public void setDocumentoMensagemUnidades(Set documentoMensagemUnidades) {
        this.documentoMensagemUnidades = documentoMensagemUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Set orcamentos) {
        this.orcamentos = orcamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getBalancoItems() {
        return this.balancoItems;
    }
    
    public void setBalancoItems(Set balancoItems) {
        this.balancoItems = balancoItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getHorarioUnidades() {
        return this.horarioUnidades;
    }
    
    public void setHorarioUnidades(Set horarioUnidades) {
        this.horarioUnidades = horarioUnidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getRepasseProfissionals() {
        return this.repasseProfissionals;
    }
    
    public void setRepasseProfissionals(Set repasseProfissionals) {
        this.repasseProfissionals = repasseProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getTipoContratos() {
        return this.tipoContratos;
    }
    
    public void setTipoContratos(Set tipoContratos) {
        this.tipoContratos = tipoContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getConsultorios() {
        return this.consultorios;
    }
    
    public void setConsultorios(Set consultorios) {
        this.consultorios = consultorios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getNotaFiscals() {
        return this.notaFiscals;
    }
    
    public void setNotaFiscals(Set notaFiscals) {
        this.notaFiscals = notaFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getUnidadeUsuarios() {
        return this.unidadeUsuarios;
    }
    
    public void setUnidadeUsuarios(Set unidadeUsuarios) {
        this.unidadeUsuarios = unidadeUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getPortadors() {
        return this.portadors;
    }
    
    public void setPortadors(Set portadors) {
        this.portadors = portadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getPagamentoProfissionals() {
        return this.pagamentoProfissionals;
    }
    
    public void setPagamentoProfissionals(Set pagamentoProfissionals) {
        this.pagamentoProfissionals = pagamentoProfissionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getTituloses() {
        return this.tituloses;
    }
    
    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }




}


