package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UnidadeUsuario generated by hbm2java
 */
@Entity
@Table(name="UNIDADE_USUARIO"
    ,schema="DESENV"
)
public class UnidadeUsuario  implements java.io.Serializable {


     private UnidadeUsuarioId id;
     private GrupoUsuario grupoUsuario;
     private Unidade unidade;
     private Empresa empresa;
     private char flAlteracao;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public UnidadeUsuario() {
    }

	
    public UnidadeUsuario(UnidadeUsuarioId id, GrupoUsuario grupoUsuario, Unidade unidade, Empresa empresa, char flAlteracao) {
        this.id = id;
        this.grupoUsuario = grupoUsuario;
        this.unidade = unidade;
        this.empresa = empresa;
        this.flAlteracao = flAlteracao;
    }
    public UnidadeUsuario(UnidadeUsuarioId id, GrupoUsuario grupoUsuario, Unidade unidade, Empresa empresa, char flAlteracao, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.grupoUsuario = grupoUsuario;
       this.unidade = unidade;
       this.empresa = empresa;
       this.flAlteracao = flAlteracao;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="uniId", column=@Column(name="UNI_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="grusCdUsuario", column=@Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0) ) } )
    public UnidadeUsuarioId getId() {
        return this.id;
    }
    
    public void setId(UnidadeUsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUS_CD_USUARIO", nullable=false, insertable=false, updatable=false)
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNI_ID", nullable=false, insertable=false, updatable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="FL_ALTERACAO", nullable=false, length=1)
    public char getFlAlteracao() {
        return this.flAlteracao;
    }
    
    public void setFlAlteracao(char flAlteracao) {
        this.flAlteracao = flAlteracao;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


