package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuGrupoProg generated by hbm2java
 */
@Entity
@Table(name="USU_GRUPO_PROG"
    ,schema="DESENV"
)
public class UsuGrupoProg  implements java.io.Serializable {


     private UsuGrupoProgId id;
     private AgePrograma agePrograma;
     private GrupoUsuario grupoUsuario;
     private BigDecimal cdCriadoPor;
     private BigDecimal cdAlteradoPor;
     private Date dtCriacao;
     private Date dtUltimaAlteracao;

    public UsuGrupoProg() {
    }

    public UsuGrupoProg(UsuGrupoProgId id, AgePrograma agePrograma, GrupoUsuario grupoUsuario, BigDecimal cdCriadoPor, BigDecimal cdAlteradoPor, Date dtCriacao, Date dtUltimaAlteracao) {
       this.id = id;
       this.agePrograma = agePrograma;
       this.grupoUsuario = grupoUsuario;
       this.cdCriadoPor = cdCriadoPor;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtCriacao = dtCriacao;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="progCdPrograma", column=@Column(name="PROG_CD_PROGRAMA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="grusCdUsuario", column=@Column(name="GRUS_CD_USUARIO", nullable=false, precision=22, scale=0) ) } )
    public UsuGrupoProgId getId() {
        return this.id;
    }
    
    public void setId(UsuGrupoProgId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROG_CD_PROGRAMA", nullable=false, insertable=false, updatable=false)
    public AgePrograma getAgePrograma() {
        return this.agePrograma;
    }
    
    public void setAgePrograma(AgePrograma agePrograma) {
        this.agePrograma = agePrograma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GRUS_CD_USUARIO", nullable=false, insertable=false, updatable=false)
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }

    
    @Column(name="CD_CRIADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    
    @Column(name="CD_ALTERADO_POR", nullable=false, precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", nullable=false, length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", nullable=false, length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


