package com.sistemaclinica.entities;
// Generated 09/07/2015 17:16:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValorIndiceAtualizacao generated by hbm2java
 */
@Entity
@Table(name="VALOR_INDICE_ATUALIZACAO"
    ,schema="DESENV"
)
public class ValorIndiceAtualizacao  implements java.io.Serializable {


     private ValorIndiceAtualizacaoId id;
     private IndiceAtualizacao indiceAtualizacao;
     private Empresa empresa;
     private BigDecimal percentual;
     private BigDecimal cdCriadoPor;
     private Date dtCriacao;
     private BigDecimal cdAlteradoPor;
     private Date dtUltimaAlteracao;

    public ValorIndiceAtualizacao() {
    }

	
    public ValorIndiceAtualizacao(ValorIndiceAtualizacaoId id, IndiceAtualizacao indiceAtualizacao, Empresa empresa, BigDecimal percentual) {
        this.id = id;
        this.indiceAtualizacao = indiceAtualizacao;
        this.empresa = empresa;
        this.percentual = percentual;
    }
    public ValorIndiceAtualizacao(ValorIndiceAtualizacaoId id, IndiceAtualizacao indiceAtualizacao, Empresa empresa, BigDecimal percentual, BigDecimal cdCriadoPor, Date dtCriacao, BigDecimal cdAlteradoPor, Date dtUltimaAlteracao) {
       this.id = id;
       this.indiceAtualizacao = indiceAtualizacao;
       this.empresa = empresa;
       this.percentual = percentual;
       this.cdCriadoPor = cdCriadoPor;
       this.dtCriacao = dtCriacao;
       this.cdAlteradoPor = cdAlteradoPor;
       this.dtUltimaAlteracao = dtUltimaAlteracao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="indId", column=@Column(name="IND_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="competencia", column=@Column(name="COMPETENCIA", nullable=false, length=7) ) } )
    public ValorIndiceAtualizacaoId getId() {
        return this.id;
    }
    
    public void setId(ValorIndiceAtualizacaoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IND_ID", nullable=false, insertable=false, updatable=false)
    public IndiceAtualizacao getIndiceAtualizacao() {
        return this.indiceAtualizacao;
    }
    
    public void setIndiceAtualizacao(IndiceAtualizacao indiceAtualizacao) {
        this.indiceAtualizacao = indiceAtualizacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMP_ID", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="PERCENTUAL", nullable=false, precision=7, scale=4)
    public BigDecimal getPercentual() {
        return this.percentual;
    }
    
    public void setPercentual(BigDecimal percentual) {
        this.percentual = percentual;
    }

    
    @Column(name="CD_CRIADO_POR", precision=22, scale=0)
    public BigDecimal getCdCriadoPor() {
        return this.cdCriadoPor;
    }
    
    public void setCdCriadoPor(BigDecimal cdCriadoPor) {
        this.cdCriadoPor = cdCriadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_CRIACAO", length=7)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="CD_ALTERADO_POR", precision=22, scale=0)
    public BigDecimal getCdAlteradoPor() {
        return this.cdAlteradoPor;
    }
    
    public void setCdAlteradoPor(BigDecimal cdAlteradoPor) {
        this.cdAlteradoPor = cdAlteradoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DT_ULTIMA_ALTERACAO", length=7)
    public Date getDtUltimaAlteracao() {
        return this.dtUltimaAlteracao;
    }
    
    public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
        this.dtUltimaAlteracao = dtUltimaAlteracao;
    }




}


